#!/bin/sh
#
#  Makes a library of the FFT routines
#
#
mpif90 -O3 -c fftgen.f
mpif90 -O3 -c fftgin.f
#
mpif90 -O3 -c fftfr2.f
mpif90 -O3 -c fftfr3.f
mpif90 -O3 -c fftfr5.f
mpif90 -O3 -c fftfr7.f
mpif90 -O3 -c fftfra.f
#
mpif90 -O3 -c fftnr2.f
mpif90 -O3 -c fftnr3.f
mpif90 -O3 -c fftnr5.f
mpif90 -O3 -c fftnr7.f
mpif90 -O3 -c fftnra.f
#
mpif90 -O3 -c fftp1d.f
mpif90 -O3 -c fftpin.f
mpif90 -O3 -c fftf1d.f
#
ar rcsv fftlib.a \
        fftgen.o fftgin.o \
        fftfr2.o fftfr3.o fftfr5.o fftfr7.o fftfra.o \
        fftnr2.o fftnr3.o fftnr5.o fftnr7.o fftnra.o \
        fftp1d.o fftpin.o fftf1d.o
#
rm *.o
#
exit
