C     PPCCOM--------------------------------------------------------------------

C     PARAMETERS
C     ==========
      DOUBLE PRECISION ZERO, ONE, TWO, THREE
      PARAMETER(ZERO = 0.0D0, ONE = 1.0D0, TWO = 2.0D0, THREE = 3.0D0)
      DOUBLE PRECISION CSCTOL
      PARAMETER(CSCTOL = 1.0D-6)
      INTEGER NCINPT,NCREPT,NCMECH,NCSPEC,NCOUTP
      PARAMETER(NCINPT=5, NCREPT=6, NCMECH=1, NCSPEC=2, NCOUTP=7)
      INTEGER IENULL,IEINFO,IEWARN,IERROR,IESEVR,IEFATL
      PARAMETER(IENULL=0,
     +          IEINFO=1, IEWARN=2, IERROR=3, IESEVR=4, IEFATL=5)
      INTEGER ICHNUL,ICHSTR,ICHEND,ICHINT,ICHSNT,ICHRNO
      PARAMETER(ICHNUL=0,
     +          ICHSTR=1, ICHEND=2, ICHINT=3, ICHSNT=4, ICHRNO=5)
      INTEGER NFCMAX
      PARAMETER(NFCMAX=5)

      CHARACTER*50 BLANKS
      PARAMETER(
     +   BLANKS='                                                  ')


C     GLOBAL DATA
C     ===========
      DOUBLE PRECISION CRTABL(NSPCMX,NSTPMX)
      DOUBLE PRECISION CPTABL(NSPCMX,NSTPMX)
      DOUBLE PRECISION RFCONV(NFCMAX)
      DOUBLE PRECISION RORDER(NSTPMX)

      INTEGER NRTABL(NSPCMX,NSTPMX)
      INTEGER NPTABL(NSPCMX,NSTPMX)

      INTEGER LENNAM(NSPCMX)
      INTEGER NUMSPC(NSPCMX)
      INTEGER NUMSTP(NSTPMX)
      INTEGER NORDER(NSTPMX)
      INTEGER NUMBDY(NBDYMX)
 
      CHARACTER*50 SPCNAM(NSPCMX)
      CHARACTER*80 FNMECH,FNSPEC,FNOUTP

      COMMON/PPCCOM/CRTABL,CPTABL,RFCONV,RORDER,
     +              NRTABL,NPTABL,NUMSPC,NUMSTP,NORDER,NUMBDY,
     +              LENNAM,SPCNAM,FNMECH,FNSPEC,FNOUTP

C     PPCCOM--------------------------------------------------------------------
