#!/bin/bash


# Slurm job options (job-name, compute nodes, job time)
#SBATCH --job-name=1DH2FL
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=128
#SBATCH --cpus-per-task=1

# Replace [budget code] below with your budget code (e.g. t01)
#SBATCH --account=e01-NU-Ahmed
#SBATCH --partition=standard
#SBATCH --qos=standard
#####SBATCH --qos=standard
#####SBATCH --qos=lowpriority

# Set the number of threads to 1
#   This prevents any threaded system libraries from automatically
#   using threading.
export OMP_NUM_THREADS=1

#Set CPU frequency to 2.25 GHz
export SLURM_CPU_FREQ_REQ=2250000

# Launch the parallel job
#   Using 512 MPI processes and 128 MPI processes per node
#   srun picks up the distribution from the sbatch options

#srun --cpu-bind=1458 ./senga
srun -n 100 ./senga2
