#!/bin/bash --login
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=128
#SBATCH --time=48:00:00
#SBATCH --job-name=TGVOPS
#SBATCH --account=e01-NU-Ahmed


#SBATCH --partition=standard
#SBATCH --qos=long
####SBATCH --qos=lowpriority
####SBATCH --reservation=shortqos
####SBATCH --error=/work/e01/e01/ashutoshl/senga_org/fortran90-3D/SENGA2/EO/job.%J.err
####SBATCH --output=/work/e01/e01/ashutoshl/senga_org/fortran90-3D/SENGA2/EO/job.%J.out

export OMP_NUM_THREADS=1

echo "Submission directory is ${SLURM_SUBMIT_DIR}"

# Setup the batch environment
cd /work/e01/e01/ve01/SENGA_OPS
#source setup_env_gnu_ops.sh
source ops_source_environment.sh

cd $SLURM_SUBMIT_DIR

time srun --distribution=block:block --hint=nomultithread --unbuffered --ntasks-per-node=128 --ntasks=512 ./senga2_mpi 2>&1 | tee log_new_1nodes.txt
#srun -n 512 ./senga2_mpi
