!
! auto-generated by ops_fortran.py
!

MODULE BOUNDT_KERNEL_EQG_YDIR_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1

INTEGER(KIND=4) xdim2
#define OPS_ACC2(x,y,z) (x+xdim2*(y)+xdim2*ydim2*(z)+1)
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2

INTEGER(KIND=4) xdim3
#define OPS_ACC3(x,y,z) (x+xdim3*(y)+xdim3*ydim3*(z)+1)
INTEGER(KIND=4) ydim3
INTEGER(KIND=4) zdim3

INTEGER(KIND=4) xdim4
#define OPS_ACC4(x,y,z) (x+xdim4*(y)+xdim4*ydim4*(z)+1)
INTEGER(KIND=4) ydim4
INTEGER(KIND=4) zdim4

contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: boundt_kernel_eqG_ydir


SUBROUTINE boundt_kernel_eqG_ydir(erhs,yrhs,itndex,strty,amasch,rgspec,ncpoly,ncpom1,ncenth,ispec,icoef1,icoef2)
    use data_types
    implicit none

    real(kind=8), dimension(1) :: erhs
    integer(kind=4), dimension(1), intent(in) :: itndex
    real(kind=8), dimension(1), intent(in) :: yrhs,strty

    integer(kind=4), intent(in) :: ispec,icoef1,icoef2

    real(kind=8), dimension(ncofmx,ntinmx,nspcmx), intent(in) :: amasch
    real(kind=8), dimension(nspcmx), intent(in) :: rgspec
    integer(kind=4), dimension(ntinmx,nspcmx), intent(in) :: ncpoly,ncpom1,ncenth

    real(kind=8) :: fornow
    integer(kind=4) :: itint,icp

    itint = 1 +MOD(itndex(OPS_ACC3(0,0,0)),icoef1)/icoef2
    fornow = amasch(ncpoly(itint,ispec),itint,ispec)

    DO icp = ncpom1(itint,ispec),1,-1
        fornow = fornow*strty(OPS_ACC4(0,0,0)) + amasch(icp,itint,ispec)
    END DO

    fornow = amasch(ncenth(itint,ispec),itint,ispec)  &
              + fornow*strty(OPS_ACC4(0,0,0))

    erhs(OPS_ACC1(0,0,0)) = erhs(OPS_ACC1(0,0,0))  &
                      + (fornow-rgspec(ispec)*strty(OPS_ACC4(0,0,0)))*yrhs(OPS_ACC2(0,0,0))

END SUBROUTINE


#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4


subroutine boundt_kernel_eqG_ydir_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& opsDat3Local, &
& opsDat4Local, &
& opsDat5Local, &
& opsDat6Local, &
& opsDat7Local, &
& opsDat8Local, &
& opsDat9Local, &
& opsDat10Local, &
& opsDat11Local, &
& opsDat12Local, &
& dat1_base, &
& dat2_base, &
& dat3_base, &
& dat4_base, &
& dat5_base, &
& dat6_base, &
& dat7_base, &
& dat8_base, &
& dat9_base, &
& dat10_base, &
& dat11_base, &
& dat12_base, &
& start_indx, &
& end_indx )

  IMPLICIT NONE

  real(kind=8), dimension(*), intent(inout) :: opsDat1Local
  integer(4) :: dat1_base
  real(kind=8), dimension(*), intent(in)    :: opsDat2Local
  integer(4) :: dat2_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat3Local
  integer(4) :: dat3_base
  real(kind=8), dimension(*), intent(in)    :: opsDat4Local
  integer(4) :: dat4_base
  real(kind=8), dimension(*), intent(in)    :: opsDat5Local
  integer(4) :: dat5_base
  real(kind=8), dimension(*), intent(in)    :: opsDat6Local
  integer(4) :: dat6_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat7Local
  integer(4) :: dat7_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat8Local
  integer(4) :: dat8_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat9Local
  integer(4) :: dat9_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat10Local
  integer(4) :: dat10_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat11Local
  integer(4) :: dat11_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat12Local
  integer(4) :: dat12_base
  integer(4), dimension(3), intent(in) :: start_indx, end_indx
  integer(4) :: n_x, n_y, n_z

  DO n_z = 1, end_indx(3)-start_indx(3)+1
    DO n_y = 1, end_indx(2)-start_indx(2)+1
      !$OMP SIMD
      DO n_x = 1, end_indx(1)-start_indx(1)+1

        call boundt_kernel_eqG_ydir( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base+(n_x-1)*1 + (n_y-1)*xdim2*1 + (n_z-1)*ydim2*xdim2*1), &
        & opsDat3Local(dat3_base+(n_x-1)*1 + (n_y-1)*xdim3*1 + (n_z-1)*ydim3*xdim3*1), &
        & opsDat4Local(dat4_base+(n_x-1)*1 + (n_y-1)*xdim4*1 + (n_z-1)*ydim4*xdim4*1), &
        & opsDat5Local(dat5_base), &
        & opsDat6Local(dat6_base), &
        & opsDat7Local(dat7_base), &
        & opsDat8Local(dat8_base), &
        & opsDat9Local(dat9_base), &
        & opsDat10Local(dat10_base), &
        & opsDat11Local(dat11_base), &
        & opsDat12Local(dat12_base) )

      END DO
    END DO
  END DO

end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine boundt_kernel_eqG_ydir_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10, &
& opsArg11, &
& opsArg12)

  IMPLICIT NONE

  character(kind=c_char,len=*), intent(in) :: userSubroutine
  type(ops_block), intent(in) :: block
  integer(4), intent(in):: dim
  integer(4), dimension(2*dim), intent(in) :: range
  type(ops_arg), intent(in) :: opsArg1
  type(ops_arg), intent(in) :: opsArg2
  type(ops_arg), intent(in) :: opsArg3
  type(ops_arg), intent(in) :: opsArg4
  type(ops_arg), intent(in) :: opsArg5
  type(ops_arg), intent(in) :: opsArg6
  type(ops_arg), intent(in) :: opsArg7
  type(ops_arg), intent(in) :: opsArg8
  type(ops_arg), intent(in) :: opsArg9
  type(ops_arg), intent(in) :: opsArg10
  type(ops_arg), intent(in) :: opsArg11
  type(ops_arg), intent(in) :: opsArg12

  type(ops_arg), dimension(12) :: opsArgArray
#else
subroutine boundt_kernel_eqG_ydir_host_execute( descPtr )

  USE ISO_C_BINDING
  IMPLICIT NONE

  type(ops_kernel_descriptor), intent(in) :: descPtr
  type(ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, dimension(:) :: range
  character(kind=c_char), pointer, dimension(:) :: userSubroutine
  type(ops_arg), pointer, dimension(:) :: opsArgArray
  type(ops_arg) :: opsArg1
  type(ops_arg) :: opsArg2
  type(ops_arg) :: opsArg3
  type(ops_arg) :: opsArg4
  type(ops_arg) :: opsArg5
  type(ops_arg) :: opsArg6
  type(ops_arg) :: opsArg7
  type(ops_arg) :: opsArg8
  type(ops_arg) :: opsArg9
  type(ops_arg) :: opsArg10
  type(ops_arg) :: opsArg11
  type(ops_arg) :: opsArg12
#endif

  real(kind=8), pointer, dimension(:) :: opsDat1Local
  integer(4) :: opsDat1Cardinality
  integer(4), pointer, dimension(:)  :: dat1_size
  integer(4) :: dat1_base

  real(kind=8), pointer, dimension(:) :: opsDat2Local
  integer(4) :: opsDat2Cardinality
  integer(4), pointer, dimension(:)  :: dat2_size
  integer(4) :: dat2_base

  integer(kind=4), pointer, dimension(:) :: opsDat3Local
  integer(4) :: opsDat3Cardinality
  integer(4), pointer, dimension(:)  :: dat3_size
  integer(4) :: dat3_base

  real(kind=8), pointer, dimension(:) :: opsDat4Local
  integer(4) :: opsDat4Cardinality
  integer(4), pointer, dimension(:)  :: dat4_size
  integer(4) :: dat4_base

  real(kind=8), pointer, dimension(:) :: opsDat5Local
  integer(4) :: dat5_base

  real(kind=8), pointer, dimension(:) :: opsDat6Local
  integer(4) :: dat6_base

  integer(kind=4), pointer, dimension(:) :: opsDat7Local
  integer(4) :: dat7_base

  integer(kind=4), pointer, dimension(:) :: opsDat8Local
  integer(4) :: dat8_base

  integer(kind=4), pointer, dimension(:) :: opsDat9Local
  integer(4) :: dat9_base

  integer(kind=4), pointer, dimension(:) :: opsDat10Local
  integer(4) :: dat10_base

  integer(kind=4), pointer, dimension(:) :: opsDat11Local
  integer(4) :: dat11_base

  integer(kind=4), pointer, dimension(:) :: opsDat12Local
  integer(4) :: dat12_base

  real(8) :: t1,t2,t3
  real(4) :: transfer_total, transfer
  integer(4), dimension(3) :: start_indx, end_indx
  integer(4) :: n


#ifdef OPS_LAZY
!  Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)
  opsArg4 = opsArgArray(4)
  opsArg5 = opsArgArray(5)
  opsArg6 = opsArgArray(6)
  opsArg7 = opsArgArray(7)
  opsArg8 = opsArgArray(8)
  opsArg9 = opsArgArray(9)
  opsArg10 = opsArgArray(10)
  opsArg11 = opsArgArray(11)
  opsArg12 = opsArgArray(12)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
  opsArgArray(11) = opsArg11
  opsArgArray(12) = opsArg12
#endif

  call setKernelTime(477,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start_indx, end_indx, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start_indx(n) = range(2*n-1)
    end_indx(n)   = range(2*n)
  END DO
#else
  DO n = 1, 3
    start_indx(n) = range(2*n-1) + 1
    end_indx(n)   = range(2*n) 
  END DO
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start_indx,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start_indx,1)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg3),dat3_size,(/dim/))
  xdim3 = dat3_size(1)
  ydim3 = dat3_size(2)
  zdim3 = dat3_size(3)
  opsDat3Cardinality = opsArg3%dim * xdim3 * ydim3 * zdim3
  dat3_base = getDatBaseFromOpsArg3D(opsArg3,start_indx,1)
  call c_f_pointer(opsArg3%data,opsDat3Local,(/opsDat3Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg4),dat4_size,(/dim/))
  xdim4 = dat4_size(1)
  ydim4 = dat4_size(2)
  zdim4 = dat4_size(3)
  opsDat4Cardinality = opsArg4%dim * xdim4 * ydim4 * zdim4
  dat4_base = getDatBaseFromOpsArg3D(opsArg4,start_indx,1)
  call c_f_pointer(opsArg4%data,opsDat4Local,(/opsDat4Cardinality/))

  call c_f_pointer(getGblPtrFromOpsArg(opsArg5),opsDat5Local, (/opsArg5%dim/))
  dat5_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg6),opsDat6Local, (/opsArg6%dim/))
  dat6_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg7),opsDat7Local, (/opsArg7%dim/))
  dat7_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg8),opsDat8Local, (/opsArg8%dim/))
  dat8_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg9),opsDat9Local, (/opsArg9%dim/))
  dat9_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg10),opsDat10Local, (/opsArg10%dim/))
  dat10_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg11),opsDat11Local, (/opsArg11%dim/))
  dat11_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg12),opsDat12Local, (/opsArg12%dim/))
  dat12_base = 1

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,12)
  call ops_halo_exchanges(opsArgArray,12,range)
  call ops_H_D_exchanges_host(opsArgArray,12)
#endif

  call ops_timers_core(t2)

  call boundt_kernel_eqG_ydir_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & opsDat3Local, &
  & opsDat4Local, &
  & opsDat5Local, &
  & opsDat6Local, &
  & opsDat7Local, &
  & opsDat8Local, &
  & opsDat9Local, &
  & opsDat10Local, &
  & opsDat11Local, &
  & opsDat12Local, &
  & dat1_base, &
  & dat2_base, &
  & dat3_base, &
  & dat4_base, &
  & dat5_base, &
  & dat6_base, &
  & dat7_base, &
  & dat8_base, &
  & dat9_base, &
  & dat10_base, &
  & dat11_base, &
  & dat12_base, &
  & start_indx, &
  & end_indx )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 12)
  call ops_set_halo_dirtybit3(opsArg1,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start_indx, end_indx, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg3,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg4,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(477,userSubroutine,t3-t2,t2-t1,transfer_total,0)

end subroutine

#ifdef OPS_LAZY
subroutine boundt_kernel_eqG_ydir_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10, &
& opsArg11, &
& opsArg12)

  IMPLICIT NONE

  character(kind=c_char,len=*), intent(in), target :: userSubroutine
  type(ops_block), intent(in) :: block
  integer(4), intent(in) :: dim
  integer(4), dimension(2*dim), intent(inout), target :: range
  integer(4), dimension(2*dim), target :: range_tmp
  type(ops_arg), intent(in) :: opsArg1
  type(ops_arg), intent(in) :: opsArg2
  type(ops_arg), intent(in) :: opsArg3
  type(ops_arg), intent(in) :: opsArg4
  type(ops_arg), intent(in) :: opsArg5
  type(ops_arg), intent(in) :: opsArg6
  type(ops_arg), intent(in) :: opsArg7
  type(ops_arg), intent(in) :: opsArg8
  type(ops_arg), intent(in) :: opsArg9
  type(ops_arg), intent(in) :: opsArg10
  type(ops_arg), intent(in) :: opsArg11
  type(ops_arg), intent(in) :: opsArg12

  type(ops_arg), dimension(12), target :: opsArgArray
  integer(4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
  opsArgArray(11) = opsArg11
  opsArgArray(12) = opsArg12

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 12, 477, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(boundt_kernel_eqG_ydir_host_execute))

end subroutine
#endif

END MODULE
