!
! auto-generated by ops_fortran.py
!

MODULE BOUNDS_KERNEL_WALLBC1_COMPUTEL_XL_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1

INTEGER(KIND=4) xdim2
#define OPS_ACC2(x,y,z) (x+xdim2*(y)+xdim2*ydim2*(z)+1)
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2

INTEGER(KIND=4) xdim3
#define OPS_ACC3(x,y,z) (x+xdim3*(y)+xdim3*ydim3*(z)+1)
INTEGER(KIND=4) ydim3
INTEGER(KIND=4) zdim3

INTEGER(KIND=4) xdim4
#define OPS_ACC4(x,y,z) (x+xdim4*(y)+xdim4*ydim4*(z)+1)
INTEGER(KIND=4) ydim4
INTEGER(KIND=4) zdim4

INTEGER(KIND=4) xdim5
#define OPS_ACC5(x,y,z) (x+xdim5*(y)+xdim5*ydim5*(z)+1)
INTEGER(KIND=4) ydim5
INTEGER(KIND=4) zdim5

INTEGER(KIND=4) xdim6
#define OPS_ACC6(x,y,z) (x+xdim6*(y)+xdim6*ydim6*(z)+1)
INTEGER(KIND=4) ydim6
INTEGER(KIND=4) zdim6

INTEGER(KIND=4) xdim7
#define OPS_ACC7(x,y,z) (x+xdim7*(y)+xdim7*ydim7*(z)+1)
INTEGER(KIND=4) ydim7
INTEGER(KIND=4) zdim7

INTEGER(KIND=4) xdim8
#define OPS_ACC8(x,y,z) (x+xdim8*(y)+xdim8*ydim8*(z)+1)
INTEGER(KIND=4) ydim8
INTEGER(KIND=4) zdim8

INTEGER(KIND=4) xdim9
#define OPS_ACC9(x,y,z) (x+xdim9*(y)+xdim9*ydim9*(z)+1)
INTEGER(KIND=4) ydim9
INTEGER(KIND=4) zdim9

INTEGER(KIND=4) xdim10
#define OPS_ACC10(x,y,z) (x+xdim10*(y)+xdim10*ydim10*(z)+1)
INTEGER(KIND=4) ydim10
INTEGER(KIND=4) zdim10

contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: bounds_kernel_wallBC1_computeL_xl


SUBROUTINE bounds_kernel_wallBC1_computeL_xl(bcl1xl,bcl3xl,bcl4xl,bcl5xl,strdxl,acouxl,struxl,dudtxl,dvdtxl,dwdtxl)
    use data_types
    implicit none

    real(kind=8), dimension(1) :: bcl1xl,bcl3xl,bcl4xl,bcl5xl
    real(kind=8), dimension(1), intent(in) :: strdxl,acouxl,struxl,dudtxl,dvdtxl,dwdtxl
    real(kind=8) :: fornow

    fornow = strdxl(OPS_ACC5(0,0,0))*acouxl(OPS_ACC6(0,0,0))*bcl1xl(OPS_ACC1(0,0,0))
    bcl1xl(OPS_ACC1(0,0,0)) = 0.5_8*(struxl(OPS_ACC7(0,0,0))-acouxl(OPS_ACC6(0,0,0)))  &
            *(bcl5xl(OPS_ACC4(0,0,0))-fornow)
    bcl3xl(OPS_ACC2(0,0,0)) = struxl(OPS_ACC7(0,0,0))*bcl3xl(OPS_ACC2(0,0,0))
    bcl4xl(OPS_ACC3(0,0,0)) = struxl(OPS_ACC7(0,0,0))*bcl4xl(OPS_ACC3(0,0,0))
    bcl5xl(OPS_ACC4(0,0,0)) = 0.5_8*(struxl(OPS_ACC7(0,0,0))+acouxl(OPS_ACC6(0,0,0)))  &
            *(bcl5xl(OPS_ACC4(0,0,0))+fornow)


    bcl3xl(OPS_ACC2(0,0,0)) = -dvdtxl(OPS_ACC9(0,0,0)) - bcl3xl(OPS_ACC2(0,0,0))
    bcl4xl(OPS_ACC3(0,0,0)) = -dwdtxl(OPS_ACC10(0,0,0)) - bcl4xl(OPS_ACC3(0,0,0))
    bcl5xl(OPS_ACC4(0,0,0)) = bcl1xl(OPS_ACC1(0,0,0))  &
            - strdxl(OPS_ACC5(0,0,0))*acouxl(OPS_ACC6(0,0,0))*dudtxl(OPS_ACC8(0,0,0)) - bcl5xl(OPS_ACC4(0,0,0))

END SUBROUTINE


#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC5
#undef OPS_ACC6
#undef OPS_ACC7
#undef OPS_ACC8
#undef OPS_ACC9
#undef OPS_ACC10


subroutine bounds_kernel_wallBC1_computeL_xl_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& opsDat3Local, &
& opsDat4Local, &
& opsDat5Local, &
& opsDat6Local, &
& opsDat7Local, &
& opsDat8Local, &
& opsDat9Local, &
& opsDat10Local, &
& dat1_base, &
& dat2_base, &
& dat3_base, &
& dat4_base, &
& dat5_base, &
& dat6_base, &
& dat7_base, &
& dat8_base, &
& dat9_base, &
& dat10_base, &
& start_indx, &
& end_indx )

  IMPLICIT NONE

  real(kind=8), dimension(*), intent(inout) :: opsDat1Local
  integer(4) :: dat1_base
  real(kind=8), dimension(*), intent(inout) :: opsDat2Local
  integer(4) :: dat2_base
  real(kind=8), dimension(*), intent(inout) :: opsDat3Local
  integer(4) :: dat3_base
  real(kind=8), dimension(*), intent(inout) :: opsDat4Local
  integer(4) :: dat4_base
  real(kind=8), dimension(*), intent(in)    :: opsDat5Local
  integer(4) :: dat5_base
  real(kind=8), dimension(*), intent(in)    :: opsDat6Local
  integer(4) :: dat6_base
  real(kind=8), dimension(*), intent(in)    :: opsDat7Local
  integer(4) :: dat7_base
  real(kind=8), dimension(*), intent(in)    :: opsDat8Local
  integer(4) :: dat8_base
  real(kind=8), dimension(*), intent(in)    :: opsDat9Local
  integer(4) :: dat9_base
  real(kind=8), dimension(*), intent(in)    :: opsDat10Local
  integer(4) :: dat10_base
  integer(4), dimension(3), intent(in) :: start_indx, end_indx
  integer(4) :: n_x, n_y, n_z

  DO n_z = 1, end_indx(3)-start_indx(3)+1
    DO n_y = 1, end_indx(2)-start_indx(2)+1
      !$OMP SIMD
      DO n_x = 1, end_indx(1)-start_indx(1)+1

        call bounds_kernel_wallBC1_computeL_xl( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base+(n_x-1)*1 + (n_y-1)*xdim2*1 + (n_z-1)*ydim2*xdim2*1), &
        & opsDat3Local(dat3_base+(n_x-1)*1 + (n_y-1)*xdim3*1 + (n_z-1)*ydim3*xdim3*1), &
        & opsDat4Local(dat4_base+(n_x-1)*1 + (n_y-1)*xdim4*1 + (n_z-1)*ydim4*xdim4*1), &
        & opsDat5Local(dat5_base+(n_x-1)*1 + (n_y-1)*xdim5*1 + (n_z-1)*ydim5*xdim5*1), &
        & opsDat6Local(dat6_base+(n_x-1)*1 + (n_y-1)*xdim6*1 + (n_z-1)*ydim6*xdim6*1), &
        & opsDat7Local(dat7_base+(n_x-1)*1 + (n_y-1)*xdim7*1 + (n_z-1)*ydim7*xdim7*1), &
        & opsDat8Local(dat8_base+(n_x-1)*1 + (n_y-1)*xdim8*1 + (n_z-1)*ydim8*xdim8*1), &
        & opsDat9Local(dat9_base+(n_x-1)*1 + (n_y-1)*xdim9*1 + (n_z-1)*ydim9*xdim9*1), &
        & opsDat10Local(dat10_base+(n_x-1)*1 + (n_y-1)*xdim10*1 + (n_z-1)*ydim10*xdim10*1) )

      END DO
    END DO
  END DO

end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine bounds_kernel_wallBC1_computeL_xl_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10)

  IMPLICIT NONE

  character(kind=c_char,len=*), intent(in) :: userSubroutine
  type(ops_block), intent(in) :: block
  integer(4), intent(in):: dim
  integer(4), dimension(2*dim), intent(in) :: range
  type(ops_arg), intent(in) :: opsArg1
  type(ops_arg), intent(in) :: opsArg2
  type(ops_arg), intent(in) :: opsArg3
  type(ops_arg), intent(in) :: opsArg4
  type(ops_arg), intent(in) :: opsArg5
  type(ops_arg), intent(in) :: opsArg6
  type(ops_arg), intent(in) :: opsArg7
  type(ops_arg), intent(in) :: opsArg8
  type(ops_arg), intent(in) :: opsArg9
  type(ops_arg), intent(in) :: opsArg10

  type(ops_arg), dimension(10) :: opsArgArray
#else
subroutine bounds_kernel_wallBC1_computeL_xl_host_execute( descPtr )

  USE ISO_C_BINDING
  IMPLICIT NONE

  type(ops_kernel_descriptor), intent(in) :: descPtr
  type(ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, dimension(:) :: range
  character(kind=c_char), pointer, dimension(:) :: userSubroutine
  type(ops_arg), pointer, dimension(:) :: opsArgArray
  type(ops_arg) :: opsArg1
  type(ops_arg) :: opsArg2
  type(ops_arg) :: opsArg3
  type(ops_arg) :: opsArg4
  type(ops_arg) :: opsArg5
  type(ops_arg) :: opsArg6
  type(ops_arg) :: opsArg7
  type(ops_arg) :: opsArg8
  type(ops_arg) :: opsArg9
  type(ops_arg) :: opsArg10
#endif

  real(kind=8), pointer, dimension(:) :: opsDat1Local
  integer(4) :: opsDat1Cardinality
  integer(4), pointer, dimension(:)  :: dat1_size
  integer(4) :: dat1_base

  real(kind=8), pointer, dimension(:) :: opsDat2Local
  integer(4) :: opsDat2Cardinality
  integer(4), pointer, dimension(:)  :: dat2_size
  integer(4) :: dat2_base

  real(kind=8), pointer, dimension(:) :: opsDat3Local
  integer(4) :: opsDat3Cardinality
  integer(4), pointer, dimension(:)  :: dat3_size
  integer(4) :: dat3_base

  real(kind=8), pointer, dimension(:) :: opsDat4Local
  integer(4) :: opsDat4Cardinality
  integer(4), pointer, dimension(:)  :: dat4_size
  integer(4) :: dat4_base

  real(kind=8), pointer, dimension(:) :: opsDat5Local
  integer(4) :: opsDat5Cardinality
  integer(4), pointer, dimension(:)  :: dat5_size
  integer(4) :: dat5_base

  real(kind=8), pointer, dimension(:) :: opsDat6Local
  integer(4) :: opsDat6Cardinality
  integer(4), pointer, dimension(:)  :: dat6_size
  integer(4) :: dat6_base

  real(kind=8), pointer, dimension(:) :: opsDat7Local
  integer(4) :: opsDat7Cardinality
  integer(4), pointer, dimension(:)  :: dat7_size
  integer(4) :: dat7_base

  real(kind=8), pointer, dimension(:) :: opsDat8Local
  integer(4) :: opsDat8Cardinality
  integer(4), pointer, dimension(:)  :: dat8_size
  integer(4) :: dat8_base

  real(kind=8), pointer, dimension(:) :: opsDat9Local
  integer(4) :: opsDat9Cardinality
  integer(4), pointer, dimension(:)  :: dat9_size
  integer(4) :: dat9_base

  real(kind=8), pointer, dimension(:) :: opsDat10Local
  integer(4) :: opsDat10Cardinality
  integer(4), pointer, dimension(:)  :: dat10_size
  integer(4) :: dat10_base

  real(8) :: t1,t2,t3
  real(4) :: transfer_total, transfer
  integer(4), dimension(3) :: start_indx, end_indx
  integer(4) :: n


#ifdef OPS_LAZY
!  Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)
  opsArg4 = opsArgArray(4)
  opsArg5 = opsArgArray(5)
  opsArg6 = opsArgArray(6)
  opsArg7 = opsArgArray(7)
  opsArg8 = opsArgArray(8)
  opsArg9 = opsArgArray(9)
  opsArg10 = opsArgArray(10)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
#endif

  call setKernelTime(347,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start_indx, end_indx, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start_indx(n) = range(2*n-1)
    end_indx(n)   = range(2*n)
  END DO
#else
  DO n = 1, 3
    start_indx(n) = range(2*n-1) + 1
    end_indx(n)   = range(2*n) 
  END DO
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start_indx,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start_indx,1)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg3),dat3_size,(/dim/))
  xdim3 = dat3_size(1)
  ydim3 = dat3_size(2)
  zdim3 = dat3_size(3)
  opsDat3Cardinality = opsArg3%dim * xdim3 * ydim3 * zdim3
  dat3_base = getDatBaseFromOpsArg3D(opsArg3,start_indx,1)
  call c_f_pointer(opsArg3%data,opsDat3Local,(/opsDat3Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg4),dat4_size,(/dim/))
  xdim4 = dat4_size(1)
  ydim4 = dat4_size(2)
  zdim4 = dat4_size(3)
  opsDat4Cardinality = opsArg4%dim * xdim4 * ydim4 * zdim4
  dat4_base = getDatBaseFromOpsArg3D(opsArg4,start_indx,1)
  call c_f_pointer(opsArg4%data,opsDat4Local,(/opsDat4Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg5),dat5_size,(/dim/))
  xdim5 = dat5_size(1)
  ydim5 = dat5_size(2)
  zdim5 = dat5_size(3)
  opsDat5Cardinality = opsArg5%dim * xdim5 * ydim5 * zdim5
  dat5_base = getDatBaseFromOpsArg3D(opsArg5,start_indx,1)
  call c_f_pointer(opsArg5%data,opsDat5Local,(/opsDat5Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg6),dat6_size,(/dim/))
  xdim6 = dat6_size(1)
  ydim6 = dat6_size(2)
  zdim6 = dat6_size(3)
  opsDat6Cardinality = opsArg6%dim * xdim6 * ydim6 * zdim6
  dat6_base = getDatBaseFromOpsArg3D(opsArg6,start_indx,1)
  call c_f_pointer(opsArg6%data,opsDat6Local,(/opsDat6Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg7),dat7_size,(/dim/))
  xdim7 = dat7_size(1)
  ydim7 = dat7_size(2)
  zdim7 = dat7_size(3)
  opsDat7Cardinality = opsArg7%dim * xdim7 * ydim7 * zdim7
  dat7_base = getDatBaseFromOpsArg3D(opsArg7,start_indx,1)
  call c_f_pointer(opsArg7%data,opsDat7Local,(/opsDat7Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg8),dat8_size,(/dim/))
  xdim8 = dat8_size(1)
  ydim8 = dat8_size(2)
  zdim8 = dat8_size(3)
  opsDat8Cardinality = opsArg8%dim * xdim8 * ydim8 * zdim8
  dat8_base = getDatBaseFromOpsArg3D(opsArg8,start_indx,1)
  call c_f_pointer(opsArg8%data,opsDat8Local,(/opsDat8Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg9),dat9_size,(/dim/))
  xdim9 = dat9_size(1)
  ydim9 = dat9_size(2)
  zdim9 = dat9_size(3)
  opsDat9Cardinality = opsArg9%dim * xdim9 * ydim9 * zdim9
  dat9_base = getDatBaseFromOpsArg3D(opsArg9,start_indx,1)
  call c_f_pointer(opsArg9%data,opsDat9Local,(/opsDat9Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg10),dat10_size,(/dim/))
  xdim10 = dat10_size(1)
  ydim10 = dat10_size(2)
  zdim10 = dat10_size(3)
  opsDat10Cardinality = opsArg10%dim * xdim10 * ydim10 * zdim10
  dat10_base = getDatBaseFromOpsArg3D(opsArg10,start_indx,1)
  call c_f_pointer(opsArg10%data,opsDat10Local,(/opsDat10Cardinality/))

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,10)
  call ops_halo_exchanges(opsArgArray,10,range)
  call ops_H_D_exchanges_host(opsArgArray,10)
#endif

  call ops_timers_core(t2)

  call bounds_kernel_wallBC1_computeL_xl_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & opsDat3Local, &
  & opsDat4Local, &
  & opsDat5Local, &
  & opsDat6Local, &
  & opsDat7Local, &
  & opsDat8Local, &
  & opsDat9Local, &
  & opsDat10Local, &
  & dat1_base, &
  & dat2_base, &
  & dat3_base, &
  & dat4_base, &
  & dat5_base, &
  & dat6_base, &
  & dat7_base, &
  & dat8_base, &
  & dat9_base, &
  & dat10_base, &
  & start_indx, &
  & end_indx )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 10)
  call ops_set_halo_dirtybit3(opsArg1,range)
  call ops_set_halo_dirtybit3(opsArg2,range)
  call ops_set_halo_dirtybit3(opsArg3,range)
  call ops_set_halo_dirtybit3(opsArg4,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start_indx, end_indx, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg3,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg4,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg5,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg6,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg7,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg8,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg9,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg10,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(347,userSubroutine,t3-t2,t2-t1,transfer_total,0)

end subroutine

#ifdef OPS_LAZY
subroutine bounds_kernel_wallBC1_computeL_xl_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10)

  IMPLICIT NONE

  character(kind=c_char,len=*), intent(in), target :: userSubroutine
  type(ops_block), intent(in) :: block
  integer(4), intent(in) :: dim
  integer(4), dimension(2*dim), intent(inout), target :: range
  integer(4), dimension(2*dim), target :: range_tmp
  type(ops_arg), intent(in) :: opsArg1
  type(ops_arg), intent(in) :: opsArg2
  type(ops_arg), intent(in) :: opsArg3
  type(ops_arg), intent(in) :: opsArg4
  type(ops_arg), intent(in) :: opsArg5
  type(ops_arg), intent(in) :: opsArg6
  type(ops_arg), intent(in) :: opsArg7
  type(ops_arg), intent(in) :: opsArg8
  type(ops_arg), intent(in) :: opsArg9
  type(ops_arg), intent(in) :: opsArg10

  type(ops_arg), dimension(10), target :: opsArgArray
  integer(4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 10, 347, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(bounds_kernel_wallBC1_computeL_xl_host_execute))

end subroutine
#endif

END MODULE
