!
! auto-generated by ops_fortran.py
!
MODULE BOUNDT_KERNEL_EQD_YDIR_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim3
#define OPS_ACC3(x,y,z) (x+xdim3*(y)+xdim3*ydim3*(z)+1)
INTEGER(KIND=4) ydim3
INTEGER(KIND=4) zdim3

INTEGER(KIND=4) multi_d1
INTEGER(KIND=4) xdim1
#define OPS_ACC_MD1(d,x,y,z) ((x)*multi_d1 + (d) + (xdim1*(y)*multi_d1) + (xdim1*ydim1*(z)*multi_d1))
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1
INTEGER(KIND=4) multi_d2
INTEGER(KIND=4) xdim2
#define OPS_ACC_MD2(d,x,y,z) ((x)*multi_d2 + (d) + (xdim2*(y)*multi_d2) + (xdim2*ydim2*(z)*multi_d2))
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2

contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: boundt_kernel_eqD_ydir


SUBROUTINE boundt_kernel_eqD_ydir(yrhs,stryy,strdy,ispec)
    use data_types
    implicit none

    real(kind=8), dimension(1) :: yrhs
    real(kind=8), dimension(1), intent(in) :: stryy,strdy
    integer, intent(in) :: ispec

    yrhs(OPS_ACC_MD1(ispec,0,0,0)) = strdy(OPS_ACC3(0,0,0))*stryy(OPS_ACC_MD2(ispec,0,0,0))

END SUBROUTINE


#undef OPS_ACC3

#undef OPS_ACC_MD1
#undef OPS_ACC_MD2


subroutine boundt_kernel_eqD_ydir_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& opsDat3Local, &
& opsDat4Local, &
& dat1_base, &
& dat2_base, &
& dat3_base, &
& dat4_base, &
& start, &
& end )
  IMPLICIT NONE
  real(8) opsDat1Local(*)
  real(8), INTENT(IN) :: opsDat2Local(*)
  real(8), INTENT(IN) :: opsDat3Local(*)
  integer opsDat4Local(*)
  integer dat1_base
  integer dat2_base
  integer dat3_base
  integer dat4_base
  integer(4) start(3)
  integer(4) end(3)
  integer n_x, n_y, n_z

  DO n_z = 1, end(3)-start(3)+1
    DO n_y = 1, end(2)-start(2)+1
      !$OMP SIMD
      DO n_x = 1, end(1)-start(1)+1
        call boundt_kernel_eqD_ydir( &
        & opsDat1Local(dat1_base+(n_x-1)*9 + (n_y-1)*xdim1*9 + (n_z-1)*ydim1*xdim1*9), &
        & opsDat2Local(dat2_base+(n_x-1)*9 + (n_y-1)*xdim2*9 + (n_z-1)*ydim2*xdim2*9), &
        & opsDat3Local(dat3_base+(n_x-1)*1 + (n_y-1)*xdim3*1 + (n_z-1)*ydim3*xdim3*1), &
        & opsDat4Local(dat4_base) )
      END DO
    END DO
  END DO
end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine boundt_kernel_eqD_ydir_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4)   , DIMENSION(2*dim), INTENT(IN) :: range
  type ( ops_arg )  , INTENT(IN) :: opsArg1
  type ( ops_arg )  , INTENT(IN) :: opsArg2
  type ( ops_arg )  , INTENT(IN) :: opsArg3
  type ( ops_arg )  , INTENT(IN) :: opsArg4

  type ( ops_arg ) , DIMENSION(4) :: opsArgArray
#else
subroutine boundt_kernel_eqD_ydir_host_execute( descPtr )
  use iso_c_binding
  IMPLICIT NONE
  type (ops_kernel_descriptor), intent(in) :: descPtr
  type (ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, DIMENSION(:) :: range
  character(kind=c_char), pointer, DIMENSION(:) :: userSubroutine
  type ( ops_arg ) , pointer, DIMENSION(:) :: opsArgArray
  type ( ops_arg ) :: opsArg1
  type ( ops_arg ) :: opsArg2
  type ( ops_arg ) :: opsArg3
  type ( ops_arg ) :: opsArg4
#endif

  real(8), POINTER, DIMENSION(:) :: opsDat1Local
  integer(kind=4) :: opsDat1Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat1_size
  integer(kind=4) :: dat1_base

  real(8), POINTER, DIMENSION(:) :: opsDat2Local
  integer(kind=4) :: opsDat2Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat2_size
  integer(kind=4) :: dat2_base

  real(8), POINTER, DIMENSION(:) :: opsDat3Local
  integer(kind=4) :: opsDat3Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat3_size
  integer(kind=4) :: dat3_base

  integer, POINTER, DIMENSION(:) :: opsDat4Local
  integer(kind=4) :: dat4_base

  real(kind=8) t1,t2,t3
  real(kind=4) transfer_total, transfer
  integer start(3)
  integer end(3)
  integer(kind=4) :: n


#ifdef OPS_LAZY
  !Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)
  opsArg4 = opsArgArray(4)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
#endif

  call setKernelTime(502,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start, end, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start(n) = range(2*n-1)
    end(n) = range(2*n)
  END DO
#else
  DO n = 1, 3
    start(n) = range(2*n-1) + 1
    end(n) = range(2*n) 
  END DO
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  multi_d1 = getDatDimFromOpsArg(opsArg1) ! dimension of the dat
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start,multi_d1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  multi_d2 = getDatDimFromOpsArg(opsArg2) ! dimension of the dat
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start,multi_d2)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg3),dat3_size,(/dim/))
  xdim3 = dat3_size(1)
  ydim3 = dat3_size(2)
  zdim3 = dat3_size(3)
  opsDat3Cardinality = opsArg3%dim * xdim3 * ydim3 * zdim3
  dat3_base = getDatBaseFromOpsArg3D(opsArg3,start,1)
  call c_f_pointer(opsArg3%data,opsDat3Local,(/opsDat3Cardinality/))

  call c_f_pointer(getGblPtrFromOpsArg(opsArg4),opsDat4Local, (/opsArg4%dim/))
  dat4_base = 1

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,4)
  call ops_halo_exchanges(opsArgArray,4,range)
  call ops_H_D_exchanges_host(opsArgArray,4)
#endif

  call ops_timers_core(t2)

  call boundt_kernel_eqD_ydir_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & opsDat3Local, &
  & opsDat4Local, &
  & dat1_base, &
  & dat2_base, &
  & dat3_base, &
  & dat4_base, &
  & start, &
  & end )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 4)
  call ops_set_halo_dirtybit3(opsArg1,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start, end, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg3,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(502,userSubroutine,t3-t2,t2-t1,transfer_total,0)
end subroutine

#ifdef OPS_LAZY
subroutine boundt_kernel_eqD_ydir_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN), TARGET :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4), DIMENSION(2*dim), INTENT(INOUT), TARGET :: range
  integer(kind=4), DIMENSION(2*dim), TARGET :: range_tmp
  type ( ops_arg ), INTENT(IN) :: opsArg1
  type ( ops_arg ), INTENT(IN) :: opsArg2
  type ( ops_arg ), INTENT(IN) :: opsArg3
  type ( ops_arg ), INTENT(IN) :: opsArg4
  type ( ops_arg ), DIMENSION(4), TARGET :: opsArgArray
  integer(kind=4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 4, 502, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(boundt_kernel_eqD_ydir_host_execute))
end subroutine
#endif

END MODULE
