!
! auto-generated by ops_fortran.py
!
MODULE BOUNDT_KERNEL_EQG_ZDIR_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1
INTEGER(KIND=4) xdim4
#define OPS_ACC4(x,y,z) (x+xdim4*(y)+xdim4*ydim4*(z)+1)
INTEGER(KIND=4) ydim4
INTEGER(KIND=4) zdim4

INTEGER(KIND=4) multi_d2
INTEGER(KIND=4) xdim2
#define OPS_ACC_MD2(d,x,y,z) ((x)*multi_d2 + (d) + (xdim2*(y)*multi_d2) + (xdim2*ydim2*(z)*multi_d2))
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2
INTEGER(KIND=4) multi_d3
INTEGER(KIND=4) xdim3
#define OPS_ACC_MD3(d,x,y,z) ((x)*multi_d3 + (d) + (xdim3*(y)*multi_d3) + (xdim3*ydim3*(z)*multi_d3))
INTEGER(KIND=4) ydim3
INTEGER(KIND=4) zdim3

contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: boundt_kernel_eqG_zdir


SUBROUTINE boundt_kernel_eqG_zdir(erhs,yrhs,itndex,strtz,amasch,rgspec,ncpoly,ncpom1,ncenth,ispec,iindex,icoef1,icoef2)
    use data_types
    implicit none

    real(kind=8), dimension(1) :: erhs
    integer, dimension(1), intent(in) :: itndex
    real(kind=8), dimension(1), intent(in) :: yrhs,strtz

    integer, intent(in) :: ispec,iindex,icoef1,icoef2

    real(kind=8), dimension(ncofmx,ntinmx,nspcmx), intent(in) :: amasch
    real(kind=8), dimension(nspcmx), intent(in) :: rgspec
    integer, dimension(ntinmx,nspcmx), intent(in) :: ncpoly,ncpom1,ncenth

    real(kind=8) :: fornow
    integer :: itint,icp

    itint = 1 +MOD(itndex(OPS_ACC_MD3(iindex,0,0,0)),icoef1)/icoef2
    fornow = amasch(ncpoly(itint,ispec),itint,ispec)

    DO icp = ncpom1(itint,ispec),1,-1
        fornow = fornow*strtz(OPS_ACC4(0,0,0)) + amasch(icp,itint,ispec)
    END DO

    fornow = amasch(ncenth(itint,ispec),itint,ispec)  &
              + fornow*strtz(OPS_ACC4(0,0,0))

    erhs(OPS_ACC1(0,0,0)) = erhs(OPS_ACC1(0,0,0))  &
                      + (fornow-rgspec(ispec)*strtz(OPS_ACC4(0,0,0)))*yrhs(OPS_ACC_MD2(ispec,0,0,0))

END SUBROUTINE


#undef OPS_ACC1
#undef OPS_ACC4

#undef OPS_ACC_MD2
#undef OPS_ACC_MD3


subroutine boundt_kernel_eqG_zdir_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& opsDat3Local, &
& opsDat4Local, &
& opsDat5Local, &
& opsDat6Local, &
& opsDat7Local, &
& opsDat8Local, &
& opsDat9Local, &
& opsDat10Local, &
& opsDat11Local, &
& opsDat12Local, &
& opsDat13Local, &
& dat1_base, &
& dat2_base, &
& dat3_base, &
& dat4_base, &
& dat5_base, &
& dat6_base, &
& dat7_base, &
& dat8_base, &
& dat9_base, &
& dat10_base, &
& dat11_base, &
& dat12_base, &
& dat13_base, &
& start, &
& end )
  IMPLICIT NONE
  real(8) opsDat1Local(*)
  real(8), INTENT(IN) :: opsDat2Local(*)
  integer, INTENT(IN) :: opsDat3Local(*)
  real(8), INTENT(IN) :: opsDat4Local(*)
  real(8) opsDat5Local(*)
  real(8) opsDat6Local(*)
  integer opsDat7Local(*)
  integer opsDat8Local(*)
  integer opsDat9Local(*)
  integer opsDat10Local(*)
  integer opsDat11Local(*)
  integer opsDat12Local(*)
  integer opsDat13Local(*)
  integer dat1_base
  integer dat2_base
  integer dat3_base
  integer dat4_base
  integer dat5_base
  integer dat6_base
  integer dat7_base
  integer dat8_base
  integer dat9_base
  integer dat10_base
  integer dat11_base
  integer dat12_base
  integer dat13_base
  integer(4) start(3)
  integer(4) end(3)
  integer n_x, n_y, n_z

  DO n_z = 1, end(3)-start(3)+1
    DO n_y = 1, end(2)-start(2)+1
      !$OMP SIMD
      DO n_x = 1, end(1)-start(1)+1
        call boundt_kernel_eqG_zdir( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base+(n_x-1)*9 + (n_y-1)*xdim2*9 + (n_z-1)*ydim2*xdim2*9), &
        & opsDat3Local(dat3_base+(n_x-1)*2 + (n_y-1)*xdim3*2 + (n_z-1)*ydim3*xdim3*2), &
        & opsDat4Local(dat4_base+(n_x-1)*1 + (n_y-1)*xdim4*1 + (n_z-1)*ydim4*xdim4*1), &
        & opsDat5Local(dat5_base), &
        & opsDat6Local(dat6_base), &
        & opsDat7Local(dat7_base), &
        & opsDat8Local(dat8_base), &
        & opsDat9Local(dat9_base), &
        & opsDat10Local(dat10_base), &
        & opsDat11Local(dat11_base), &
        & opsDat12Local(dat12_base), &
        & opsDat13Local(dat13_base) )
      END DO
    END DO
  END DO
end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine boundt_kernel_eqG_zdir_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10, &
& opsArg11, &
& opsArg12, &
& opsArg13)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4)   , DIMENSION(2*dim), INTENT(IN) :: range
  type ( ops_arg )  , INTENT(IN) :: opsArg1
  type ( ops_arg )  , INTENT(IN) :: opsArg2
  type ( ops_arg )  , INTENT(IN) :: opsArg3
  type ( ops_arg )  , INTENT(IN) :: opsArg4
  type ( ops_arg )  , INTENT(IN) :: opsArg5
  type ( ops_arg )  , INTENT(IN) :: opsArg6
  type ( ops_arg )  , INTENT(IN) :: opsArg7
  type ( ops_arg )  , INTENT(IN) :: opsArg8
  type ( ops_arg )  , INTENT(IN) :: opsArg9
  type ( ops_arg )  , INTENT(IN) :: opsArg10
  type ( ops_arg )  , INTENT(IN) :: opsArg11
  type ( ops_arg )  , INTENT(IN) :: opsArg12
  type ( ops_arg )  , INTENT(IN) :: opsArg13

  type ( ops_arg ) , DIMENSION(13) :: opsArgArray
#else
subroutine boundt_kernel_eqG_zdir_host_execute( descPtr )
  use iso_c_binding
  IMPLICIT NONE
  type (ops_kernel_descriptor), intent(in) :: descPtr
  type (ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, DIMENSION(:) :: range
  character(kind=c_char), pointer, DIMENSION(:) :: userSubroutine
  type ( ops_arg ) , pointer, DIMENSION(:) :: opsArgArray
  type ( ops_arg ) :: opsArg1
  type ( ops_arg ) :: opsArg2
  type ( ops_arg ) :: opsArg3
  type ( ops_arg ) :: opsArg4
  type ( ops_arg ) :: opsArg5
  type ( ops_arg ) :: opsArg6
  type ( ops_arg ) :: opsArg7
  type ( ops_arg ) :: opsArg8
  type ( ops_arg ) :: opsArg9
  type ( ops_arg ) :: opsArg10
  type ( ops_arg ) :: opsArg11
  type ( ops_arg ) :: opsArg12
  type ( ops_arg ) :: opsArg13
#endif

  real(8), POINTER, DIMENSION(:) :: opsDat1Local
  integer(kind=4) :: opsDat1Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat1_size
  integer(kind=4) :: dat1_base

  real(8), POINTER, DIMENSION(:) :: opsDat2Local
  integer(kind=4) :: opsDat2Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat2_size
  integer(kind=4) :: dat2_base

  integer, POINTER, DIMENSION(:) :: opsDat3Local
  integer(kind=4) :: opsDat3Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat3_size
  integer(kind=4) :: dat3_base

  real(8), POINTER, DIMENSION(:) :: opsDat4Local
  integer(kind=4) :: opsDat4Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat4_size
  integer(kind=4) :: dat4_base

  real(8), POINTER, DIMENSION(:) :: opsDat5Local
  integer(kind=4) :: dat5_base

  real(8), POINTER, DIMENSION(:) :: opsDat6Local
  integer(kind=4) :: dat6_base

  integer, POINTER, DIMENSION(:) :: opsDat7Local
  integer(kind=4) :: dat7_base

  integer, POINTER, DIMENSION(:) :: opsDat8Local
  integer(kind=4) :: dat8_base

  integer, POINTER, DIMENSION(:) :: opsDat9Local
  integer(kind=4) :: dat9_base

  integer, POINTER, DIMENSION(:) :: opsDat10Local
  integer(kind=4) :: dat10_base

  integer, POINTER, DIMENSION(:) :: opsDat11Local
  integer(kind=4) :: dat11_base

  integer, POINTER, DIMENSION(:) :: opsDat12Local
  integer(kind=4) :: dat12_base

  integer, POINTER, DIMENSION(:) :: opsDat13Local
  integer(kind=4) :: dat13_base

  real(kind=8) t1,t2,t3
  real(kind=4) transfer_total, transfer
  integer start(3)
  integer end(3)
  integer(kind=4) :: n


#ifdef OPS_LAZY
  !Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)
  opsArg4 = opsArgArray(4)
  opsArg5 = opsArgArray(5)
  opsArg6 = opsArgArray(6)
  opsArg7 = opsArgArray(7)
  opsArg8 = opsArgArray(8)
  opsArg9 = opsArgArray(9)
  opsArg10 = opsArgArray(10)
  opsArg11 = opsArgArray(11)
  opsArg12 = opsArgArray(12)
  opsArg13 = opsArgArray(13)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
  opsArgArray(11) = opsArg11
  opsArgArray(12) = opsArg12
  opsArgArray(13) = opsArg13
#endif

  call setKernelTime(492,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start, end, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start(n) = range(2*n-1)
    end(n) = range(2*n)
  END DO
#else
  DO n = 1, 3
    start(n) = range(2*n-1) + 1
    end(n) = range(2*n) 
  END DO
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  multi_d2 = getDatDimFromOpsArg(opsArg2) ! dimension of the dat
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start,multi_d2)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg3),dat3_size,(/dim/))
  xdim3 = dat3_size(1)
  ydim3 = dat3_size(2)
  zdim3 = dat3_size(3)
  opsDat3Cardinality = opsArg3%dim * xdim3 * ydim3 * zdim3
  multi_d3 = getDatDimFromOpsArg(opsArg3) ! dimension of the dat
  dat3_base = getDatBaseFromOpsArg3D(opsArg3,start,multi_d3)
  call c_f_pointer(opsArg3%data,opsDat3Local,(/opsDat3Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg4),dat4_size,(/dim/))
  xdim4 = dat4_size(1)
  ydim4 = dat4_size(2)
  zdim4 = dat4_size(3)
  opsDat4Cardinality = opsArg4%dim * xdim4 * ydim4 * zdim4
  dat4_base = getDatBaseFromOpsArg3D(opsArg4,start,1)
  call c_f_pointer(opsArg4%data,opsDat4Local,(/opsDat4Cardinality/))

  call c_f_pointer(getGblPtrFromOpsArg(opsArg5),opsDat5Local, (/opsArg5%dim/))
  dat5_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg6),opsDat6Local, (/opsArg6%dim/))
  dat6_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg7),opsDat7Local, (/opsArg7%dim/))
  dat7_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg8),opsDat8Local, (/opsArg8%dim/))
  dat8_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg9),opsDat9Local, (/opsArg9%dim/))
  dat9_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg10),opsDat10Local, (/opsArg10%dim/))
  dat10_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg11),opsDat11Local, (/opsArg11%dim/))
  dat11_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg12),opsDat12Local, (/opsArg12%dim/))
  dat12_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg13),opsDat13Local, (/opsArg13%dim/))
  dat13_base = 1

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,13)
  call ops_halo_exchanges(opsArgArray,13,range)
  call ops_H_D_exchanges_host(opsArgArray,13)
#endif

  call ops_timers_core(t2)

  call boundt_kernel_eqG_zdir_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & opsDat3Local, &
  & opsDat4Local, &
  & opsDat5Local, &
  & opsDat6Local, &
  & opsDat7Local, &
  & opsDat8Local, &
  & opsDat9Local, &
  & opsDat10Local, &
  & opsDat11Local, &
  & opsDat12Local, &
  & opsDat13Local, &
  & dat1_base, &
  & dat2_base, &
  & dat3_base, &
  & dat4_base, &
  & dat5_base, &
  & dat6_base, &
  & dat7_base, &
  & dat8_base, &
  & dat9_base, &
  & dat10_base, &
  & dat11_base, &
  & dat12_base, &
  & dat13_base, &
  & start, &
  & end )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 13)
  call ops_set_halo_dirtybit3(opsArg1,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start, end, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg3,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg4,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(492,userSubroutine,t3-t2,t2-t1,transfer_total,0)
end subroutine

#ifdef OPS_LAZY
subroutine boundt_kernel_eqG_zdir_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10, &
& opsArg11, &
& opsArg12, &
& opsArg13)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN), TARGET :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4), DIMENSION(2*dim), INTENT(INOUT), TARGET :: range
  integer(kind=4), DIMENSION(2*dim), TARGET :: range_tmp
  type ( ops_arg ), INTENT(IN) :: opsArg1
  type ( ops_arg ), INTENT(IN) :: opsArg2
  type ( ops_arg ), INTENT(IN) :: opsArg3
  type ( ops_arg ), INTENT(IN) :: opsArg4
  type ( ops_arg ), INTENT(IN) :: opsArg5
  type ( ops_arg ), INTENT(IN) :: opsArg6
  type ( ops_arg ), INTENT(IN) :: opsArg7
  type ( ops_arg ), INTENT(IN) :: opsArg8
  type ( ops_arg ), INTENT(IN) :: opsArg9
  type ( ops_arg ), INTENT(IN) :: opsArg10
  type ( ops_arg ), INTENT(IN) :: opsArg11
  type ( ops_arg ), INTENT(IN) :: opsArg12
  type ( ops_arg ), INTENT(IN) :: opsArg13
  type ( ops_arg ), DIMENSION(13), TARGET :: opsArgArray
  integer(kind=4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
  opsArgArray(11) = opsArg11
  opsArgArray(12) = opsArg12
  opsArgArray(13) = opsArg13

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 13, 492, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(boundt_kernel_eqG_zdir_host_execute))
end subroutine
#endif

END MODULE
