!
! auto-generated by ops_fortran.py
!

MODULE D2FDX2_KERNEL_MAIN_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1

INTEGER(KIND=4) xdim2
#define OPS_ACC2(x,y,z) (x+xdim2*(y)+xdim2*ydim2*(z)+1)
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2

contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: d2fdx2_kernel_main
SUBROUTINE d2fdx2_kernel_main(functn, fderiv, nxglbl, nendxl, nendxr, nbound, idx)
    use data_types
    implicit none

    real(kind=8), dimension(1), intent(in) :: functn
    real(kind=8), dimension(1) :: fderiv
    real(kind=8) :: fdifap,fdifbp,fdifcp,fdifdp,fdifep
    real(kind=8) :: fdifam,fdifbm,fdifcm,fdifdm,fdifem

    integer(kind=4), intent(in) :: nxglbl, nendxl, nendxr, nbound
    integer(kind=4), dimension(3), intent(in) :: idx
    integer(kind=4) :: ic, istart, ifinis

    istart = 1
    ifinis = nxglbl
    IF(nendxl == nbound) istart = 6
    IF(nendxr == nbound) ifinis = nxglbl-5

    ic = idx(1)

    IF (ic >= istart .and. ic <= ifinis) THEN

        fdifap = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifam = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-1,0,0))
        fdifbp = functn(OPS_ACC1(2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-2,0,0))
        fdifcp = functn(OPS_ACC1(3,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifcm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-3,0,0))
        fdifdp = functn(OPS_ACC1(4,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifdm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-4,0,0))
        fdifep = functn(OPS_ACC1(5,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifem = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-5,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acofsx*(fdifap-fdifam) + bcofsx*(fdifbp-fdifbm)  &
                                + ccofsx*(fdifcp-fdifcm) + dcofsx*(fdifdp-fdifdm)  &
                                + ecofsx*(fdifep-fdifem)

    ELSE IF (ic == 1) THEN

        fdifap = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbp = functn(OPS_ACC1(2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifcp = functn(OPS_ACC1(3,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifdp = functn(OPS_ACC1(4,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifep = functn(OPS_ACC1(5,0,0)) - functn(OPS_ACC1(0,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs1x*fdifap + bcfs1x*fdifbp  &
                                + ccfs1x*fdifcp + dcfs1x*fdifdp  &
                                + ecfs1x*fdifep

    ELSE IF (ic == 2) THEN

        fdifap = functn(OPS_ACC1(-1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbp = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifcp = functn(OPS_ACC1(2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifdp = functn(OPS_ACC1(3,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifep = functn(OPS_ACC1(4,0,0)) - functn(OPS_ACC1(0,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs2x*fdifap + bcfs2x*fdifbp  &
                                + ccfs2x*fdifcp + dcfs2x*fdifdp  &
                                + ecfs2x*fdifep

    ELSE IF (ic == 3) THEN

        fdifap = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifam = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-1,0,0))
        fdifbp = functn(OPS_ACC1(2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-2,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs3x*(fdifap-fdifam) + bcfs3x*(fdifbp-fdifbm)

    ELSE IF (ic == 4) THEN

        fdifap = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifam = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-1,0,0))
        fdifbp = functn(OPS_ACC1(2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-2,0,0))
        fdifcp = functn(OPS_ACC1(3,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifcm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-3,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs4x*(fdifap-fdifam)  &
                                + bcfs4x*(fdifbp-fdifbm) + ccfs4x*(fdifcp-fdifcm)

    ELSE IF (ic == 5) THEN

        fdifap = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifam = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-1,0,0))
        fdifbp = functn(OPS_ACC1(2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-2,0,0))
        fdifcp = functn(OPS_ACC1(3,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifcm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-3,0,0))
        fdifdp = functn(OPS_ACC1(4,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifdm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-4,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs5x*(fdifap-fdifam)  &
                                + bcfs5x*(fdifbp-fdifbm) + ccfs5x*(fdifcp-fdifcm)  &
                                + dcfs5x*(fdifdp-fdifdm)

    ELSE IF (ic == nxglbl-4) THEN

        fdifap = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifam = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-1,0,0))
        fdifbp = functn(OPS_ACC1(2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-2,0,0))
        fdifcp = functn(OPS_ACC1(3,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifcm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-3,0,0))
        fdifdp = functn(OPS_ACC1(4,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifdm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-4,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs5x*(fdifap-fdifam)  &
                                + bcfs5x*(fdifbp-fdifbm) + ccfs5x*(fdifcp-fdifcm)  &
                                + dcfs5x*(fdifdp-fdifdm)

    ELSE IF (ic == nxglbl-3) THEN

        fdifap = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifam = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-1,0,0))
        fdifbp = functn(OPS_ACC1(2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-2,0,0))
        fdifcp = functn(OPS_ACC1(3,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifcm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-3,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs4x*(fdifap-fdifam)  &
                                + bcfs4x*(fdifbp-fdifbm) + ccfs4x*(fdifcp-fdifcm)

    ELSE IF (ic == nxglbl-2) THEN

        fdifap = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifam = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-1,0,0))
        fdifbp = functn(OPS_ACC1(2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbm = functn(OPS_ACC1(0,0,0)) - functn(OPS_ACC1(-2,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs3x*(fdifap-fdifam) + bcfs3x*(fdifbp-fdifbm)

    ELSE IF (ic == nxglbl-1) THEN

        fdifap = functn(OPS_ACC1(1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbp = functn(OPS_ACC1(-1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifcp = functn(OPS_ACC1(-2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifdp = functn(OPS_ACC1(-3,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifep = functn(OPS_ACC1(-4,0,0)) - functn(OPS_ACC1(0,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs2x*fdifap + bcfs2x*fdifbp  &
                                + ccfs2x*fdifcp + dcfs2x*fdifdp  &
                                + ecfs2x*fdifep

    ELSE IF (ic == nxglbl) THEN

        fdifap = functn(OPS_ACC1(-1,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifbp = functn(OPS_ACC1(-2,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifcp = functn(OPS_ACC1(-3,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifdp = functn(OPS_ACC1(-4,0,0)) - functn(OPS_ACC1(0,0,0))
        fdifep = functn(OPS_ACC1(-5,0,0)) - functn(OPS_ACC1(0,0,0))

        fderiv(OPS_ACC2(0,0,0)) = acfs1x*fdifap + bcfs1x*fdifbp  &
                                + ccfs1x*fdifcp + dcfs1x*fdifdp  &
                                + ecfs1x*fdifep

    END IF

    fderiv(OPS_ACC2(0,0,0)) = fderiv(OPS_ACC2(0,0,0))*ovdlx2

END SUBROUTINE


#undef OPS_ACC1
#undef OPS_ACC2


subroutine d2fdx2_kernel_main_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& opsDat3Local, &
& opsDat4Local, &
& opsDat5Local, &
& opsDat6Local, &
& idx, &
& dat1_base, &
& dat2_base, &
& dat3_base, &
& dat4_base, &
& dat5_base, &
& dat6_base, &
& start_indx, &
& end_indx )

  IMPLICIT NONE

  real(kind=8), dimension(*), intent(in)    :: opsDat1Local
  integer(4) :: dat1_base
  real(kind=8), dimension(*), intent(inout) :: opsDat2Local
  integer(4) :: dat2_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat3Local
  integer(4) :: dat3_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat4Local
  integer(4) :: dat4_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat5Local
  integer(4) :: dat5_base
  integer(kind=4), dimension(*), intent(in)    :: opsDat6Local
  integer(4) :: dat6_base
  integer(4), dimension(3), intent(in) :: idx
  integer(4), dimension(3)             :: idx_local
  integer(4), dimension(3), intent(in) :: start_indx, end_indx
  integer(4) :: n_x, n_y, n_z

  DO n_z = 1, end_indx(3)-start_indx(3)+1
    idx_local(3) = idx(3) + n_z - 1
    DO n_y = 1, end_indx(2)-start_indx(2)+1
      idx_local(2) = idx(2) + n_y - 1
      !$OMP SIMD
      DO n_x = 1, end_indx(1)-start_indx(1)+1
        idx_local(1) = idx(1) + n_x - 1

        call d2fdx2_kernel_main( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base+(n_x-1)*1 + (n_y-1)*xdim2*1 + (n_z-1)*ydim2*xdim2*1), &
        & opsDat3Local(dat3_base), &
        & opsDat4Local(dat4_base), &
        & opsDat5Local(dat5_base), &
        & opsDat6Local(dat6_base), &
        & idx_local )

      END DO
    END DO
  END DO

end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine d2fdx2_kernel_main_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7)

  IMPLICIT NONE

  character(kind=c_char,len=*), intent(in) :: userSubroutine
  type(ops_block), intent(in) :: block
  integer(4), intent(in):: dim
  integer(4), dimension(2*dim), intent(in) :: range
  type(ops_arg), intent(in) :: opsArg1
  type(ops_arg), intent(in) :: opsArg2
  type(ops_arg), intent(in) :: opsArg3
  type(ops_arg), intent(in) :: opsArg4
  type(ops_arg), intent(in) :: opsArg5
  type(ops_arg), intent(in) :: opsArg6
  type(ops_arg), intent(in) :: opsArg7

  type(ops_arg), dimension(7) :: opsArgArray
#else
subroutine d2fdx2_kernel_main_host_execute( descPtr )

  USE ISO_C_BINDING
  IMPLICIT NONE

  type(ops_kernel_descriptor), intent(in) :: descPtr
  type(ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, dimension(:) :: range
  character(kind=c_char), pointer, dimension(:) :: userSubroutine
  type(ops_arg), pointer, dimension(:) :: opsArgArray
  type(ops_arg) :: opsArg1
  type(ops_arg) :: opsArg2
  type(ops_arg) :: opsArg3
  type(ops_arg) :: opsArg4
  type(ops_arg) :: opsArg5
  type(ops_arg) :: opsArg6
  type(ops_arg) :: opsArg7
#endif

  real(kind=8), pointer, dimension(:) :: opsDat1Local
  integer(4) :: opsDat1Cardinality
  integer(4), pointer, dimension(:)  :: dat1_size
  integer(4) :: dat1_base

  real(kind=8), pointer, dimension(:) :: opsDat2Local
  integer(4) :: opsDat2Cardinality
  integer(4), pointer, dimension(:)  :: dat2_size
  integer(4) :: dat2_base

  integer(kind=4), pointer, dimension(:) :: opsDat3Local
  integer(4) :: dat3_base

  integer(kind=4), pointer, dimension(:) :: opsDat4Local
  integer(4) :: dat4_base

  integer(kind=4), pointer, dimension(:) :: opsDat5Local
  integer(4) :: dat5_base

  integer(kind=4), pointer, dimension(:) :: opsDat6Local
  integer(4) :: dat6_base

  real(8) :: t1,t2,t3
  real(4) :: transfer_total, transfer
  integer(4), dimension(3) :: idx
  integer(4), dimension(3) :: start_indx, end_indx
  integer(4) :: n


#ifdef OPS_LAZY
!  Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)
  opsArg4 = opsArgArray(4)
  opsArg5 = opsArgArray(5)
  opsArg6 = opsArgArray(6)
  opsArg7 = opsArgArray(7)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
#endif

  call setKernelTime(6,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start_indx, end_indx, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start_indx(n) = range(2*n-1)
    end_indx(n)   = range(2*n)
  END DO
#else
  DO n = 1, 3
    start_indx(n) = range(2*n-1) + 1
    end_indx(n)   = range(2*n) 
  END DO
#endif

#ifdef OPS_MPI
  call getIdx(block,start_indx,idx)
#else
  idx(1) = start_indx(1)
  idx(2) = start_indx(2)
  idx(3) = start_indx(3)
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start_indx,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start_indx,1)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

  call c_f_pointer(getGblPtrFromOpsArg(opsArg3),opsDat3Local, (/opsArg3%dim/))
  dat3_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg4),opsDat4Local, (/opsArg4%dim/))
  dat4_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg5),opsDat5Local, (/opsArg5%dim/))
  dat5_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg6),opsDat6Local, (/opsArg6%dim/))
  dat6_base = 1

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,7)
  call ops_halo_exchanges(opsArgArray,7,range)
  call ops_H_D_exchanges_host(opsArgArray,7)
#endif

  call ops_timers_core(t2)

  call d2fdx2_kernel_main_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & opsDat3Local, &
  & opsDat4Local, &
  & opsDat5Local, &
  & opsDat6Local, &
  & idx, &
  & dat1_base, &
  & dat2_base, &
  & dat3_base, &
  & dat4_base, &
  & dat5_base, &
  & dat6_base, &
  & start_indx, &
  & end_indx )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 7)
  call ops_set_halo_dirtybit3(opsArg2,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start_indx, end_indx, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(6,userSubroutine,t3-t2,t2-t1,transfer_total,0)

end subroutine

#ifdef OPS_LAZY
subroutine d2fdx2_kernel_main_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7)

  IMPLICIT NONE

  character(kind=c_char,len=*), intent(in), target :: userSubroutine
  type(ops_block), intent(in) :: block
  integer(4), intent(in) :: dim
  integer(4), dimension(2*dim), intent(inout), target :: range
  integer(4), dimension(2*dim), target :: range_tmp
  type(ops_arg), intent(in) :: opsArg1
  type(ops_arg), intent(in) :: opsArg2
  type(ops_arg), intent(in) :: opsArg3
  type(ops_arg), intent(in) :: opsArg4
  type(ops_arg), intent(in) :: opsArg5
  type(ops_arg), intent(in) :: opsArg6
  type(ops_arg), intent(in) :: opsArg7

  type(ops_arg), dimension(7), target :: opsArgArray
  integer(4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 7, 6, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(d2fdx2_kernel_main_host_execute))

end subroutine
#endif

END MODULE
