!
! auto-generated by ops_fortran.py
!

MODULE D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQI_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1

INTEGER(KIND=4) xdim2
#define OPS_ACC2(x,y,z) (x+xdim2*(y)+xdim2*ydim2*(z)+1)
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2

contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: d2fdyz_kernel_lh_zdir_corner_eqI


SUBROUTINE d2fdyz_kernel_lh_zdir_corner_eqI(functn, fderiv, idx)
    use data_types
    implicit none

    real(kind=8), dimension(1), intent(in) :: functn
    real(kind=8), dimension(1) :: fderiv

    integer(kind=4), dimension(3), intent(in) :: idx

    real(kind=8) :: fdiffa, fdiffb, fdiffc, fdiffd
    real(kind=8) :: fstora, fstorb, fstorc
    integer(kind=4) :: jc, kc

    jc = idx(2)
    kc = idx(3)

    IF (jc>=3 .and. jc<=5 .and. kc>=3 .and. kc<=5) THEN
        fdiffa = functn(OPS_ACC1(0,1,1)) - functn(OPS_ACC1(0,1,-1))  &
               - functn(OPS_ACC1(0,-1,1)) + functn(OPS_ACC1(0,-1,-1))
        fdiffb = functn(OPS_ACC1(0,2,2)) - functn(OPS_ACC1(0,2,-2))  &
               - functn(OPS_ACC1(0,-2,2)) + functn(OPS_ACC1(0,-2,-2))

        fderiv(OPS_ACC2(0,0,0)) = acf3yz*fdiffa + bcf3yz*fdiffb

        fstora = fdiffa
        fstorb = fdiffb
    END IF

    IF (jc>=4 .and. jc<=5 .and. kc>=4 .and. kc<=5) THEN
        fdiffc = functn(OPS_ACC1(0,3,3)) - functn(OPS_ACC1(0,3,-3))  &
               - functn(OPS_ACC1(0,-3,3)) + functn(OPS_ACC1(0,-3,-3))

        fderiv(OPS_ACC2(0,0,0)) = acf4yz*fstora + bcf4yz*fstorb + ccf4yz*fdiffc

        fstorc = fdiffc
    END IF

    IF (jc==5 .and. kc==5) THEN
        fdiffd = functn(OPS_ACC1(0,4,4)) - functn(OPS_ACC1(0,4,-4))  &
               - functn(OPS_ACC1(0,-4,4)) + functn(OPS_ACC1(0,-4,-4))

        fderiv(OPS_ACC2(0,0,0)) = acf5yz*fstora + bcf5yz*fstorb  &
                                + ccf5yz*fstorc + dcf5yz*fdiffd
    END IF

END SUBROUTINE


#undef OPS_ACC1
#undef OPS_ACC2


subroutine d2fdyz_kernel_lh_zdir_corner_eqI_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& idx, &
& dat1_base, &
& dat2_base, &
& start_indx, &
& end_indx )

  IMPLICIT NONE

  real(kind=8), dimension(*), intent(in)    :: opsDat1Local
  integer(4) :: dat1_base
  real(kind=8), dimension(*), intent(inout) :: opsDat2Local
  integer(4) :: dat2_base
  integer(4), dimension(3), intent(in) :: idx
  integer(4), dimension(3)             :: idx_local
  integer(4), dimension(3), intent(in) :: start_indx, end_indx
  integer(4) :: n_x, n_y, n_z

  DO n_z = 1, end_indx(3)-start_indx(3)+1
    idx_local(3) = idx(3) + n_z - 1
    DO n_y = 1, end_indx(2)-start_indx(2)+1
      idx_local(2) = idx(2) + n_y - 1
      !$OMP SIMD
      DO n_x = 1, end_indx(1)-start_indx(1)+1
        idx_local(1) = idx(1) + n_x - 1

        call d2fdyz_kernel_lh_zdir_corner_eqI( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base+(n_x-1)*1 + (n_y-1)*xdim2*1 + (n_z-1)*ydim2*xdim2*1), &
        & idx_local )

      END DO
    END DO
  END DO

end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine d2fdyz_kernel_lh_zdir_corner_eqI_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3)

  IMPLICIT NONE

  character(kind=c_char,len=*), intent(in) :: userSubroutine
  type(ops_block), intent(in) :: block
  integer(4), intent(in):: dim
  integer(4), dimension(2*dim), intent(in) :: range
  type(ops_arg), intent(in) :: opsArg1
  type(ops_arg), intent(in) :: opsArg2
  type(ops_arg), intent(in) :: opsArg3

  type(ops_arg), dimension(3) :: opsArgArray
#else
subroutine d2fdyz_kernel_lh_zdir_corner_eqI_host_execute( descPtr )

  USE ISO_C_BINDING
  IMPLICIT NONE

  type(ops_kernel_descriptor), intent(in) :: descPtr
  type(ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, dimension(:) :: range
  character(kind=c_char), pointer, dimension(:) :: userSubroutine
  type(ops_arg), pointer, dimension(:) :: opsArgArray
  type(ops_arg) :: opsArg1
  type(ops_arg) :: opsArg2
  type(ops_arg) :: opsArg3
#endif

  real(kind=8), pointer, dimension(:) :: opsDat1Local
  integer(4) :: opsDat1Cardinality
  integer(4), pointer, dimension(:)  :: dat1_size
  integer(4) :: dat1_base

  real(kind=8), pointer, dimension(:) :: opsDat2Local
  integer(4) :: opsDat2Cardinality
  integer(4), pointer, dimension(:)  :: dat2_size
  integer(4) :: dat2_base

  real(8) :: t1,t2,t3
  real(4) :: transfer_total, transfer
  integer(4), dimension(3) :: idx
  integer(4), dimension(3) :: start_indx, end_indx
  integer(4) :: n


#ifdef OPS_LAZY
!  Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
#endif

  call setKernelTime(158,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start_indx, end_indx, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start_indx(n) = range(2*n-1)
    end_indx(n)   = range(2*n)
  END DO
#else
  DO n = 1, 3
    start_indx(n) = range(2*n-1) + 1
    end_indx(n)   = range(2*n) 
  END DO
#endif

#ifdef OPS_MPI
  call getIdx(block,start_indx,idx)
#else
  idx(1) = start_indx(1)
  idx(2) = start_indx(2)
  idx(3) = start_indx(3)
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start_indx,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start_indx,1)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,3)
  call ops_halo_exchanges(opsArgArray,3,range)
  call ops_H_D_exchanges_host(opsArgArray,3)
#endif

  call ops_timers_core(t2)

  call d2fdyz_kernel_lh_zdir_corner_eqI_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & idx, &
  & dat1_base, &
  & dat2_base, &
  & start_indx, &
  & end_indx )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 3)
  call ops_set_halo_dirtybit3(opsArg2,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start_indx, end_indx, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start_indx, end_indx, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(158,userSubroutine,t3-t2,t2-t1,transfer_total,0)

end subroutine

#ifdef OPS_LAZY
subroutine d2fdyz_kernel_lh_zdir_corner_eqI_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3)

  IMPLICIT NONE

  character(kind=c_char,len=*), intent(in), target :: userSubroutine
  type(ops_block), intent(in) :: block
  integer(4), intent(in) :: dim
  integer(4), dimension(2*dim), intent(inout), target :: range
  integer(4), dimension(2*dim), target :: range_tmp
  type(ops_arg), intent(in) :: opsArg1
  type(ops_arg), intent(in) :: opsArg2
  type(ops_arg), intent(in) :: opsArg3

  type(ops_arg), dimension(3), target :: opsArgArray
  integer(4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 3, 158, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(d2fdyz_kernel_lh_zdir_corner_eqI_host_execute))

end subroutine
#endif

END MODULE
