!
! auto-generated by ops_fortran.py
!
MODULE D2FDXY_KERNEL_RH_XDIR_6TH_CENTERED_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1
INTEGER(KIND=4) xdim2
#define OPS_ACC2(x,y,z) (x+xdim2*(y)+xdim2*ydim2*(z)+1)
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2


contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: d2fdxy_kernel_rh_xdir_6th_centered


SUBROUTINE d2fdxy_kernel_rh_xdir_6th_centered(functn, fderiv)
    use data_types
    implicit none

    real(kind=8), dimension(1), intent(in) :: functn
    real(kind=8), dimension(1) :: fderiv

    real(kind=8) :: fdiffa,fdiffb,fdiffc

    fdiffa = functn(OPS_ACC1(1,1,0)) - functn(OPS_ACC1(1,-1,0))  &
           - functn(OPS_ACC1(-1,1,0)) + functn(OPS_ACC1(-1,-1,0))
    fdiffb = functn(OPS_ACC1(2,2,0)) - functn(OPS_ACC1(2,-2,0))  &
           - functn(OPS_ACC1(-2,2,0)) + functn(OPS_ACC1(-2,-2,0))
    fdiffc = functn(OPS_ACC1(3,3,0)) - functn(OPS_ACC1(3,-3,0))  &
           - functn(OPS_ACC1(-3,3,0))  + functn(OPS_ACC1(-3,-3,0))

    fderiv(OPS_ACC2(0,0,0)) = acf4xy*fdiffa + bcf4xy*fdiffb  &
          + ccf4xy*fdiffc

END SUBROUTINE


#undef OPS_ACC1
#undef OPS_ACC2



subroutine d2fdxy_kernel_rh_xdir_6th_centered_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& dat1_base, &
& dat2_base, &
& start, &
& end )
  IMPLICIT NONE
  real(8), INTENT(IN) :: opsDat1Local(*)
  real(8) opsDat2Local(*)
  integer dat1_base
  integer dat2_base
  integer(4) start(3)
  integer(4) end(3)
  integer n_x, n_y, n_z

  DO n_z = 1, end(3)-start(3)+1
    DO n_y = 1, end(2)-start(2)+1
      !$OMP SIMD
      DO n_x = 1, end(1)-start(1)+1
        call d2fdxy_kernel_rh_xdir_6th_centered( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base+(n_x-1)*1 + (n_y-1)*xdim2*1 + (n_z-1)*ydim2*xdim2*1) )
      END DO
    END DO
  END DO
end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine d2fdxy_kernel_rh_xdir_6th_centered_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4)   , DIMENSION(2*dim), INTENT(IN) :: range
  type ( ops_arg )  , INTENT(IN) :: opsArg1
  type ( ops_arg )  , INTENT(IN) :: opsArg2

  type ( ops_arg ) , DIMENSION(2) :: opsArgArray
#else
subroutine d2fdxy_kernel_rh_xdir_6th_centered_host_execute( descPtr )
  use iso_c_binding
  IMPLICIT NONE
  type (ops_kernel_descriptor), intent(in) :: descPtr
  type (ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, DIMENSION(:) :: range
  character(kind=c_char), pointer, DIMENSION(:) :: userSubroutine
  type ( ops_arg ) , pointer, DIMENSION(:) :: opsArgArray
  type ( ops_arg ) :: opsArg1
  type ( ops_arg ) :: opsArg2
#endif

  real(8), POINTER, DIMENSION(:) :: opsDat1Local
  integer(kind=4) :: opsDat1Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat1_size
  integer(kind=4) :: dat1_base

  real(8), POINTER, DIMENSION(:) :: opsDat2Local
  integer(kind=4) :: opsDat2Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat2_size
  integer(kind=4) :: dat2_base

  real(kind=8) t1,t2,t3
  real(kind=4) transfer_total, transfer
  integer start(3)
  integer end(3)
  integer(kind=4) :: n


#ifdef OPS_LAZY
  !Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
#endif

  call setKernelTime(27,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start, end, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start(n) = range(2*n-1)
    end(n) = range(2*n)
  END DO
#else
  DO n = 1, 3
    start(n) = range(2*n-1) + 1
    end(n) = range(2*n) 
  END DO
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start,1)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,2)
  call ops_halo_exchanges(opsArgArray,2,range)
  call ops_H_D_exchanges_host(opsArgArray,2)
#endif

  call ops_timers_core(t2)

  call d2fdxy_kernel_rh_xdir_6th_centered_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & dat1_base, &
  & dat2_base, &
  & start, &
  & end )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 2)
  call ops_set_halo_dirtybit3(opsArg2,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start, end, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(27,userSubroutine,t3-t2,t2-t1,transfer_total,0)
end subroutine

#ifdef OPS_LAZY
subroutine d2fdxy_kernel_rh_xdir_6th_centered_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN), TARGET :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4), DIMENSION(2*dim), INTENT(INOUT), TARGET :: range
  integer(kind=4), DIMENSION(2*dim), TARGET :: range_tmp
  type ( ops_arg ), INTENT(IN) :: opsArg1
  type ( ops_arg ), INTENT(IN) :: opsArg2
  type ( ops_arg ), DIMENSION(2), TARGET :: opsArgArray
  integer(kind=4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 2, 27, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(d2fdxy_kernel_rh_xdir_6th_centered_host_execute))
end subroutine
#endif

END MODULE
