!
! auto-generated by ops_fortran.py
!
MODULE FLAMIN_KERNEL_SET_REACTION_VAR_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1


contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: flamin_kernel_set_reaction_var
SUBROUTINE flamin_kernel_set_reaction_var(crin,deltag,clocat,cthick,idx)
    use data_types
    implicit none

    real(kind=8), dimension(1) :: crin
    real(kind=8), intent(in) :: deltag,clocat,cthick
    integer, dimension(3), intent(in) :: idx

    real(kind=8) :: xcoord,argmnt

    real(kind=8) :: erfunc
    integer, parameter :: ncoeff = 5
    integer, parameter :: ncofm1 = ncoeff-1

    real(kind=8) :: ecoeff(ncoeff)
    real(kind=8) :: pcoeff
    real(kind=8) :: etotal,zvalue,tvalue
    integer :: ix,icoeff

    pcoeff = 0.3275911_8
    ecoeff(1) = 0.254829592_8
    ecoeff(2) =-0.284496736_8
    ecoeff(3) = 1.421413741_8
    ecoeff(4) =-1.453152027_8
    ecoeff(5) = 1.061405429_8

    ix = idx(1)
    xcoord = real(ix-1,kind=8)*deltag
    argmnt = (xcoord-clocat)/cthick

    zvalue = abs(argmnt)
    tvalue = 1.0_8/(1.0_8+pcoeff*zvalue)

    etotal = ecoeff(ncoeff)
    DO icoeff = ncofm1,1,-1
        etotal = ecoeff(icoeff) + etotal*tvalue
    END DO
    etotal = etotal*tvalue

    erfunc = 1.0_8 - etotal*exp(-zvalue*zvalue)
    IF(argmnt < 0.0_8) erfunc = -erfunc

    crin(OPS_ACC1(0,0,0)) = 0.5_8*(1.0_8+erfunc)

END SUBROUTINE


#undef OPS_ACC1



subroutine flamin_kernel_set_reaction_var_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& opsDat3Local, &
& opsDat4Local, &
& idx, &
& dat1_base, &
& dat2_base, &
& dat3_base, &
& dat4_base, &
& start, &
& end )
  IMPLICIT NONE
  real(8) opsDat1Local(*)
  real(8) opsDat2Local(*)
  real(8) opsDat3Local(*)
  real(8) opsDat4Local(*)
  integer(4) idx(3),idx_local(3)
  integer dat1_base
  integer dat2_base
  integer dat3_base
  integer dat4_base
  integer(4) start(3)
  integer(4) end(3)
  integer n_x, n_y, n_z

  DO n_z = 1, end(3)-start(3)+1
    idx_local(3) = idx(3) + n_z - 1
    DO n_y = 1, end(2)-start(2)+1
      idx_local(2) = idx(2) + n_y - 1
      !$OMP SIMD
      DO n_x = 1, end(1)-start(1)+1
        idx_local(1) = idx(1) + n_x - 1
        call flamin_kernel_set_reaction_var( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base), &
        & opsDat3Local(dat3_base), &
        & opsDat4Local(dat4_base), &
        & idx_local )
      END DO
    END DO
  END DO
end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine flamin_kernel_set_reaction_var_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4)   , DIMENSION(2*dim), INTENT(IN) :: range
  type ( ops_arg )  , INTENT(IN) :: opsArg1
  type ( ops_arg )  , INTENT(IN) :: opsArg2
  type ( ops_arg )  , INTENT(IN) :: opsArg3
  type ( ops_arg )  , INTENT(IN) :: opsArg4
  type ( ops_arg )  , INTENT(IN) :: opsArg5

  type ( ops_arg ) , DIMENSION(5) :: opsArgArray
#else
subroutine flamin_kernel_set_reaction_var_host_execute( descPtr )
  use iso_c_binding
  IMPLICIT NONE
  type (ops_kernel_descriptor), intent(in) :: descPtr
  type (ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, DIMENSION(:) :: range
  character(kind=c_char), pointer, DIMENSION(:) :: userSubroutine
  type ( ops_arg ) , pointer, DIMENSION(:) :: opsArgArray
  type ( ops_arg ) :: opsArg1
  type ( ops_arg ) :: opsArg2
  type ( ops_arg ) :: opsArg3
  type ( ops_arg ) :: opsArg4
  type ( ops_arg ) :: opsArg5
#endif

  real(8), POINTER, DIMENSION(:) :: opsDat1Local
  integer(kind=4) :: opsDat1Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat1_size
  integer(kind=4) :: dat1_base

  real(8), POINTER, DIMENSION(:) :: opsDat2Local
  integer(kind=4) :: dat2_base

  real(8), POINTER, DIMENSION(:) :: opsDat3Local
  integer(kind=4) :: dat3_base

  real(8), POINTER, DIMENSION(:) :: opsDat4Local
  integer(kind=4) :: dat4_base

  real(kind=8) t1,t2,t3
  real(kind=4) transfer_total, transfer
  integer start(3)
  integer end(3)
  integer idx(3)
  integer(kind=4) :: n


#ifdef OPS_LAZY
  !Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)
  opsArg4 = opsArgArray(4)
  opsArg5 = opsArgArray(5)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
#endif

  call setKernelTime(511,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start, end, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start(n) = range(2*n-1)
    end(n) = range(2*n)
  END DO
#else
  DO n = 1, 3
    start(n) = range(2*n-1) + 1
    end(n) = range(2*n) 
  END DO
#endif

#ifdef OPS_MPI
  call getIdx(block,start,idx)
#else
  idx(1) = start(1)
  idx(2) = start(2)
  idx(3) = start(3)
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getGblPtrFromOpsArg(opsArg2),opsDat2Local, (/opsArg2%dim/))
  dat2_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg3),opsDat3Local, (/opsArg3%dim/))
  dat3_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg4),opsDat4Local, (/opsArg4%dim/))
  dat4_base = 1

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,5)
  call ops_halo_exchanges(opsArgArray,5,range)
  call ops_H_D_exchanges_host(opsArgArray,5)
#endif

  call ops_timers_core(t2)

  call flamin_kernel_set_reaction_var_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & opsDat3Local, &
  & opsDat4Local, &
  & idx, &
  & dat1_base, &
  & dat2_base, &
  & dat3_base, &
  & dat4_base, &
  & start, &
  & end )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 5)
  call ops_set_halo_dirtybit3(opsArg1,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start, end, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(511,userSubroutine,t3-t2,t2-t1,transfer_total,0)
end subroutine

#ifdef OPS_LAZY
subroutine flamin_kernel_set_reaction_var_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN), TARGET :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4), DIMENSION(2*dim), INTENT(INOUT), TARGET :: range
  integer(kind=4), DIMENSION(2*dim), TARGET :: range_tmp
  type ( ops_arg ), INTENT(IN) :: opsArg1
  type ( ops_arg ), INTENT(IN) :: opsArg2
  type ( ops_arg ), INTENT(IN) :: opsArg3
  type ( ops_arg ), INTENT(IN) :: opsArg4
  type ( ops_arg ), INTENT(IN) :: opsArg5
  type ( ops_arg ), DIMENSION(5), TARGET :: opsArgArray
  integer(kind=4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 5, 511, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(flamin_kernel_set_reaction_var_host_execute))
end subroutine
#endif

END MODULE
