!
! auto-generated by ops_fortran.py
!
MODULE MATH_MD_KERNEL_EQY_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1
INTEGER(KIND=4) xdim2
#define OPS_ACC2(x,y,z) (x+xdim2*(y)+xdim2*ydim2*(z)+1)
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2

INTEGER(KIND=4) multi_d3
INTEGER(KIND=4) xdim3
#define OPS_ACC_MD3(d,x,y,z) ((x)*multi_d3 + (d) + (xdim3*(y)*multi_d3) + (xdim3*ydim3*(z)*multi_d3))
INTEGER(KIND=4) ydim3
INTEGER(KIND=4) zdim3

contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: math_MD_kernel_eqY


SUBROUTINE math_MD_kernel_eqY(difmix,transp,yrhs,viscco,wilko1,wilko2,ovwmol,ncovis,ncovm1,nspec)
    use data_types
    implicit none

    real(kind=8), dimension(1) :: difmix
    real(kind=8), dimension(1), intent(in) :: transp,yrhs

    integer, intent(in) :: ncovis,ncovm1,nspec

    real(kind=8), dimension(nspcmx), intent(in) :: ovwmol
    real(kind=8), dimension(nvcfmx,nspcmx), intent(in) :: viscco
    real(kind=8), dimension(nspcmx,nspcmx), intent(in) :: wilko1,wilko2

    real(kind=8) :: fornow, combo1, combo2
    real(kind=8), dimension(nspcmx) :: ctrans
    integer :: ispec, jspec, icp

    DO ispec = 1, nspcmx
        fornow = viscco(ncovis,ispec)
        DO icp = ncovm1,1,-1
            fornow = fornow*transp(OPS_ACC2(0,0,0)) + viscco(icp,ispec)
        END DO
        ctrans(ispec) = EXP(fornow)
    END DO

    combo1 = 0.0_8
    DO ispec = 1, nspcmx
        combo2 = 0.0_8
        DO jspec = 1, nspec
            fornow = SQRT(ctrans(ispec)/ctrans(jspec))
            fornow = 1.0_8 + fornow*wilko2(jspec,ispec)
            fornow = wilko1(jspec,ispec)*fornow*fornow
            combo2 = combo2 + yrhs(OPS_ACC_MD3(jspec,0,0,0))*ovwmol(jspec)*fornow
        END DO
        fornow = ctrans(ispec)/combo2
        combo1 = combo1 + yrhs(OPS_ACC_MD3(ispec,0,0,0))*ovwmol(ispec)*fornow
    END DO

    difmix(OPS_ACC1(0,0,0)) = combo1

END SUBROUTINE


#undef OPS_ACC1
#undef OPS_ACC2

#undef OPS_ACC_MD3


subroutine math_MD_kernel_eqY_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& opsDat3Local, &
& opsDat4Local, &
& opsDat5Local, &
& opsDat6Local, &
& opsDat7Local, &
& opsDat8Local, &
& opsDat9Local, &
& opsDat10Local, &
& dat1_base, &
& dat2_base, &
& dat3_base, &
& dat4_base, &
& dat5_base, &
& dat6_base, &
& dat7_base, &
& dat8_base, &
& dat9_base, &
& dat10_base, &
& start, &
& end )
  IMPLICIT NONE
  real(8) opsDat1Local(*)
  real(8), INTENT(IN) :: opsDat2Local(*)
  real(8), INTENT(IN) :: opsDat3Local(*)
  real(8) opsDat4Local(*)
  real(8) opsDat5Local(*)
  real(8) opsDat6Local(*)
  real(8) opsDat7Local(*)
  integer opsDat8Local(*)
  integer opsDat9Local(*)
  integer opsDat10Local(*)
  integer dat1_base
  integer dat2_base
  integer dat3_base
  integer dat4_base
  integer dat5_base
  integer dat6_base
  integer dat7_base
  integer dat8_base
  integer dat9_base
  integer dat10_base
  integer(4) start(3)
  integer(4) end(3)
  integer n_x, n_y, n_z

  DO n_z = 1, end(3)-start(3)+1
    DO n_y = 1, end(2)-start(2)+1
      !$OMP SIMD
      DO n_x = 1, end(1)-start(1)+1
        call math_MD_kernel_eqY( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base+(n_x-1)*1 + (n_y-1)*xdim2*1 + (n_z-1)*ydim2*xdim2*1), &
        & opsDat3Local(dat3_base+(n_x-1)*9 + (n_y-1)*xdim3*9 + (n_z-1)*ydim3*xdim3*9), &
        & opsDat4Local(dat4_base), &
        & opsDat5Local(dat5_base), &
        & opsDat6Local(dat6_base), &
        & opsDat7Local(dat7_base), &
        & opsDat8Local(dat8_base), &
        & opsDat9Local(dat9_base), &
        & opsDat10Local(dat10_base) )
      END DO
    END DO
  END DO
end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine math_MD_kernel_eqY_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4)   , DIMENSION(2*dim), INTENT(IN) :: range
  type ( ops_arg )  , INTENT(IN) :: opsArg1
  type ( ops_arg )  , INTENT(IN) :: opsArg2
  type ( ops_arg )  , INTENT(IN) :: opsArg3
  type ( ops_arg )  , INTENT(IN) :: opsArg4
  type ( ops_arg )  , INTENT(IN) :: opsArg5
  type ( ops_arg )  , INTENT(IN) :: opsArg6
  type ( ops_arg )  , INTENT(IN) :: opsArg7
  type ( ops_arg )  , INTENT(IN) :: opsArg8
  type ( ops_arg )  , INTENT(IN) :: opsArg9
  type ( ops_arg )  , INTENT(IN) :: opsArg10

  type ( ops_arg ) , DIMENSION(10) :: opsArgArray
#else
subroutine math_MD_kernel_eqY_host_execute( descPtr )
  use iso_c_binding
  IMPLICIT NONE
  type (ops_kernel_descriptor), intent(in) :: descPtr
  type (ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, DIMENSION(:) :: range
  character(kind=c_char), pointer, DIMENSION(:) :: userSubroutine
  type ( ops_arg ) , pointer, DIMENSION(:) :: opsArgArray
  type ( ops_arg ) :: opsArg1
  type ( ops_arg ) :: opsArg2
  type ( ops_arg ) :: opsArg3
  type ( ops_arg ) :: opsArg4
  type ( ops_arg ) :: opsArg5
  type ( ops_arg ) :: opsArg6
  type ( ops_arg ) :: opsArg7
  type ( ops_arg ) :: opsArg8
  type ( ops_arg ) :: opsArg9
  type ( ops_arg ) :: opsArg10
#endif

  real(8), POINTER, DIMENSION(:) :: opsDat1Local
  integer(kind=4) :: opsDat1Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat1_size
  integer(kind=4) :: dat1_base

  real(8), POINTER, DIMENSION(:) :: opsDat2Local
  integer(kind=4) :: opsDat2Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat2_size
  integer(kind=4) :: dat2_base

  real(8), POINTER, DIMENSION(:) :: opsDat3Local
  integer(kind=4) :: opsDat3Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat3_size
  integer(kind=4) :: dat3_base

  real(8), POINTER, DIMENSION(:) :: opsDat4Local
  integer(kind=4) :: dat4_base

  real(8), POINTER, DIMENSION(:) :: opsDat5Local
  integer(kind=4) :: dat5_base

  real(8), POINTER, DIMENSION(:) :: opsDat6Local
  integer(kind=4) :: dat6_base

  real(8), POINTER, DIMENSION(:) :: opsDat7Local
  integer(kind=4) :: dat7_base

  integer, POINTER, DIMENSION(:) :: opsDat8Local
  integer(kind=4) :: dat8_base

  integer, POINTER, DIMENSION(:) :: opsDat9Local
  integer(kind=4) :: dat9_base

  integer, POINTER, DIMENSION(:) :: opsDat10Local
  integer(kind=4) :: dat10_base

  real(kind=8) t1,t2,t3
  real(kind=4) transfer_total, transfer
  integer start(3)
  integer end(3)
  integer(kind=4) :: n


#ifdef OPS_LAZY
  !Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)
  opsArg4 = opsArgArray(4)
  opsArg5 = opsArgArray(5)
  opsArg6 = opsArgArray(6)
  opsArg7 = opsArgArray(7)
  opsArg8 = opsArgArray(8)
  opsArg9 = opsArgArray(9)
  opsArg10 = opsArgArray(10)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
#endif

  call setKernelTime(277,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start, end, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start(n) = range(2*n-1)
    end(n) = range(2*n)
  END DO
#else
  DO n = 1, 3
    start(n) = range(2*n-1) + 1
    end(n) = range(2*n) 
  END DO
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start,1)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg3),dat3_size,(/dim/))
  xdim3 = dat3_size(1)
  ydim3 = dat3_size(2)
  zdim3 = dat3_size(3)
  opsDat3Cardinality = opsArg3%dim * xdim3 * ydim3 * zdim3
  multi_d3 = getDatDimFromOpsArg(opsArg3) ! dimension of the dat
  dat3_base = getDatBaseFromOpsArg3D(opsArg3,start,multi_d3)
  call c_f_pointer(opsArg3%data,opsDat3Local,(/opsDat3Cardinality/))

  call c_f_pointer(getGblPtrFromOpsArg(opsArg4),opsDat4Local, (/opsArg4%dim/))
  dat4_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg5),opsDat5Local, (/opsArg5%dim/))
  dat5_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg6),opsDat6Local, (/opsArg6%dim/))
  dat6_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg7),opsDat7Local, (/opsArg7%dim/))
  dat7_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg8),opsDat8Local, (/opsArg8%dim/))
  dat8_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg9),opsDat9Local, (/opsArg9%dim/))
  dat9_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg10),opsDat10Local, (/opsArg10%dim/))
  dat10_base = 1

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,10)
  call ops_halo_exchanges(opsArgArray,10,range)
  call ops_H_D_exchanges_host(opsArgArray,10)
#endif

  call ops_timers_core(t2)

  call math_MD_kernel_eqY_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & opsDat3Local, &
  & opsDat4Local, &
  & opsDat5Local, &
  & opsDat6Local, &
  & opsDat7Local, &
  & opsDat8Local, &
  & opsDat9Local, &
  & opsDat10Local, &
  & dat1_base, &
  & dat2_base, &
  & dat3_base, &
  & dat4_base, &
  & dat5_base, &
  & dat6_base, &
  & dat7_base, &
  & dat8_base, &
  & dat9_base, &
  & dat10_base, &
  & start, &
  & end )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 10)
  call ops_set_halo_dirtybit3(opsArg1,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start, end, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg3,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(277,userSubroutine,t3-t2,t2-t1,transfer_total,0)
end subroutine

#ifdef OPS_LAZY
subroutine math_MD_kernel_eqY_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN), TARGET :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4), DIMENSION(2*dim), INTENT(INOUT), TARGET :: range
  integer(kind=4), DIMENSION(2*dim), TARGET :: range_tmp
  type ( ops_arg ), INTENT(IN) :: opsArg1
  type ( ops_arg ), INTENT(IN) :: opsArg2
  type ( ops_arg ), INTENT(IN) :: opsArg3
  type ( ops_arg ), INTENT(IN) :: opsArg4
  type ( ops_arg ), INTENT(IN) :: opsArg5
  type ( ops_arg ), INTENT(IN) :: opsArg6
  type ( ops_arg ), INTENT(IN) :: opsArg7
  type ( ops_arg ), INTENT(IN) :: opsArg8
  type ( ops_arg ), INTENT(IN) :: opsArg9
  type ( ops_arg ), INTENT(IN) :: opsArg10
  type ( ops_arg ), DIMENSION(10), TARGET :: opsArgArray
  integer(kind=4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 10, 277, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(math_MD_kernel_eqY_host_execute))
end subroutine
#endif

END MODULE
