!
! auto-generated by ops_fortran.py
!
MODULE MATH_KERNEL_EQAS_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1
INTEGER(KIND=4) xdim2
#define OPS_ACC2(x,y,z) (x+xdim2*(y)+xdim2*ydim2*(z)+1)
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2
INTEGER(KIND=4) xdim3
#define OPS_ACC3(x,y,z) (x+xdim3*(y)+xdim3*ydim3*(z)+1)
INTEGER(KIND=4) ydim3
INTEGER(KIND=4) zdim3
INTEGER(KIND=4) xdim4
#define OPS_ACC4(x,y,z) (x+xdim4*(y)+xdim4*ydim4*(z)+1)
INTEGER(KIND=4) ydim4
INTEGER(KIND=4) zdim4
INTEGER(KIND=4) xdim5
#define OPS_ACC5(x,y,z) (x+xdim5*(y)+xdim5*ydim5*(z)+1)
INTEGER(KIND=4) ydim5
INTEGER(KIND=4) zdim5


contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: math_kernel_eqAS


SUBROUTINE math_kernel_eqAS(out_arr1,out_arr2,out_arr3,in_arr1,in_arr2,racnst,rncnst,reovrr,talpha,ovtst1,tstar2,ovtst3,cfcst1,cfcst2,encst1,encst2,dtcnst,omalph,clnten)
    use data_types
    implicit none

    real(kind=8), dimension(1) :: out_arr1, out_arr2, out_arr3
    real(kind=8), dimension(1), intent(in) :: in_arr1, in_arr2
    real(kind=8), intent(in) :: racnst,rncnst,reovrr,talpha,ovtst1,tstar2,ovtst3,cfcst1,cfcst2,encst1,encst2,dtcnst,omalph,clnten

    real(kind=8) :: preduc,fornow,trats1,trats2,trats3,ftcent,cfactr,enfact,fbroad

    out_arr3(OPS_ACC3(0,0,0)) = racnst + rncnst*LOG(in_arr1(OPS_ACC4(0,0,0)))  &
                              - reovrr/in_arr1(OPS_ACC4(0,0,0))
    out_arr3(OPS_ACC3(0,0,0)) = EXP(out_arr3(OPS_ACC3(0,0,0)))

    preduc = in_arr2(OPS_ACC5(0,0,0))*out_arr3(OPS_ACC3(0,0,0)) /out_arr1(OPS_ACC1(0,0,0))

    trats1 = in_arr1(OPS_ACC4(0,0,0))*ovtst1
    trats2 = tstar2/in_arr1(OPS_ACC4(0,0,0))
    trats3 = in_arr1(OPS_ACC4(0,0,0))*ovtst3
    ftcent = omalph*EXP(trats3) + talpha*EXP(trats1)  &
           + EXP(trats2)
    ftcent = LOG10(ftcent)

    cfactr = cfcst1 + cfcst2*ftcent
    enfact = encst1 + encst2*ftcent
    fornow = LOG10(preduc) + cfactr
    fornow = fornow/(enfact - dtcnst*fornow)
    fornow = 1.0_8 + fornow*fornow
    fbroad = ftcent/fornow
    fbroad = EXP(fbroad*clnten)

    fornow = fbroad*preduc/(1.0_8+preduc)
    out_arr1(OPS_ACC1(0,0,0)) = out_arr1(OPS_ACC1(0,0,0))*fornow

    out_arr2(OPS_ACC2(0,0,0)) = LOG(out_arr1(OPS_ACC1(0,0,0)))

END SUBROUTINE


#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC5



subroutine math_kernel_eqAS_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& opsDat3Local, &
& opsDat4Local, &
& opsDat5Local, &
& opsDat6Local, &
& opsDat7Local, &
& opsDat8Local, &
& opsDat9Local, &
& opsDat10Local, &
& opsDat11Local, &
& opsDat12Local, &
& opsDat13Local, &
& opsDat14Local, &
& opsDat15Local, &
& opsDat16Local, &
& opsDat17Local, &
& opsDat18Local, &
& opsDat19Local, &
& dat1_base, &
& dat2_base, &
& dat3_base, &
& dat4_base, &
& dat5_base, &
& dat6_base, &
& dat7_base, &
& dat8_base, &
& dat9_base, &
& dat10_base, &
& dat11_base, &
& dat12_base, &
& dat13_base, &
& dat14_base, &
& dat15_base, &
& dat16_base, &
& dat17_base, &
& dat18_base, &
& dat19_base, &
& start, &
& end )
  IMPLICIT NONE
  real(8) opsDat1Local(*)
  real(8) opsDat2Local(*)
  real(8) opsDat3Local(*)
  real(8), INTENT(IN) :: opsDat4Local(*)
  real(8), INTENT(IN) :: opsDat5Local(*)
  real(8) opsDat6Local(*)
  real(8) opsDat7Local(*)
  real(8) opsDat8Local(*)
  real(8) opsDat9Local(*)
  real(8) opsDat10Local(*)
  real(8) opsDat11Local(*)
  real(8) opsDat12Local(*)
  real(8) opsDat13Local(*)
  real(8) opsDat14Local(*)
  real(8) opsDat15Local(*)
  real(8) opsDat16Local(*)
  real(8) opsDat17Local(*)
  real(8) opsDat18Local(*)
  real(8) opsDat19Local(*)
  integer dat1_base
  integer dat2_base
  integer dat3_base
  integer dat4_base
  integer dat5_base
  integer dat6_base
  integer dat7_base
  integer dat8_base
  integer dat9_base
  integer dat10_base
  integer dat11_base
  integer dat12_base
  integer dat13_base
  integer dat14_base
  integer dat15_base
  integer dat16_base
  integer dat17_base
  integer dat18_base
  integer dat19_base
  integer(4) start(3)
  integer(4) end(3)
  integer n_x, n_y, n_z

  DO n_z = 1, end(3)-start(3)+1
    DO n_y = 1, end(2)-start(2)+1
      !$OMP SIMD
      DO n_x = 1, end(1)-start(1)+1
        call math_kernel_eqAS( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base+(n_x-1)*1 + (n_y-1)*xdim2*1 + (n_z-1)*ydim2*xdim2*1), &
        & opsDat3Local(dat3_base+(n_x-1)*1 + (n_y-1)*xdim3*1 + (n_z-1)*ydim3*xdim3*1), &
        & opsDat4Local(dat4_base+(n_x-1)*1 + (n_y-1)*xdim4*1 + (n_z-1)*ydim4*xdim4*1), &
        & opsDat5Local(dat5_base+(n_x-1)*1 + (n_y-1)*xdim5*1 + (n_z-1)*ydim5*xdim5*1), &
        & opsDat6Local(dat6_base), &
        & opsDat7Local(dat7_base), &
        & opsDat8Local(dat8_base), &
        & opsDat9Local(dat9_base), &
        & opsDat10Local(dat10_base), &
        & opsDat11Local(dat11_base), &
        & opsDat12Local(dat12_base), &
        & opsDat13Local(dat13_base), &
        & opsDat14Local(dat14_base), &
        & opsDat15Local(dat15_base), &
        & opsDat16Local(dat16_base), &
        & opsDat17Local(dat17_base), &
        & opsDat18Local(dat18_base), &
        & opsDat19Local(dat19_base) )
      END DO
    END DO
  END DO
end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine math_kernel_eqAS_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10, &
& opsArg11, &
& opsArg12, &
& opsArg13, &
& opsArg14, &
& opsArg15, &
& opsArg16, &
& opsArg17, &
& opsArg18, &
& opsArg19)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4)   , DIMENSION(2*dim), INTENT(IN) :: range
  type ( ops_arg )  , INTENT(IN) :: opsArg1
  type ( ops_arg )  , INTENT(IN) :: opsArg2
  type ( ops_arg )  , INTENT(IN) :: opsArg3
  type ( ops_arg )  , INTENT(IN) :: opsArg4
  type ( ops_arg )  , INTENT(IN) :: opsArg5
  type ( ops_arg )  , INTENT(IN) :: opsArg6
  type ( ops_arg )  , INTENT(IN) :: opsArg7
  type ( ops_arg )  , INTENT(IN) :: opsArg8
  type ( ops_arg )  , INTENT(IN) :: opsArg9
  type ( ops_arg )  , INTENT(IN) :: opsArg10
  type ( ops_arg )  , INTENT(IN) :: opsArg11
  type ( ops_arg )  , INTENT(IN) :: opsArg12
  type ( ops_arg )  , INTENT(IN) :: opsArg13
  type ( ops_arg )  , INTENT(IN) :: opsArg14
  type ( ops_arg )  , INTENT(IN) :: opsArg15
  type ( ops_arg )  , INTENT(IN) :: opsArg16
  type ( ops_arg )  , INTENT(IN) :: opsArg17
  type ( ops_arg )  , INTENT(IN) :: opsArg18
  type ( ops_arg )  , INTENT(IN) :: opsArg19

  type ( ops_arg ) , DIMENSION(19) :: opsArgArray
#else
subroutine math_kernel_eqAS_host_execute( descPtr )
  use iso_c_binding
  IMPLICIT NONE
  type (ops_kernel_descriptor), intent(in) :: descPtr
  type (ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, DIMENSION(:) :: range
  character(kind=c_char), pointer, DIMENSION(:) :: userSubroutine
  type ( ops_arg ) , pointer, DIMENSION(:) :: opsArgArray
  type ( ops_arg ) :: opsArg1
  type ( ops_arg ) :: opsArg2
  type ( ops_arg ) :: opsArg3
  type ( ops_arg ) :: opsArg4
  type ( ops_arg ) :: opsArg5
  type ( ops_arg ) :: opsArg6
  type ( ops_arg ) :: opsArg7
  type ( ops_arg ) :: opsArg8
  type ( ops_arg ) :: opsArg9
  type ( ops_arg ) :: opsArg10
  type ( ops_arg ) :: opsArg11
  type ( ops_arg ) :: opsArg12
  type ( ops_arg ) :: opsArg13
  type ( ops_arg ) :: opsArg14
  type ( ops_arg ) :: opsArg15
  type ( ops_arg ) :: opsArg16
  type ( ops_arg ) :: opsArg17
  type ( ops_arg ) :: opsArg18
  type ( ops_arg ) :: opsArg19
#endif

  real(8), POINTER, DIMENSION(:) :: opsDat1Local
  integer(kind=4) :: opsDat1Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat1_size
  integer(kind=4) :: dat1_base

  real(8), POINTER, DIMENSION(:) :: opsDat2Local
  integer(kind=4) :: opsDat2Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat2_size
  integer(kind=4) :: dat2_base

  real(8), POINTER, DIMENSION(:) :: opsDat3Local
  integer(kind=4) :: opsDat3Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat3_size
  integer(kind=4) :: dat3_base

  real(8), POINTER, DIMENSION(:) :: opsDat4Local
  integer(kind=4) :: opsDat4Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat4_size
  integer(kind=4) :: dat4_base

  real(8), POINTER, DIMENSION(:) :: opsDat5Local
  integer(kind=4) :: opsDat5Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat5_size
  integer(kind=4) :: dat5_base

  real(8), POINTER, DIMENSION(:) :: opsDat6Local
  integer(kind=4) :: dat6_base

  real(8), POINTER, DIMENSION(:) :: opsDat7Local
  integer(kind=4) :: dat7_base

  real(8), POINTER, DIMENSION(:) :: opsDat8Local
  integer(kind=4) :: dat8_base

  real(8), POINTER, DIMENSION(:) :: opsDat9Local
  integer(kind=4) :: dat9_base

  real(8), POINTER, DIMENSION(:) :: opsDat10Local
  integer(kind=4) :: dat10_base

  real(8), POINTER, DIMENSION(:) :: opsDat11Local
  integer(kind=4) :: dat11_base

  real(8), POINTER, DIMENSION(:) :: opsDat12Local
  integer(kind=4) :: dat12_base

  real(8), POINTER, DIMENSION(:) :: opsDat13Local
  integer(kind=4) :: dat13_base

  real(8), POINTER, DIMENSION(:) :: opsDat14Local
  integer(kind=4) :: dat14_base

  real(8), POINTER, DIMENSION(:) :: opsDat15Local
  integer(kind=4) :: dat15_base

  real(8), POINTER, DIMENSION(:) :: opsDat16Local
  integer(kind=4) :: dat16_base

  real(8), POINTER, DIMENSION(:) :: opsDat17Local
  integer(kind=4) :: dat17_base

  real(8), POINTER, DIMENSION(:) :: opsDat18Local
  integer(kind=4) :: dat18_base

  real(8), POINTER, DIMENSION(:) :: opsDat19Local
  integer(kind=4) :: dat19_base

  real(kind=8) t1,t2,t3
  real(kind=4) transfer_total, transfer
  integer start(3)
  integer end(3)
  integer(kind=4) :: n


#ifdef OPS_LAZY
  !Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)
  opsArg4 = opsArgArray(4)
  opsArg5 = opsArgArray(5)
  opsArg6 = opsArgArray(6)
  opsArg7 = opsArgArray(7)
  opsArg8 = opsArgArray(8)
  opsArg9 = opsArgArray(9)
  opsArg10 = opsArgArray(10)
  opsArg11 = opsArgArray(11)
  opsArg12 = opsArgArray(12)
  opsArg13 = opsArgArray(13)
  opsArg14 = opsArgArray(14)
  opsArg15 = opsArgArray(15)
  opsArg16 = opsArgArray(16)
  opsArg17 = opsArgArray(17)
  opsArg18 = opsArgArray(18)
  opsArg19 = opsArgArray(19)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
  opsArgArray(11) = opsArg11
  opsArgArray(12) = opsArg12
  opsArgArray(13) = opsArg13
  opsArgArray(14) = opsArg14
  opsArgArray(15) = opsArg15
  opsArgArray(16) = opsArg16
  opsArgArray(17) = opsArg17
  opsArgArray(18) = opsArg18
  opsArgArray(19) = opsArg19
#endif

  call setKernelTime(522,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start, end, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start(n) = range(2*n-1)
    end(n) = range(2*n)
  END DO
#else
  DO n = 1, 3
    start(n) = range(2*n-1) + 1
    end(n) = range(2*n) 
  END DO
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start,1)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg3),dat3_size,(/dim/))
  xdim3 = dat3_size(1)
  ydim3 = dat3_size(2)
  zdim3 = dat3_size(3)
  opsDat3Cardinality = opsArg3%dim * xdim3 * ydim3 * zdim3
  dat3_base = getDatBaseFromOpsArg3D(opsArg3,start,1)
  call c_f_pointer(opsArg3%data,opsDat3Local,(/opsDat3Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg4),dat4_size,(/dim/))
  xdim4 = dat4_size(1)
  ydim4 = dat4_size(2)
  zdim4 = dat4_size(3)
  opsDat4Cardinality = opsArg4%dim * xdim4 * ydim4 * zdim4
  dat4_base = getDatBaseFromOpsArg3D(opsArg4,start,1)
  call c_f_pointer(opsArg4%data,opsDat4Local,(/opsDat4Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg5),dat5_size,(/dim/))
  xdim5 = dat5_size(1)
  ydim5 = dat5_size(2)
  zdim5 = dat5_size(3)
  opsDat5Cardinality = opsArg5%dim * xdim5 * ydim5 * zdim5
  dat5_base = getDatBaseFromOpsArg3D(opsArg5,start,1)
  call c_f_pointer(opsArg5%data,opsDat5Local,(/opsDat5Cardinality/))

  call c_f_pointer(getGblPtrFromOpsArg(opsArg6),opsDat6Local, (/opsArg6%dim/))
  dat6_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg7),opsDat7Local, (/opsArg7%dim/))
  dat7_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg8),opsDat8Local, (/opsArg8%dim/))
  dat8_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg9),opsDat9Local, (/opsArg9%dim/))
  dat9_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg10),opsDat10Local, (/opsArg10%dim/))
  dat10_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg11),opsDat11Local, (/opsArg11%dim/))
  dat11_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg12),opsDat12Local, (/opsArg12%dim/))
  dat12_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg13),opsDat13Local, (/opsArg13%dim/))
  dat13_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg14),opsDat14Local, (/opsArg14%dim/))
  dat14_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg15),opsDat15Local, (/opsArg15%dim/))
  dat15_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg16),opsDat16Local, (/opsArg16%dim/))
  dat16_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg17),opsDat17Local, (/opsArg17%dim/))
  dat17_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg18),opsDat18Local, (/opsArg18%dim/))
  dat18_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg19),opsDat19Local, (/opsArg19%dim/))
  dat19_base = 1

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,19)
  call ops_halo_exchanges(opsArgArray,19,range)
  call ops_H_D_exchanges_host(opsArgArray,19)
#endif

  call ops_timers_core(t2)

  call math_kernel_eqAS_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & opsDat3Local, &
  & opsDat4Local, &
  & opsDat5Local, &
  & opsDat6Local, &
  & opsDat7Local, &
  & opsDat8Local, &
  & opsDat9Local, &
  & opsDat10Local, &
  & opsDat11Local, &
  & opsDat12Local, &
  & opsDat13Local, &
  & opsDat14Local, &
  & opsDat15Local, &
  & opsDat16Local, &
  & opsDat17Local, &
  & opsDat18Local, &
  & opsDat19Local, &
  & dat1_base, &
  & dat2_base, &
  & dat3_base, &
  & dat4_base, &
  & dat5_base, &
  & dat6_base, &
  & dat7_base, &
  & dat8_base, &
  & dat9_base, &
  & dat10_base, &
  & dat11_base, &
  & dat12_base, &
  & dat13_base, &
  & dat14_base, &
  & dat15_base, &
  & dat16_base, &
  & dat17_base, &
  & dat18_base, &
  & dat19_base, &
  & start, &
  & end )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 19)
  call ops_set_halo_dirtybit3(opsArg1,range)
  call ops_set_halo_dirtybit3(opsArg2,range)
  call ops_set_halo_dirtybit3(opsArg3,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start, end, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg3,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg4,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg5,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(522,userSubroutine,t3-t2,t2-t1,transfer_total,0)
end subroutine

#ifdef OPS_LAZY
subroutine math_kernel_eqAS_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10, &
& opsArg11, &
& opsArg12, &
& opsArg13, &
& opsArg14, &
& opsArg15, &
& opsArg16, &
& opsArg17, &
& opsArg18, &
& opsArg19)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN), TARGET :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4), DIMENSION(2*dim), INTENT(INOUT), TARGET :: range
  integer(kind=4), DIMENSION(2*dim), TARGET :: range_tmp
  type ( ops_arg ), INTENT(IN) :: opsArg1
  type ( ops_arg ), INTENT(IN) :: opsArg2
  type ( ops_arg ), INTENT(IN) :: opsArg3
  type ( ops_arg ), INTENT(IN) :: opsArg4
  type ( ops_arg ), INTENT(IN) :: opsArg5
  type ( ops_arg ), INTENT(IN) :: opsArg6
  type ( ops_arg ), INTENT(IN) :: opsArg7
  type ( ops_arg ), INTENT(IN) :: opsArg8
  type ( ops_arg ), INTENT(IN) :: opsArg9
  type ( ops_arg ), INTENT(IN) :: opsArg10
  type ( ops_arg ), INTENT(IN) :: opsArg11
  type ( ops_arg ), INTENT(IN) :: opsArg12
  type ( ops_arg ), INTENT(IN) :: opsArg13
  type ( ops_arg ), INTENT(IN) :: opsArg14
  type ( ops_arg ), INTENT(IN) :: opsArg15
  type ( ops_arg ), INTENT(IN) :: opsArg16
  type ( ops_arg ), INTENT(IN) :: opsArg17
  type ( ops_arg ), INTENT(IN) :: opsArg18
  type ( ops_arg ), INTENT(IN) :: opsArg19
  type ( ops_arg ), DIMENSION(19), TARGET :: opsArgArray
  integer(kind=4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
  opsArgArray(11) = opsArg11
  opsArgArray(12) = opsArg12
  opsArgArray(13) = opsArg13
  opsArgArray(14) = opsArg14
  opsArgArray(15) = opsArg15
  opsArgArray(16) = opsArg16
  opsArgArray(17) = opsArg17
  opsArgArray(18) = opsArg18
  opsArgArray(19) = opsArg19

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 19, 522, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(math_kernel_eqAS_host_execute))
end subroutine
#endif

END MODULE
