!
! auto-generated by ops_fortran.py
!
MODULE TEMPIN_KERNEL_MAIN_MODULE
USE OPS_FORTRAN_DECLARATIONS
USE OPS_FORTRAN_RT_SUPPORT

USE OPS_CONSTANTS
USE ISO_C_BINDING

INTEGER(KIND=4) xdim1
#define OPS_ACC1(x,y,z) (x+xdim1*(y)+xdim1*ydim1*(z)+1)
INTEGER(KIND=4) ydim1
INTEGER(KIND=4) zdim1
INTEGER(KIND=4) xdim2
#define OPS_ACC2(x,y,z) (x+xdim2*(y)+xdim2*ydim2*(z)+1)
INTEGER(KIND=4) ydim2
INTEGER(KIND=4) zdim2
INTEGER(KIND=4) xdim3
#define OPS_ACC3(x,y,z) (x+xdim3*(y)+xdim3*ydim3*(z)+1)
INTEGER(KIND=4) ydim3
INTEGER(KIND=4) zdim3
INTEGER(KIND=4) xdim4
#define OPS_ACC4(x,y,z) (x+xdim4*(y)+xdim4*ydim4*(z)+1)
INTEGER(KIND=4) ydim4
INTEGER(KIND=4) zdim4
INTEGER(KIND=4) xdim6
#define OPS_ACC6(x,y,z) (x+xdim6*(y)+xdim6*ydim6*(z)+1)
INTEGER(KIND=4) ydim6
INTEGER(KIND=4) zdim6
INTEGER(KIND=4) xdim7
#define OPS_ACC7(x,y,z) (x+xdim7*(y)+xdim7*ydim7*(z)+1)
INTEGER(KIND=4) ydim7
INTEGER(KIND=4) zdim7
INTEGER(KIND=4) xdim8
#define OPS_ACC8(x,y,z) (x+xdim8*(y)+xdim8*ydim8*(z)+1)
INTEGER(KIND=4) ydim8
INTEGER(KIND=4) zdim8
INTEGER(KIND=4) xdim9
#define OPS_ACC9(x,y,z) (x+xdim9*(y)+xdim9*ydim9*(z)+1)
INTEGER(KIND=4) ydim9
INTEGER(KIND=4) zdim9
INTEGER(KIND=4) xdim10
#define OPS_ACC10(x,y,z) (x+xdim10*(y)+xdim10*ydim10*(z)+1)
INTEGER(KIND=4) ydim10
INTEGER(KIND=4) zdim10

INTEGER(KIND=4) multi_d5
INTEGER(KIND=4) xdim5
#define OPS_ACC_MD5(d,x,y,z) ((x)*multi_d5 + (d) + (xdim5*(y)*multi_d5) + (xdim5*ydim5*(z)*multi_d5))
INTEGER(KIND=4) ydim5
INTEGER(KIND=4) zdim5
INTEGER(KIND=4) multi_d11
INTEGER(KIND=4) xdim11
#define OPS_ACC_MD11(d,x,y,z) ((x)*multi_d11 + (d) + (xdim11*(y)*multi_d11) + (xdim11*ydim11*(z)*multi_d11))
INTEGER(KIND=4) ydim11
INTEGER(KIND=4) zdim11

contains

!user function
!DEC$ ATTRIBUTES FORCEINLINE :: tempin_kernel_main
SUBROUTINE tempin_kernel_main(trun,store7,transp,prun,itndex,urhs,vrhs,wrhs,drhs,erhs,yrhs,amascp,amasct,ncpoly,ncpom1,ncenth,tinthi,rgspec,ntint,trin,nspec,iproc,idx)
    use data_types
    implicit none

    real(kind=8), dimension(1), intent(in) :: urhs,vrhs,wrhs,drhs,erhs,yrhs
    real(kind=8), dimension(1) :: trun,store7,transp,prun
    integer, dimension(1) :: itndex

    real(kind=8), intent(in) :: trin
    integer, dimension(3), intent(in) :: idx

    integer, intent(in) :: nspec,iproc

    real(kind=8), dimension(ncofmx,ntinmx,nspcmx), intent(in) :: amascp,amasct
    integer, dimension(ntinmx,nspcmx), intent(in) :: ncpoly,ncpom1,ncenth
    real(kind=8), dimension(ntinmx,nspcmx), intent(in) :: tinthi
    real(kind=8), dimension(nspcmx), intent(in) :: rgspec
    integer, dimension(nspcmx), intent(in) :: ntint


    real(kind=8), parameter :: toltmp=0.00010_8
    real(kind=8), parameter :: tininc=50.0_8
    real(kind=8), parameter :: tlimlo=200.0_8
    real(kind=8), parameter :: tlimhi=3000.0_8


    real(kind=8) :: tcoeff(0:nctmax)
    real(kind=8) :: ukuk
    real(kind=8) :: tempor,tupper,tlower,tresid,tuk2me,cpfory
    integer :: ic,jc,kc,ispec,itint,icp
    integer :: iindex,ipower
    logical :: fnconv

    ic = idx(1)
    jc = idx(2)
    kc = idx(3)

    ukuk = (urhs(OPS_ACC6(0,0,0))*urhs(OPS_ACC6(0,0,0))  &
          +  vrhs(OPS_ACC7(0,0,0))*vrhs(OPS_ACC7(0,0,0))  &
          +  wrhs(OPS_ACC8(0,0,0))*wrhs(OPS_ACC8(0,0,0)))/drhs(OPS_ACC9(0,0,0))

    tuk2me = 0.5_8*ukuk - erhs(OPS_ACC10(0,0,0))



    tlower = tlimlo
    tupper = tlimhi

    fnconv = .true.

    tempor = trin





    tcoeff(0) = tuk2me
    DO icp = 1, nctmax
        tcoeff(icp) = 0.0_8
    END DO

    DO ispec = 1, nspec

        itint = 1
        DO WHILE (tempor > tinthi(itint,ispec) .and. itint < ntint(ispec))
            itint = itint + 1
        END DO

        tcoeff(0) = tcoeff(0) + yrhs(OPS_ACC_MD11(ispec,0,0,0))*  &
                                amascp(ncenth(itint,ispec),itint,ispec)

        tcoeff(1) = tcoeff(1) + yrhs(OPS_ACC_MD11(ispec,0,0,0))*amasct(1,itint,ispec)
        DO icp = 2, ncpoly(itint,ispec)
            tcoeff(icp) = tcoeff(icp)  &
                        + yrhs(OPS_ACC_MD11(ispec,0,0,0))*amasct(icp,itint,ispec)
        END DO

    END DO



    tresid = tcoeff(nctmax)
    DO icp = nctmm1,1,-1
        tresid = tcoeff(icp) + tresid*tempor
    END DO
    tresid = tcoeff(0) + tresid*tempor


    IF(ABS(tresid) < toltmp) THEN

        fnconv = .false.

    ELSE IF(tresid < 0.0_8)THEN

        2000          CONTINUE

        tlower = tempor
        tempor = tempor + tininc


        tcoeff(0) = tuk2me
        DO icp = 1, nctmax
            tcoeff(icp) = 0.0_8
        END DO

        DO ispec = 1, nspec

            itint = 1
            DO WHILE (tempor > tinthi(itint,ispec) .and. itint < ntint(ispec))
                itint = itint + 1
            END DO

            tcoeff(0) = tcoeff(0) + yrhs(OPS_ACC_MD11(ispec,0,0,0))*  &
                                    amascp(ncenth(itint,ispec),itint,ispec)
            tcoeff(1) = tcoeff(1) + yrhs(OPS_ACC_MD11(ispec,0,0,0))*amasct(1,itint,ispec)

            DO icp = 2, ncpoly(itint,ispec)
                tcoeff(icp) = tcoeff(icp)  &
                            + yrhs(OPS_ACC_MD11(ispec,0,0,0))*amasct(icp,itint,ispec)
            END DO

        END DO



        tresid = tcoeff(nctmax)
        DO icp = nctmm1,1,-1
            tresid = tcoeff(icp) + tresid*tempor
        END DO
        tresid = tcoeff(0) + tresid*tempor


        IF(ABS(tresid) < toltmp) THEN

            fnconv = .false.

        ELSE IF(tresid < 0.0_8) THEN

            IF(tempor < tlimhi) THEN
                GO TO 2000
            ELSE
                print *,'Fatal: TEMPIN: T upper bracket failed to converge'
                print *,'processor:',iproc
                print *,'at point:',ic,jc,kc
                print *,'with values:',tempor,tresid
                print *,drhs(OPS_ACC9(0,0,0))
                print *,urhs(OPS_ACC6(0,0,0))
                print *,vrhs(OPS_ACC7(0,0,0))
                print *,wrhs(OPS_ACC8(0,0,0))
                print *,erhs(OPS_ACC10(0,0,0))
                DO ispec = 1, nspec
                    print *,yrhs(OPS_ACC_MD11(ispec,0,0,0))
                END DO
                STOP
            END IF

        ELSE IF(tresid > 0.0_8) THEN

            tupper = tempor

        END IF


        ELSE IF(tresid > 0.0_8)THEN

            3000          CONTINUE

            tupper = tempor
            tempor = tempor - tininc

            tcoeff(0) = tuk2me
            DO icp = 1, nctmax
                tcoeff(icp) = 0.0_8
            END DO

            DO ispec = 1, nspec

                itint = 1
                DO WHILE (tempor > tinthi(itint,ispec) .and. itint < ntint(ispec))
                    itint = itint + 1
                END DO

                tcoeff(0) = tcoeff(0) + yrhs(OPS_ACC_MD11(ispec,0,0,0))*  &
                                        amascp(ncenth(itint,ispec),itint,ispec)
                tcoeff(1) = tcoeff(1) + yrhs(OPS_ACC_MD11(ispec,0,0,0))*amasct(1,itint,ispec)
                DO icp = 2, ncpoly(itint,ispec)
                    tcoeff(icp) = tcoeff(icp)  &
                                + yrhs(OPS_ACC_MD11(ispec,0,0,0))*amasct(icp,itint,ispec)
                END DO

            END DO


            tresid = tcoeff(nctmax)
            DO icp = nctmm1,1,-1
                tresid = tcoeff(icp) + tresid*tempor
            END DO
            tresid = tcoeff(0) + tresid*tempor

            IF(ABS(tresid) < toltmp) THEN

                fnconv = .false.

            ELSE IF(tresid > 0.0_8) THEN

                IF(tempor > tlimlo) THEN
                    GO TO 3000
                ELSE
                    print *,'Fatal: TEMPIN: T lower bracket failed to converge'
                    print *,'processor:',iproc
                    print *,'at point:',ic,jc,kc
                    print *,'with values:',tempor,tresid
                    print *,drhs(OPS_ACC9(0,0,0))
                    print *,urhs(OPS_ACC6(0,0,0))
                    print *,vrhs(OPS_ACC7(0,0,0))
                    print *,wrhs(OPS_ACC8(0,0,0))
                    print *,erhs(OPS_ACC10(0,0,0))
                    DO ispec = 1, nspec
                        print *,yrhs(OPS_ACC_MD11(ispec,0,0,0))
                    END DO
                    STOP
                END IF

            ELSE IF(tresid < 0.0_8) THEN

                tlower = tempor

        END IF


    END IF




    IF(fnconv) THEN

        4000          CONTINUE

        tempor = 0.5_8*(tlower+tupper)


        tcoeff(0) = tuk2me
        DO icp = 1, nctmax
            tcoeff(icp) = 0.0_8
        END DO

        DO ispec = 1, nspec

            itint = 1
            DO WHILE (tempor > tinthi(itint,ispec) .and. itint < ntint(ispec))
                itint = itint + 1
            END DO

            tcoeff(0) = tcoeff(0) + yrhs(OPS_ACC_MD11(ispec,0,0,0))*  &
                                    amascp(ncenth(itint,ispec),itint,ispec)
            tcoeff(1) = tcoeff(1) + yrhs(OPS_ACC_MD11(ispec,0,0,0))*amasct(1,itint,ispec)

            DO icp = 2, ncpoly(itint,ispec)
                tcoeff(icp) = tcoeff(icp)  &
                            + yrhs(OPS_ACC_MD11(ispec,0,0,0))*amasct(icp,itint,ispec)
            END DO

        END DO



        tresid = tcoeff(nctmax)
        DO icp = nctmm1,1,-1
            tresid = tcoeff(icp) + tresid*tempor
        END DO
        tresid = tcoeff(0) + tresid*tempor


        IF(ABS(tresid) < toltmp)THEN

            trun(OPS_ACC1(0,0,0)) = tempor

        ELSE IF(tresid < 0.0_8) THEN
            tlower = tempor
            GO TO 4000

        ELSE IF(tresid > 0.0_8) THEN
            tupper = tempor
            GO TO 4000
        END IF


        END IF



    trun(OPS_ACC1(0,0,0)) = tempor



    DO iindex = 1,nintmx
        itndex(OPS_ACC_MD5(iindex,0,0,0)) = 0
    END DO

    store7(OPS_ACC2(0,0,0)) = 0.0_8
    transp(OPS_ACC3(0,0,0)) = 0.0_8

    DO ispec = 1, nspec

        itint = 1
        DO WHILE (trun(OPS_ACC1(0,0,0)) > tinthi(itint,ispec) .and. itint < ntint(ispec))
            itint = itint + 1
        END DO

        iindex = 1 + (ispec-1)/nspimx
        ipower = ispec - (iindex-1)*nspimx - 1
        itndex(OPS_ACC_MD5(iindex,0,0,0)) = itndex(OPS_ACC_MD5(iindex,0,0,0))  &
                                + (itint-1)*ntbase**ipower


        cpfory = amascp(ncpoly(itint,ispec),itint,ispec)
        DO icp = ncpom1(itint,ispec),1,-1
            cpfory = cpfory*trun(OPS_ACC1(0,0,0)) + amascp(icp,itint,ispec)
        END DO

        transp(OPS_ACC3(0,0,0)) = transp(OPS_ACC3(0,0,0)) + yrhs(OPS_ACC_MD11(ispec,0,0,0))*cpfory


        store7(OPS_ACC2(0,0,0)) = store7(OPS_ACC2(0,0,0))  &
                         + yrhs(OPS_ACC_MD11(ispec,0,0,0))*rgspec(ispec)


    END DO

    transp(OPS_ACC3(0,0,0)) = transp(OPS_ACC3(0,0,0))/drhs(OPS_ACC9(0,0,0))


    prun(OPS_ACC4(0,0,0)) = trun(OPS_ACC1(0,0,0))*store7(OPS_ACC2(0,0,0))


END SUBROUTINE


#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC6
#undef OPS_ACC7
#undef OPS_ACC8
#undef OPS_ACC9
#undef OPS_ACC10

#undef OPS_ACC_MD5
#undef OPS_ACC_MD11


subroutine tempin_kernel_main_wrap( &
& opsDat1Local, &
& opsDat2Local, &
& opsDat3Local, &
& opsDat4Local, &
& opsDat5Local, &
& opsDat6Local, &
& opsDat7Local, &
& opsDat8Local, &
& opsDat9Local, &
& opsDat10Local, &
& opsDat11Local, &
& opsDat12Local, &
& opsDat13Local, &
& opsDat14Local, &
& opsDat15Local, &
& opsDat16Local, &
& opsDat17Local, &
& opsDat18Local, &
& opsDat19Local, &
& opsDat20Local, &
& opsDat21Local, &
& opsDat22Local, &
& idx, &
& dat1_base, &
& dat2_base, &
& dat3_base, &
& dat4_base, &
& dat5_base, &
& dat6_base, &
& dat7_base, &
& dat8_base, &
& dat9_base, &
& dat10_base, &
& dat11_base, &
& dat12_base, &
& dat13_base, &
& dat14_base, &
& dat15_base, &
& dat16_base, &
& dat17_base, &
& dat18_base, &
& dat19_base, &
& dat20_base, &
& dat21_base, &
& dat22_base, &
& start, &
& end )
  IMPLICIT NONE
  real(8) opsDat1Local(*)
  real(8) opsDat2Local(*)
  real(8) opsDat3Local(*)
  real(8) opsDat4Local(*)
  integer opsDat5Local(*)
  real(8), INTENT(IN) :: opsDat6Local(*)
  real(8), INTENT(IN) :: opsDat7Local(*)
  real(8), INTENT(IN) :: opsDat8Local(*)
  real(8), INTENT(IN) :: opsDat9Local(*)
  real(8), INTENT(IN) :: opsDat10Local(*)
  real(8), INTENT(IN) :: opsDat11Local(*)
  real(8) opsDat12Local(*)
  real(8) opsDat13Local(*)
  integer opsDat14Local(*)
  integer opsDat15Local(*)
  integer opsDat16Local(*)
  real(8) opsDat17Local(*)
  real(8) opsDat18Local(*)
  integer opsDat19Local(*)
  real(8) opsDat20Local(*)
  integer opsDat21Local(*)
  integer opsDat22Local(*)
  integer(4) idx(3),idx_local(3)
  integer dat1_base
  integer dat2_base
  integer dat3_base
  integer dat4_base
  integer dat5_base
  integer dat6_base
  integer dat7_base
  integer dat8_base
  integer dat9_base
  integer dat10_base
  integer dat11_base
  integer dat12_base
  integer dat13_base
  integer dat14_base
  integer dat15_base
  integer dat16_base
  integer dat17_base
  integer dat18_base
  integer dat19_base
  integer dat20_base
  integer dat21_base
  integer dat22_base
  integer(4) start(3)
  integer(4) end(3)
  integer n_x, n_y, n_z

  DO n_z = 1, end(3)-start(3)+1
    idx_local(3) = idx(3) + n_z - 1
    DO n_y = 1, end(2)-start(2)+1
      idx_local(2) = idx(2) + n_y - 1
      !$OMP SIMD
      DO n_x = 1, end(1)-start(1)+1
        idx_local(1) = idx(1) + n_x - 1
        call tempin_kernel_main( &
        & opsDat1Local(dat1_base+(n_x-1)*1 + (n_y-1)*xdim1*1 + (n_z-1)*ydim1*xdim1*1), &
        & opsDat2Local(dat2_base+(n_x-1)*1 + (n_y-1)*xdim2*1 + (n_z-1)*ydim2*xdim2*1), &
        & opsDat3Local(dat3_base+(n_x-1)*1 + (n_y-1)*xdim3*1 + (n_z-1)*ydim3*xdim3*1), &
        & opsDat4Local(dat4_base+(n_x-1)*1 + (n_y-1)*xdim4*1 + (n_z-1)*ydim4*xdim4*1), &
        & opsDat5Local(dat5_base+(n_x-1)*2 + (n_y-1)*xdim5*2 + (n_z-1)*ydim5*xdim5*2), &
        & opsDat6Local(dat6_base+(n_x-1)*1 + (n_y-1)*xdim6*1 + (n_z-1)*ydim6*xdim6*1), &
        & opsDat7Local(dat7_base+(n_x-1)*1 + (n_y-1)*xdim7*1 + (n_z-1)*ydim7*xdim7*1), &
        & opsDat8Local(dat8_base+(n_x-1)*1 + (n_y-1)*xdim8*1 + (n_z-1)*ydim8*xdim8*1), &
        & opsDat9Local(dat9_base+(n_x-1)*1 + (n_y-1)*xdim9*1 + (n_z-1)*ydim9*xdim9*1), &
        & opsDat10Local(dat10_base+(n_x-1)*1 + (n_y-1)*xdim10*1 + (n_z-1)*ydim10*xdim10*1), &
        & opsDat11Local(dat11_base+(n_x-1)*9 + (n_y-1)*xdim11*9 + (n_z-1)*ydim11*xdim11*9), &
        & opsDat12Local(dat12_base), &
        & opsDat13Local(dat13_base), &
        & opsDat14Local(dat14_base), &
        & opsDat15Local(dat15_base), &
        & opsDat16Local(dat16_base), &
        & opsDat17Local(dat17_base), &
        & opsDat18Local(dat18_base), &
        & opsDat19Local(dat19_base), &
        & opsDat20Local(dat20_base), &
        & opsDat21Local(dat21_base), &
        & opsDat22Local(dat22_base), &
        & idx_local )
      END DO
    END DO
  END DO
end subroutine

!host subroutine
#ifndef OPS_LAZY
subroutine tempin_kernel_main_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10, &
& opsArg11, &
& opsArg12, &
& opsArg13, &
& opsArg14, &
& opsArg15, &
& opsArg16, &
& opsArg17, &
& opsArg18, &
& opsArg19, &
& opsArg20, &
& opsArg21, &
& opsArg22, &
& opsArg23)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4)   , DIMENSION(2*dim), INTENT(IN) :: range
  type ( ops_arg )  , INTENT(IN) :: opsArg1
  type ( ops_arg )  , INTENT(IN) :: opsArg2
  type ( ops_arg )  , INTENT(IN) :: opsArg3
  type ( ops_arg )  , INTENT(IN) :: opsArg4
  type ( ops_arg )  , INTENT(IN) :: opsArg5
  type ( ops_arg )  , INTENT(IN) :: opsArg6
  type ( ops_arg )  , INTENT(IN) :: opsArg7
  type ( ops_arg )  , INTENT(IN) :: opsArg8
  type ( ops_arg )  , INTENT(IN) :: opsArg9
  type ( ops_arg )  , INTENT(IN) :: opsArg10
  type ( ops_arg )  , INTENT(IN) :: opsArg11
  type ( ops_arg )  , INTENT(IN) :: opsArg12
  type ( ops_arg )  , INTENT(IN) :: opsArg13
  type ( ops_arg )  , INTENT(IN) :: opsArg14
  type ( ops_arg )  , INTENT(IN) :: opsArg15
  type ( ops_arg )  , INTENT(IN) :: opsArg16
  type ( ops_arg )  , INTENT(IN) :: opsArg17
  type ( ops_arg )  , INTENT(IN) :: opsArg18
  type ( ops_arg )  , INTENT(IN) :: opsArg19
  type ( ops_arg )  , INTENT(IN) :: opsArg20
  type ( ops_arg )  , INTENT(IN) :: opsArg21
  type ( ops_arg )  , INTENT(IN) :: opsArg22
  type ( ops_arg )  , INTENT(IN) :: opsArg23

  type ( ops_arg ) , DIMENSION(23) :: opsArgArray
#else
subroutine tempin_kernel_main_host_execute( descPtr )
  use iso_c_binding
  IMPLICIT NONE
  type (ops_kernel_descriptor), intent(in) :: descPtr
  type (ops_block) :: block
  integer(kind=c_int) :: dim
  integer(kind=c_int), pointer, DIMENSION(:) :: range
  character(kind=c_char), pointer, DIMENSION(:) :: userSubroutine
  type ( ops_arg ) , pointer, DIMENSION(:) :: opsArgArray
  type ( ops_arg ) :: opsArg1
  type ( ops_arg ) :: opsArg2
  type ( ops_arg ) :: opsArg3
  type ( ops_arg ) :: opsArg4
  type ( ops_arg ) :: opsArg5
  type ( ops_arg ) :: opsArg6
  type ( ops_arg ) :: opsArg7
  type ( ops_arg ) :: opsArg8
  type ( ops_arg ) :: opsArg9
  type ( ops_arg ) :: opsArg10
  type ( ops_arg ) :: opsArg11
  type ( ops_arg ) :: opsArg12
  type ( ops_arg ) :: opsArg13
  type ( ops_arg ) :: opsArg14
  type ( ops_arg ) :: opsArg15
  type ( ops_arg ) :: opsArg16
  type ( ops_arg ) :: opsArg17
  type ( ops_arg ) :: opsArg18
  type ( ops_arg ) :: opsArg19
  type ( ops_arg ) :: opsArg20
  type ( ops_arg ) :: opsArg21
  type ( ops_arg ) :: opsArg22
  type ( ops_arg ) :: opsArg23
#endif

  real(8), POINTER, DIMENSION(:) :: opsDat1Local
  integer(kind=4) :: opsDat1Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat1_size
  integer(kind=4) :: dat1_base

  real(8), POINTER, DIMENSION(:) :: opsDat2Local
  integer(kind=4) :: opsDat2Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat2_size
  integer(kind=4) :: dat2_base

  real(8), POINTER, DIMENSION(:) :: opsDat3Local
  integer(kind=4) :: opsDat3Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat3_size
  integer(kind=4) :: dat3_base

  real(8), POINTER, DIMENSION(:) :: opsDat4Local
  integer(kind=4) :: opsDat4Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat4_size
  integer(kind=4) :: dat4_base

  integer, POINTER, DIMENSION(:) :: opsDat5Local
  integer(kind=4) :: opsDat5Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat5_size
  integer(kind=4) :: dat5_base

  real(8), POINTER, DIMENSION(:) :: opsDat6Local
  integer(kind=4) :: opsDat6Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat6_size
  integer(kind=4) :: dat6_base

  real(8), POINTER, DIMENSION(:) :: opsDat7Local
  integer(kind=4) :: opsDat7Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat7_size
  integer(kind=4) :: dat7_base

  real(8), POINTER, DIMENSION(:) :: opsDat8Local
  integer(kind=4) :: opsDat8Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat8_size
  integer(kind=4) :: dat8_base

  real(8), POINTER, DIMENSION(:) :: opsDat9Local
  integer(kind=4) :: opsDat9Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat9_size
  integer(kind=4) :: dat9_base

  real(8), POINTER, DIMENSION(:) :: opsDat10Local
  integer(kind=4) :: opsDat10Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat10_size
  integer(kind=4) :: dat10_base

  real(8), POINTER, DIMENSION(:) :: opsDat11Local
  integer(kind=4) :: opsDat11Cardinality
  integer(kind=4) , POINTER, DIMENSION(:)  :: dat11_size
  integer(kind=4) :: dat11_base

  real(8), POINTER, DIMENSION(:) :: opsDat12Local
  integer(kind=4) :: dat12_base

  real(8), POINTER, DIMENSION(:) :: opsDat13Local
  integer(kind=4) :: dat13_base

  integer, POINTER, DIMENSION(:) :: opsDat14Local
  integer(kind=4) :: dat14_base

  integer, POINTER, DIMENSION(:) :: opsDat15Local
  integer(kind=4) :: dat15_base

  integer, POINTER, DIMENSION(:) :: opsDat16Local
  integer(kind=4) :: dat16_base

  real(8), POINTER, DIMENSION(:) :: opsDat17Local
  integer(kind=4) :: dat17_base

  real(8), POINTER, DIMENSION(:) :: opsDat18Local
  integer(kind=4) :: dat18_base

  integer, POINTER, DIMENSION(:) :: opsDat19Local
  integer(kind=4) :: dat19_base

  real(8), POINTER, DIMENSION(:) :: opsDat20Local
  integer(kind=4) :: dat20_base

  integer, POINTER, DIMENSION(:) :: opsDat21Local
  integer(kind=4) :: dat21_base

  integer, POINTER, DIMENSION(:) :: opsDat22Local
  integer(kind=4) :: dat22_base

  real(kind=8) t1,t2,t3
  real(kind=4) transfer_total, transfer
  integer start(3)
  integer end(3)
  integer idx(3)
  integer(kind=4) :: n


#ifdef OPS_LAZY
  !Set from kernel descriptor
  dim = descPtr%dim
  call c_f_pointer(descPtr%range, range, (/2*dim/))
  call c_f_pointer(descPtr%name, userSubroutine, (/descPtr%name_len/))
  block%blockCptr = descPtr%block
  call c_f_pointer(block%blockCptr, block%blockPtr)
  call c_f_pointer(descPtr%args, opsArgArray, (/descPtr%nargs/))
  opsArg1 = opsArgArray(1)
  opsArg2 = opsArgArray(2)
  opsArg3 = opsArgArray(3)
  opsArg4 = opsArgArray(4)
  opsArg5 = opsArgArray(5)
  opsArg6 = opsArgArray(6)
  opsArg7 = opsArgArray(7)
  opsArg8 = opsArgArray(8)
  opsArg9 = opsArgArray(9)
  opsArg10 = opsArgArray(10)
  opsArg11 = opsArgArray(11)
  opsArg12 = opsArgArray(12)
  opsArg13 = opsArgArray(13)
  opsArg14 = opsArgArray(14)
  opsArg15 = opsArgArray(15)
  opsArg16 = opsArgArray(16)
  opsArg17 = opsArgArray(17)
  opsArg18 = opsArgArray(18)
  opsArg19 = opsArgArray(19)
  opsArg20 = opsArgArray(20)
  opsArg21 = opsArgArray(21)
  opsArg22 = opsArgArray(22)
  opsArg23 = opsArgArray(23)

#else
  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
  opsArgArray(11) = opsArg11
  opsArgArray(12) = opsArg12
  opsArgArray(13) = opsArg13
  opsArgArray(14) = opsArg14
  opsArgArray(15) = opsArg15
  opsArgArray(16) = opsArg16
  opsArgArray(17) = opsArg17
  opsArgArray(18) = opsArg18
  opsArgArray(19) = opsArg19
  opsArgArray(20) = opsArg20
  opsArgArray(21) = opsArg21
  opsArgArray(22) = opsArg22
  opsArgArray(23) = opsArg23
#endif

  call setKernelTime(541,userSubroutine,0.0_8,0.0_8,0.0_4,1)
  call ops_timers_core(t1)

#if defined(OPS_MPI) && !defined(OPS_LAZY)
  IF (getRange(block, start, end, range) < 0) THEN
    return
  ENDIF
#elif !defined(OPS_MPI)  && !defined(OPS_LAZY)
  DO n = 1, 3
    start(n) = range(2*n-1)
    end(n) = range(2*n)
  END DO
#else
  DO n = 1, 3
    start(n) = range(2*n-1) + 1
    end(n) = range(2*n) 
  END DO
#endif

#ifdef OPS_MPI
  call getIdx(block,start,idx)
#else
  idx(1) = start(1)
  idx(2) = start(2)
  idx(3) = start(3)
#endif

  call c_f_pointer(getDatSizeFromOpsArg(opsArg1),dat1_size,(/dim/))
  xdim1 = dat1_size(1)
  ydim1 = dat1_size(2)
  zdim1 = dat1_size(3)
  opsDat1Cardinality = opsArg1%dim * xdim1 * ydim1 * zdim1
  dat1_base = getDatBaseFromOpsArg3D(opsArg1,start,1)
  call c_f_pointer(opsArg1%data,opsDat1Local,(/opsDat1Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg2),dat2_size,(/dim/))
  xdim2 = dat2_size(1)
  ydim2 = dat2_size(2)
  zdim2 = dat2_size(3)
  opsDat2Cardinality = opsArg2%dim * xdim2 * ydim2 * zdim2
  dat2_base = getDatBaseFromOpsArg3D(opsArg2,start,1)
  call c_f_pointer(opsArg2%data,opsDat2Local,(/opsDat2Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg3),dat3_size,(/dim/))
  xdim3 = dat3_size(1)
  ydim3 = dat3_size(2)
  zdim3 = dat3_size(3)
  opsDat3Cardinality = opsArg3%dim * xdim3 * ydim3 * zdim3
  dat3_base = getDatBaseFromOpsArg3D(opsArg3,start,1)
  call c_f_pointer(opsArg3%data,opsDat3Local,(/opsDat3Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg4),dat4_size,(/dim/))
  xdim4 = dat4_size(1)
  ydim4 = dat4_size(2)
  zdim4 = dat4_size(3)
  opsDat4Cardinality = opsArg4%dim * xdim4 * ydim4 * zdim4
  dat4_base = getDatBaseFromOpsArg3D(opsArg4,start,1)
  call c_f_pointer(opsArg4%data,opsDat4Local,(/opsDat4Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg5),dat5_size,(/dim/))
  xdim5 = dat5_size(1)
  ydim5 = dat5_size(2)
  zdim5 = dat5_size(3)
  opsDat5Cardinality = opsArg5%dim * xdim5 * ydim5 * zdim5
  multi_d5 = getDatDimFromOpsArg(opsArg5) ! dimension of the dat
  dat5_base = getDatBaseFromOpsArg3D(opsArg5,start,multi_d5)
  call c_f_pointer(opsArg5%data,opsDat5Local,(/opsDat5Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg6),dat6_size,(/dim/))
  xdim6 = dat6_size(1)
  ydim6 = dat6_size(2)
  zdim6 = dat6_size(3)
  opsDat6Cardinality = opsArg6%dim * xdim6 * ydim6 * zdim6
  dat6_base = getDatBaseFromOpsArg3D(opsArg6,start,1)
  call c_f_pointer(opsArg6%data,opsDat6Local,(/opsDat6Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg7),dat7_size,(/dim/))
  xdim7 = dat7_size(1)
  ydim7 = dat7_size(2)
  zdim7 = dat7_size(3)
  opsDat7Cardinality = opsArg7%dim * xdim7 * ydim7 * zdim7
  dat7_base = getDatBaseFromOpsArg3D(opsArg7,start,1)
  call c_f_pointer(opsArg7%data,opsDat7Local,(/opsDat7Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg8),dat8_size,(/dim/))
  xdim8 = dat8_size(1)
  ydim8 = dat8_size(2)
  zdim8 = dat8_size(3)
  opsDat8Cardinality = opsArg8%dim * xdim8 * ydim8 * zdim8
  dat8_base = getDatBaseFromOpsArg3D(opsArg8,start,1)
  call c_f_pointer(opsArg8%data,opsDat8Local,(/opsDat8Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg9),dat9_size,(/dim/))
  xdim9 = dat9_size(1)
  ydim9 = dat9_size(2)
  zdim9 = dat9_size(3)
  opsDat9Cardinality = opsArg9%dim * xdim9 * ydim9 * zdim9
  dat9_base = getDatBaseFromOpsArg3D(opsArg9,start,1)
  call c_f_pointer(opsArg9%data,opsDat9Local,(/opsDat9Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg10),dat10_size,(/dim/))
  xdim10 = dat10_size(1)
  ydim10 = dat10_size(2)
  zdim10 = dat10_size(3)
  opsDat10Cardinality = opsArg10%dim * xdim10 * ydim10 * zdim10
  dat10_base = getDatBaseFromOpsArg3D(opsArg10,start,1)
  call c_f_pointer(opsArg10%data,opsDat10Local,(/opsDat10Cardinality/))

  call c_f_pointer(getDatSizeFromOpsArg(opsArg11),dat11_size,(/dim/))
  xdim11 = dat11_size(1)
  ydim11 = dat11_size(2)
  zdim11 = dat11_size(3)
  opsDat11Cardinality = opsArg11%dim * xdim11 * ydim11 * zdim11
  multi_d11 = getDatDimFromOpsArg(opsArg11) ! dimension of the dat
  dat11_base = getDatBaseFromOpsArg3D(opsArg11,start,multi_d11)
  call c_f_pointer(opsArg11%data,opsDat11Local,(/opsDat11Cardinality/))

  call c_f_pointer(getGblPtrFromOpsArg(opsArg12),opsDat12Local, (/opsArg12%dim/))
  dat12_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg13),opsDat13Local, (/opsArg13%dim/))
  dat13_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg14),opsDat14Local, (/opsArg14%dim/))
  dat14_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg15),opsDat15Local, (/opsArg15%dim/))
  dat15_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg16),opsDat16Local, (/opsArg16%dim/))
  dat16_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg17),opsDat17Local, (/opsArg17%dim/))
  dat17_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg18),opsDat18Local, (/opsArg18%dim/))
  dat18_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg19),opsDat19Local, (/opsArg19%dim/))
  dat19_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg20),opsDat20Local, (/opsArg20%dim/))
  dat20_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg21),opsDat21Local, (/opsArg21%dim/))
  dat21_base = 1

  call c_f_pointer(getGblPtrFromOpsArg(opsArg22),opsDat22Local, (/opsArg22%dim/))
  dat22_base = 1

#ifndef OPS_LAZY
  call ops_H_D_exchanges_host(opsArgArray,23)
  call ops_halo_exchanges(opsArgArray,23,range)
  call ops_H_D_exchanges_host(opsArgArray,23)
#endif

  call ops_timers_core(t2)

  call tempin_kernel_main_wrap( &
  & opsDat1Local, &
  & opsDat2Local, &
  & opsDat3Local, &
  & opsDat4Local, &
  & opsDat5Local, &
  & opsDat6Local, &
  & opsDat7Local, &
  & opsDat8Local, &
  & opsDat9Local, &
  & opsDat10Local, &
  & opsDat11Local, &
  & opsDat12Local, &
  & opsDat13Local, &
  & opsDat14Local, &
  & opsDat15Local, &
  & opsDat16Local, &
  & opsDat17Local, &
  & opsDat18Local, &
  & opsDat19Local, &
  & opsDat20Local, &
  & opsDat21Local, &
  & opsDat22Local, &
  & idx, &
  & dat1_base, &
  & dat2_base, &
  & dat3_base, &
  & dat4_base, &
  & dat5_base, &
  & dat6_base, &
  & dat7_base, &
  & dat8_base, &
  & dat9_base, &
  & dat10_base, &
  & dat11_base, &
  & dat12_base, &
  & dat13_base, &
  & dat14_base, &
  & dat15_base, &
  & dat16_base, &
  & dat17_base, &
  & dat18_base, &
  & dat19_base, &
  & dat20_base, &
  & dat21_base, &
  & dat22_base, &
  & start, &
  & end )

  call ops_timers_core(t3)
#ifndef OPS_LAZY
  call ops_set_dirtybit_host(opsArgArray, 23)
  call ops_set_halo_dirtybit3(opsArg1,range)
  call ops_set_halo_dirtybit3(opsArg2,range)
  call ops_set_halo_dirtybit3(opsArg3,range)
  call ops_set_halo_dirtybit3(opsArg4,range)
  call ops_set_halo_dirtybit3(opsArg5,range)
#endif

  !Timing and data movement
  transfer_total = 0.0_4
  call ops_compute_transfer(3, start, end, opsArg1,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg2,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg3,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg4,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg5,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg6,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg7,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg8,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg9,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg10,transfer)
  transfer_total = transfer_total + transfer
  call ops_compute_transfer(3, start, end, opsArg11,transfer)
  transfer_total = transfer_total + transfer
  call setKernelTime(541,userSubroutine,t3-t2,t2-t1,transfer_total,0)
end subroutine

#ifdef OPS_LAZY
subroutine tempin_kernel_main_host( userSubroutine, block, dim, range, &
& opsArg1, &
& opsArg2, &
& opsArg3, &
& opsArg4, &
& opsArg5, &
& opsArg6, &
& opsArg7, &
& opsArg8, &
& opsArg9, &
& opsArg10, &
& opsArg11, &
& opsArg12, &
& opsArg13, &
& opsArg14, &
& opsArg15, &
& opsArg16, &
& opsArg17, &
& opsArg18, &
& opsArg19, &
& opsArg20, &
& opsArg21, &
& opsArg22, &
& opsArg23)
  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN), TARGET :: userSubroutine
  type ( ops_block ), INTENT(IN) :: block
  integer(kind=4), INTENT(IN):: dim
  integer(kind=4), DIMENSION(2*dim), INTENT(INOUT), TARGET :: range
  integer(kind=4), DIMENSION(2*dim), TARGET :: range_tmp
  type ( ops_arg ), INTENT(IN) :: opsArg1
  type ( ops_arg ), INTENT(IN) :: opsArg2
  type ( ops_arg ), INTENT(IN) :: opsArg3
  type ( ops_arg ), INTENT(IN) :: opsArg4
  type ( ops_arg ), INTENT(IN) :: opsArg5
  type ( ops_arg ), INTENT(IN) :: opsArg6
  type ( ops_arg ), INTENT(IN) :: opsArg7
  type ( ops_arg ), INTENT(IN) :: opsArg8
  type ( ops_arg ), INTENT(IN) :: opsArg9
  type ( ops_arg ), INTENT(IN) :: opsArg10
  type ( ops_arg ), INTENT(IN) :: opsArg11
  type ( ops_arg ), INTENT(IN) :: opsArg12
  type ( ops_arg ), INTENT(IN) :: opsArg13
  type ( ops_arg ), INTENT(IN) :: opsArg14
  type ( ops_arg ), INTENT(IN) :: opsArg15
  type ( ops_arg ), INTENT(IN) :: opsArg16
  type ( ops_arg ), INTENT(IN) :: opsArg17
  type ( ops_arg ), INTENT(IN) :: opsArg18
  type ( ops_arg ), INTENT(IN) :: opsArg19
  type ( ops_arg ), INTENT(IN) :: opsArg20
  type ( ops_arg ), INTENT(IN) :: opsArg21
  type ( ops_arg ), INTENT(IN) :: opsArg22
  type ( ops_arg ), INTENT(IN) :: opsArg23
  type ( ops_arg ), DIMENSION(23), TARGET :: opsArgArray
  integer(kind=4) :: n

  opsArgArray(1) = opsArg1
  opsArgArray(2) = opsArg2
  opsArgArray(3) = opsArg3
  opsArgArray(4) = opsArg4
  opsArgArray(5) = opsArg5
  opsArgArray(6) = opsArg6
  opsArgArray(7) = opsArg7
  opsArgArray(8) = opsArg8
  opsArgArray(9) = opsArg9
  opsArgArray(10) = opsArg10
  opsArgArray(11) = opsArg11
  opsArgArray(12) = opsArg12
  opsArgArray(13) = opsArg13
  opsArgArray(14) = opsArg14
  opsArgArray(15) = opsArg15
  opsArgArray(16) = opsArg16
  opsArgArray(17) = opsArg17
  opsArgArray(18) = opsArg18
  opsArgArray(19) = opsArg19
  opsArgArray(20) = opsArg20
  opsArgArray(21) = opsArg21
  opsArgArray(22) = opsArg22
  opsArgArray(23) = opsArg23

  DO n = 1, 3
    range_tmp(2*n-1) = range(2*n-1)-1
    range_tmp(2*n) = range(2*n)
  END DO

  call create_kerneldesc_and_enque(userSubroutine//c_null_char, c_loc(opsArgArray), 23, 541, dim, 0, c_loc(range_tmp), block%blockCptr, c_funloc(tempin_kernel_main_host_execute))
end subroutine
#endif

END MODULE
