#!/bin/sh
#
#  Makes a library of the parallel interface routines
#
#
$MPIF90 -O3 -I/usr/include -c p_init.f
$MPIF90 -O3 -I/usr/include -c p_stop.f
$MPIF90 -O3 -I/usr/include -c p_size.f
$MPIF90 -O3 -I/usr/include -c p_send.f
$MPIF90 -O3 -I/usr/include -c p_recv.f
$MPIF90 -O3 -I/usr/include -c p_bcst.f
$MPIF90 -O3 -I/usr/include -c p_summ.f
$MPIF90 -O3 -I/usr/include -c p_gmax.f
$MPIF90 -O3 -I/usr/include -c p_gmin.f
$MPIF90 -O3 -I/usr/include -c p_sync.f
#
ar rcsv parlib.a \
        p_init.o p_stop.o p_size.o p_send.o p_recv.o \
        p_bcst.o p_summ.o p_gmax.o p_gmin.o p_sync.o
#
rm *.o
#
exit
