C     CHEMIN-------------------------------------------------------------------

C     PARAMETERS
C     ==========
      INTEGER NSPCMX,NSTPMX,NBDYMX
      PARAMETER(NSPCMX = 100, NSTPMX = 1000, NBDYMX = 10)
      INTEGER NGIBMX,NLNDMX
      PARAMETER(NGIBMX = 100, NLNDMX = 10)
      INTEGER NLSMAX,NSSMAX,NRSMAX
      PARAMETER(NLSMAX=20, NSSMAX=20, NRSMAX=10)
      INTEGER NLGMAX,NLLMAX
      PARAMETER(NLGMAX=20, NLLMAX=20)
      INTEGER NTINMX,NCOFMX
      PARAMETER(NTINMX=2, NCOFMX=7)

C     CHEMICAL DATA
C     =============
      DOUBLE PRECISION ACOFCP(NCOFMX,NTINMX,NSPCMX)
      DOUBLE PRECISION TINTLO(NTINMX,NSPCMX),TINTHI(NTINMX,NSPCMX)
      DOUBLE PRECISION DIFFMU(NLSMAX,NSPCMX)
      DOUBLE PRECISION CRSPEC(NLSMAX,NSPCMX),CPSPEC(NLSMAX,NSPCMX)
      DOUBLE PRECISION EFFY3B(NSPCMX,NBDYMX)
      DOUBLE PRECISION DIFGIB(NLGMAX,NGIBMX)
      DOUBLE PRECISION RPARAM(3,NSTPMX)
      DOUBLE PRECISION RCLIND(4,NLLMAX)
      DOUBLE PRECISION RCTROE(12,NLLMAX)
      DOUBLE PRECISION RCSRIF(8,NLLMAX)
      DOUBLE PRECISION WMOLAR(NSPCMX),CLEWIS(NSPCMX)
      DOUBLE PRECISION PREFGB

      INTEGER NLSTEP(NLSMAX,NSPCMX)
      INTEGER NSSPEC(NSSMAX,NSTPMX)
      INTEGER NRSPEC(NRSMAX,NSTPMX),NPSPEC(NRSMAX,NSTPMX)
      INTEGER NRCPEC(NRSMAX,NSTPMX),NPCPEC(NRSMAX,NSTPMX)
      INTEGER MGSPEC(NLGMAX,NGIBMX)
      INTEGER NCOFCP(NTINMX,NSPCMX)
      INTEGER NSSLEN(NSTPMX)
      INTEGER NRSLEN(NSTPMX),NPSLEN(NSTPMX)
      INTEGER NRCLEN(NSTPMX),NPCLEN(NSTPMX)
      INTEGER MBLIST(NSTPMX)
      INTEGER MGLIST(NSTPMX)
      INTEGER MLLIST(NSTPMX)
      INTEGER MTLIST(NSTPMX)
      INTEGER MSLIST(NSTPMX)
      INTEGER NLSLEN(NSPCMX)
      INTEGER LENSYM(NSPCMX)
      INTEGER NTINT(NSPCMX)
      INTEGER LENBDY(NBDYMX)
      INTEGER NLGLEN(NGIBMX)
      INTEGER NSPEC,NSTEP,NBODY,NGIBB,NLIND,NTROE,NSRIF
 
      CHARACTER*10 SPCSYM(NSPCMX)
      CHARACTER*10 BDYSYM(NSPCMX)

      COMMON/CHEMIN/ACOFCP,TINTLO,TINTHI,
     +              DIFFMU,CRSPEC,CPSPEC,EFFY3B,DIFGIB,
     +              RPARAM,RCLIND,RCTROE,RCSRIF,WMOLAR,CLEWIS,PREFGB,
     +              NLSTEP,NSSPEC,NRSPEC,NPSPEC,NRCPEC,NPCPEC,
     +              MGSPEC,NCOFCP,
     +              NSSLEN,NRSLEN,NPSLEN,NRCLEN,NPCLEN,
     +              MBLIST,MGLIST,MLLIST,MTLIST,MSLIST,
     +              NLSLEN,LENSYM,NTINT,LENBDY,NLGLEN,
     +              NSPEC,NSTEP,NBODY,NGIBB,NLIND,NTROE,NSRIF,
     +              SPCSYM,BDYSYM

C     CHEMIN-------------------------------------------------------------------
