#!/bin/sh
#
#
#
#
cd ppchem/codes/ppthrm
./Makept
cp ppthrm ../..
cd ../../..
#
cd ppchem/codes/ppchem
./Makepp
cp ppchem ../..
cd ../../..
#
cd parlib
./Makepar
cd ..
#
cd fftlib
./Makeftl
cd ..
#
cd rndlib
./Makeran
cd ..
#
#rm senga2
#make
#
exit
