!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcdtxl

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCDT_KERNEL_XDIR_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















    integer :: rangexyz(6)






    rangexyz = (/1,1,1,nyglbl,1,nzglbl/)
    call bcdt_kernel_xdir_host("bcdt_kernel_xdir", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_strdxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                      & ops_arg_dat(d_dddtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                      & ops_arg_gbl(drin, 1, "real(8)", OPS_READ))


END SUBROUTINE bcdtxl
