!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcdtyr

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCDT_KERNEL_YDIR_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















    integer(kind=4) :: rangexyz(6)






    rangexyz = [1,nxglbl,nyglbl,nyglbl,1,nzglbl]
    call bcdt_kernel_ydir_host("bcdt_kernel_ydir", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_strdyr, 1, s3d_000_strid3d_xz, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_dddtyr, 1, s3d_000_strid3d_xz, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(drin, 1, "real(kind=8)", OPS_READ))


END SUBROUTINE bcdtyr
