!
! auto-generated by ops_fortran.py
!
SUBROUTINE bctixl

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use COPY_KERNEL_MODULE
  use SET_ZERO_KERNEL_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















    CHARACTER (LEN=4) :: pntixl,pntcxl
    CHARACTER (LEN=4) :: pnxdat
    PARAMETER(pntixl='tixl', pntcxl='tcxl', pnxdat='.dat')


    integer :: icproc
    integer :: kxmodd,ixmodd
    integer :: itotxl
    CHARACTER (LEN=6) :: pnproc
    LOGICAL :: fxdump
    integer :: rangexyz(6)




    WRITE(pnproc,'(I6.6)')iproc

    fntixl = pntixl//pnproc//pnxdat

    fntcxl = pntcxl//pnproc//pnxdat

    nctixl = 3



    IF(nxlprm(2) == 0) THEN





        INQUIRE(FILE=fntixl,EXIST=fxdump)
        IF(.NOT.fxdump) THEN
            OPEN(UNIT=nctixl,FILE=fntixl,STATUS='NEW',FORM='UNFORMATTED')
            CLOSE(nctixl)
        END IF


        OPEN(UNIT=nctixl,FILE=fntcxl,STATUS='OLD',FORM='UNFORMATTED')
            READ(nctixl)store1,store4,store5,store6
        CLOSE(nctixl)


        rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
        call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_urun, 1, s3d_000, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_store4, 1, s3d_000, "real(8)", OPS_READ))

        call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_vrun, 1, s3d_000, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_store5, 1, s3d_000, "real(8)", OPS_READ))

        call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_wrun, 1, s3d_000, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_store6, 1, s3d_000, "real(8)", OPS_READ))


        rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
        call set_zero_kernel_host("set zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_utmp, 1, s3d_000, "real(8)", OPS_WRITE))

        call set_zero_kernel_host("set zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_vtmp, 1, s3d_000, "real(8)", OPS_WRITE))

        call set_zero_kernel_host("set zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_wtmp, 1, s3d_000, "real(8)", OPS_WRITE))


        call buftxl



        bvelxl = rxlprm(1)
        svelxl = bvelxl + rxlprm(2)
        elocxl = xgdlen - rxlprm(3)


    ELSE




        write(*, '(a)') "Using the arrays not allocated by OPS, &
                        Please implement the function in OPS first, bctixl.F90: ID=137"
            STOP
        OPEN(UNIT=nctixl,FILE=fntixl,STATUS='OLD',FORM='UNFORMATTED')
            READ(nctixl)ufxl,vfxl,wfxl,elocxl,svelxl,bvelxl
        CLOSE(nctixl)


    END IF


    slocxl = elocxl

    tpovxg = two*pi/xgdlen
    scauxl = two/REAL(nxglbl,kind=8)
    scduxl = -two*pi*scauxl*REAL(nxglbl-1,kind=8)/REAL(nxglbl,kind=8)/xgdlen

    fllixl = .false.
    fltrxl = .false.
    istaxl = 1
    istoxl = npmapx(ixproc)

    kminxl = 0
    DO icproc = 0, ixproc-1
        kminxl = kminxl + npmapx(icproc)
    END DO
    kxmodd = MOD(kminxl,2)
    itotxl = kminxl + npmapx(ixproc)

    ixmodd = MOD(istoxl,2)

    IF(kxmodd == 0) THEN



        IF(kminxl > 0) fllixl = .true.
        kminxl = kminxl/2
        istaxl = 2
        IF(ixmodd == 0) THEN

            istoxl = istoxl - 1
            IF(itotxl == nxglbl) THEN

                fltrxl = .false.
            ELSE
                fltrxl = .true.
            END IF
        ELSE

            fltrxl = .false.
        END IF

    ELSE



        fllixl = .false.
        kminxl = kminxl/2 + 1
        istaxl = 1
        IF(ixmodd == 0) THEN

            fltrxl = .false.
        ELSE

            istoxl = istoxl - 1
            IF(itotxl == nxglbl) THEN

                fltrxl = .false.
            ELSE
                fltrxl = .true.
            END IF
        END IF

    END IF


END SUBROUTINE bctixl
