!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcttxl

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCDT_KERNEL_XDIR_MODULE
  use BCDT_KERNEL_XDIR_EQA_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















    integer :: rangexyz(6)






    rangexyz = (/1,1,1,nyglbl,1,nzglbl/)
    call bcdt_kernel_xdir_host("bcdt_kernel_xdir", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_strtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                      & ops_arg_dat(d_dtdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                      & ops_arg_gbl(trin, 1, "real(8)", OPS_READ))


    IF(nsbcxl == nsbcw2) THEN
        rangexyz = (/1,1,1,nyglbl,1,nzglbl/)
        call bcdt_kernel_xdir_eqA_host("bcdt_kernel_xdir", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_strtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dtdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_gbl(rxlprm, nbcprr, "real(8)", OPS_READ))

    END IF


END SUBROUTINE bcttxl
