!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcttzr

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCDT_KERNEL_ZDIR_MODULE
  use BCDT_KERNEL_ZDIR_EQA_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















    integer(kind=4) :: rangexyz(6)






    rangexyz = [1,nxglbl,1,nyglbl,nzglbl,nzglbl]
    call bcdt_kernel_zdir_host("bcdt_kernel_zdir", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_strtzr, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_dtdtzr, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(trin, 1, "real(kind=8)", OPS_READ))


    IF(nsbczr == nsbcw2) THEN
        rangexyz = [1,nxglbl,1,nyglbl,nzglbl,nzglbl]
        call bcdt_kernel_zdir_eqA_host("bcdt_kernel_zdir", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_strtzr, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_dtdtzr, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_gbl(rzrprm, nbcprr, "real(kind=8)", OPS_READ))

    END IF


END SUBROUTINE bcttzr
