!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcttyl

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCDT_KERNEL_YDIR_MODULE
  use BCDT_KERNEL_YDIR_EQA_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga

















    integer :: rangexyz(6)






    rangexyz = (/1,nxglbl,1,1,1,nzglbl/)
    call bcdt_kernel_ydir_host("bcdt_kernel_ydir", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_strtyl, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                      & ops_arg_dat(d_dtdtyl, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                      & ops_arg_gbl(trin, 1, "real(8)", OPS_READ))


    IF(nsbcyl == nsbcw2) THEN
        rangexyz = (/1,nxglbl,1,1,1,nzglbl/)
        call bcdt_kernel_ydir_eqA_host("bcdt_kernel_ydir", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_strtyl, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dtdtyl, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_gbl(rylprm, nbcprr, "real(8)", OPS_READ))

    END IF


END SUBROUTINE bcttyl
