!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcutxr

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCUT_KERNEL_XDIR_CONST_UVEL_MODULE
  use BCUT_KERNEL_XDIR_SINUSOIDAL_UVEL_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga

















    real(kind=8) :: fornow,argmnt
    integer :: jc,kc
    integer :: rangexyz(6)
    real(kind=8) :: init_val1, init_val2







    IF(nxrprm(1) == 1) THEN
        rangexyz = (/nxglbl,nxglbl,1,nyglbl,1,nzglbl/)
        call bcut_kernel_xdir_const_uvel_host("bcut_kernel_xdir_const_uvel", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_struxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strvxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strwxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dudtxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dvdtxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dwdtxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_gbl(rxrprm, nbcprr, "real(8)", OPS_READ))

    END IF



    IF(nxrprm(1) == 2) THEN
        fornow = two*pi/rxrprm(2)
        argmnt = fornow*btime
        init_val1 = rxrprm(1)*SIN(argmnt)
        init_val2 = fornow*rxrprm(1)*COS(argmnt)

        rangexyz = (/nxglbl,nxglbl,1,nyglbl,1,nzglbl/)
        call bcut_kernel_xdir_sinusoidal_uvel_host("bcut_kernel_xdir_sinusoidal_uvel", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_struxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strvxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strwxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dudtxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dvdtxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dwdtxr, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_gbl(init_val1, 1, "real(8)", OPS_READ), &
                          & ops_arg_gbl(init_val2, 1, "real(8)", OPS_READ))

    END IF


END SUBROUTINE bcutxr
