!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcutzl

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCUT_KERNEL_ZDIR_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















    integer(kind=4) :: rangexyz(6)






    IF(nzlprm(1) == 1) THEN
        rangexyz = [1,nxglbl,1,nyglbl,1,1]
        call bcut_kernel_zdir_host("bcut_kernel_zdir", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_struzl, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_strvzl, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_strwzl, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_dudtzl, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_dvdtzl, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_dwdtzl, 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_gbl(rzlprm, nbcprr, "real(kind=8)", OPS_READ))

    END IF


END SUBROUTINE bcutzl
