!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcutyr

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCUT_KERNEL_YDIR_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga

















    integer :: rangexyz(6)






    IF(nyrprm(1) == 1) THEN
        rangexyz = (/1,nxglbl,nyglbl,nyglbl,1,nzglbl/)
        call bcut_kernel_ydir_host("bcut_kernel_ydir", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_struyr, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strvyr, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strwyr, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dudtyr, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dvdtyr, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dwdtyr, 1, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_gbl(ryrprm, nbcprr, "real(8)", OPS_READ))

    END IF


END SUBROUTINE bcutyr
