!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcutxl

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCUT_KERNEL_XDIR_CONST_UVEL_MODULE
  use BCUT_KERNEL_XDIR_SINUSOIDAL_UVEL_MODULE
  use SET_ZERO_KERNEL_XDIR_MODULE
  use BCUT_KERNEL_XDIR_EQA_MODULE
  use BCUT_KERNEL_XDIR_EQB_MODULE
  use BCUT_KERNEL_XDIR_EQC_MODULE
  use BCUT_KERNEL_XDIR_EQD_MODULE
  use BCUT_KERNEL_XDIR_EQE_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga

















    real(kind=8) :: fornow,argmnt,argval,realkx
    real(kind=8) :: cosval,sinval,costht,sintht
    real(kind=8) :: pcount
    integer :: ic,jc,kc
    integer :: iic,iim,kx,kxbase
    integer :: icproc,ncount,irproc,irtag
    integer :: rangexyz(6)
    real(kind=8) :: init_val1, init_val2







    IF(nxlprm(1) == 1) THEN
        rangexyz = (/1,1,1,nyglbl,1,nzglbl/)
        call bcut_kernel_xdir_const_uvel_host("bcut_kernel_xdir_const_uvel", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_struxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strvxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strwxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dudtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dvdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dwdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_gbl(rxlprm, nbcprr, "real(8)", OPS_READ))

    END IF



    IF(nxlprm(1) == 2) THEN
        fornow = two*pi/rxlprm(2)
        argmnt = fornow*btime
        init_val1 = rxlprm(1)*SIN(argmnt)
        init_val2 = fornow*rxlprm(1)*COS(argmnt)

        rangexyz = (/1,1,1,nyglbl,1,nzglbl/)
        call bcut_kernel_xdir_sinusoidal_uvel_host("bcut_kernel_xdir_sinusoidal_uvel", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_struxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strvxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_strwxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dudtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dvdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dwdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE), &
                          & ops_arg_gbl(init_val1, 1, "real(8)", OPS_READ), &
                          & ops_arg_gbl(init_val2, 1, "real(8)", OPS_READ))

    END IF



    IF(nxlprm(1) == 3) THEN



        slocxl = elocxl - svelxl*btime
        IF(slocxl < zero) slocxl = xgdlen + slocxl

        IF(fupelc) elocxl = slocxl

        argmnt = tpovxg*slocxl
        costht = COS(argmnt)
        sintht = SIN(argmnt)
        kxbase = kminxl

        rangexyz = (/1,1,1,nyglbl,1,nzglbl/)
        call set_zero_kernel_xdir_host("set zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_struxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE))
        call set_zero_kernel_xdir_host("set zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_strvxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE))
        call set_zero_kernel_xdir_host("set zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_strwxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE))
        call set_zero_kernel_xdir_host("set zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_dudtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE))
        call set_zero_kernel_xdir_host("set zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_dvdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE))
        call set_zero_kernel_xdir_host("set zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_dwdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_WRITE))


        IF(fllixl) THEN

            kx = kxbase
            realkx = REAL(kx,kind=8)
            argval = argmnt*realkx
            cosval = COS(argval)
            sinval = SIN(argval)
            iic = 1

            rangexyz = (/1,1,1,nyglbl,1,nzglbl/)
            call bcut_kernel_xdir_eqA_host("A = A + B*val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_struxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_ufxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(sinval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqA_host("A = A + B*val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_strvxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_vfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(sinval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqA_host("A = A + B*val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_strwxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_wfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(sinval, 1, "real(8)", OPS_READ))

            call bcut_kernel_xdir_eqB_host("A = A - val1*B*val2", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dudtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_ufxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(realkx, 1, "real(8)", OPS_READ), &
                              & ops_arg_gbl(cosval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqB_host("A = A - val1*B*val2", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dvdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_vfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(realkx, 1, "real(8)", OPS_READ), &
                              & ops_arg_gbl(cosval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqB_host("A = A - val1*B*val2", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dwdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_wfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(realkx, 1, "real(8)", OPS_READ), &
                              & ops_arg_gbl(cosval, 1, "real(8)", OPS_READ))

            kxbase = kxbase + 1

        END IF



        IF(kxbase == 0) THEN
            kx = kxbase
            realkx = REAL(kx,kind=8)
            argval = argmnt*realkx
            cosval = COS(argval)
            sinval = SIN(argval)
            iim = 1

            rangexyz = (/1,1,1,nyglbl,1,nzglbl/)
            call bcut_kernel_xdir_eqC_host("A = A + val1*B*val2", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_struxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_ufxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(half, 1, "real(8)", OPS_READ), &
                              & ops_arg_gbl(cosval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqC_host("A = A + val1*B*val2", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_strvxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_vfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(half, 1, "real(8)", OPS_READ), &
                              & ops_arg_gbl(cosval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqC_host("A = A + val1*B*val2", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_strwxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_wfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(half, 1, "real(8)", OPS_READ), &
                              & ops_arg_gbl(cosval, 1, "real(8)", OPS_READ))

            kxbase = kxbase + 1

        END IF

        DO kc = 1,nzsize
            DO jc = 1,nysize

                kx = kxbase
                realkx = REAL(kx,kind=8)
                argval = argmnt*realkx
                cosval = COS(argval)
                sinval = SIN(argval)

                DO ic = istaxl,istoxl,2
                    write(*, '(a)') "Using the arrays not allocated by OPS, &
                        Please implement the function in OPS first, bcutxl.F90: ID=233"
                    STOP
                    iim = ic
                    iic = ic+1

                    struxl(1,jc,kc) = struxl(1,jc,kc) + ufxl(iim,jc,kc)*cosval  &
                                    + ufxl(iic,jc,kc)*sinval
                    strvxl(1,jc,kc) = strvxl(1,jc,kc) + vfxl(iim,jc,kc)*cosval  &
                                    + vfxl(iic,jc,kc)*sinval
                    strwxl(1,jc,kc) = strwxl(1,jc,kc) + wfxl(iim,jc,kc)*cosval  &
                                    + wfxl(iic,jc,kc)*sinval

                    dudtxl(1,jc,kc) = dudtxl(1,jc,kc) + realkx*(ufxl(iim,jc,kc)*sinval  &
                                    - ufxl(iic,jc,kc)*cosval)
                    dvdtxl(1,jc,kc) = dvdtxl(1,jc,kc) + realkx*(vfxl(iim,jc,kc)*sinval  &
                                    - vfxl(iic,jc,kc)*cosval)
                    dwdtxl(1,jc,kc) = dwdtxl(1,jc,kc) + realkx*(wfxl(iim,jc,kc)*sinval  &
                                    - wfxl(iic,jc,kc)*cosval)

                    kx = kx + 1
                    realkx = REAL(kx,kind=8)
                    fornow = cosval
                    cosval = costht*cosval - sintht*sinval
                    sinval = sintht*fornow + costht*sinval

                END DO

            END DO
        END DO


        IF(fltrxl) THEN

            kx = kxbase + istoxl/2
            realkx = REAL(kx,kind=8)
            argval = argmnt*realkx
            cosval = COS(argval)
            sinval = SIN(argval)
            iim = istoxl + 1

            write(*, '(a)') "Please correct range for the OPS par loop, bcutxl.F90: ID=275"
            STOP

            rangexyz = (/iim,iim,1,nyglbl,1,nzglbl/)
            call bcut_kernel_xdir_eqA_host("A = A + B*val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_struxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_ufxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(cosval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqA_host("A = A + B*val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_strvxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_vfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(cosval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqA_host("A = A + B*val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_strwxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_wfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(cosval, 1, "real(8)", OPS_READ))

            call bcut_kernel_xdir_eqC_host("A = A + val1*B*val2", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dudtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_ufxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(realkx, 1, "real(8)", OPS_READ), &
                              & ops_arg_gbl(sinval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqC_host("A = A + val1*B*val2", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dvdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_vfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(realkx, 1, "real(8)", OPS_READ), &
                              & ops_arg_gbl(sinval, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqC_host("A = A + val1*B*val2", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dwdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_dat(d_wfxl, 1, s3d_000, "real(8)", OPS_READ), &
                              & ops_arg_gbl(realkx, 1, "real(8)", OPS_READ), &
                              & ops_arg_gbl(sinval, 1, "real(8)", OPS_READ))

        END IF



        IF(ixproc == 0)THEN


            DO icproc = 1,nxprm1

                irproc = nprocx(icproc)
                irtag = irproc*nproc+iproc
                call p_recv(pcount,1,irproc,irtag)
                call p_recv(parray,nparay,irproc,irtag)

                ncount = 0
                DO kc = 1,nzsize
                    DO jc = 1,nysize

                        write(*, '(a)') "Using the arrays not allocated by OPS, &
                                         Please implement the function in OPS first, bcutxl.F90: ID=332"
                        STOP

                        ncount = ncount + 1
                        struxl(1,jc,kc) = struxl(1,jc,kc) + parray(ncount)
                        ncount = ncount + 1
                        strvxl(1,jc,kc) = strvxl(1,jc,kc) + parray(ncount)
                        ncount = ncount + 1
                        strwxl(1,jc,kc) = strwxl(1,jc,kc) + parray(ncount)
                        ncount = ncount + 1
                        dudtxl(1,jc,kc) = dudtxl(1,jc,kc) + parray(ncount)
                        ncount = ncount + 1
                        dvdtxl(1,jc,kc) = dvdtxl(1,jc,kc) + parray(ncount)
                        ncount = ncount + 1
                        dwdtxl(1,jc,kc) = dwdtxl(1,jc,kc) + parray(ncount)

                    END DO
                END DO

            END DO

            rangexyz = (/1,1,1,nyglbl,1,nzglbl/)

            call bcut_kernel_xdir_eqD_host("A = A * val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_struxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_RW), &
                              & ops_arg_gbl(scauxl, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqD_host("A = A * val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_strvxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_RW), &
                              & ops_arg_gbl(scauxl, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqD_host("A = A * val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_strwxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_RW), &
                              & ops_arg_gbl(scauxl, 1, "real(8)", OPS_READ))

            call bcut_kernel_xdir_eqD_host("A = A * val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dudtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_RW), &
                              & ops_arg_gbl(scduxl, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqD_host("A = A * val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dvdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_RW), &
                              & ops_arg_gbl(scduxl, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqD_host("A = A * val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dwdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_RW), &
                              & ops_arg_gbl(scduxl, 1, "real(8)", OPS_READ))

            call bcut_kernel_xdir_eqE_host("A = A + val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_struxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_INC), &
                              & ops_arg_gbl(bvelxl, 1, "real(8)", OPS_READ))

            call bcut_kernel_xdir_eqD_host("A = A * val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dudtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_RW), &
                              & ops_arg_gbl(svelxl, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqD_host("A = A * val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dvdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_RW), &
                              & ops_arg_gbl(svelxl, 1, "real(8)", OPS_READ))
            call bcut_kernel_xdir_eqD_host("A = A * val1", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_dwdtxl, 1, s3d_000_strid3d_yz, "real(8)", OPS_RW), &
                              & ops_arg_gbl(svelxl, 1, "real(8)", OPS_READ))

        ELSE


            ncount = 0
            DO kc = 1,nzsize
                DO jc = 1,nysize

                    write(*, '(a)') "Using the arrays not allocated by OPS, &
                                    Please implement the function in OPS first, bcutxl.F90: ID=402"
                    STOP

                    ncount = ncount + 1
                    parray(ncount) = struxl(1,jc,kc)
                    ncount = ncount + 1
                    parray(ncount) = strvxl(1,jc,kc)
                    ncount = ncount + 1
                    parray(ncount) = strwxl(1,jc,kc)
                    ncount = ncount + 1
                    parray(ncount) = dudtxl(1,jc,kc)
                    ncount = ncount + 1
                    parray(ncount) = dvdtxl(1,jc,kc)
                    ncount = ncount + 1
                    parray(ncount) = dwdtxl(1,jc,kc)

                END DO
            END DO

            pcount = REAL(ncount,kind=8)
            irproc = nprocx(0)
            irtag = iproc*nproc+irproc
            call p_send(pcount,1,1,irproc,irtag)
            call p_send(parray,nparay,ncount,irproc,irtag)

        END IF

    END IF


END SUBROUTINE bcutxl
