!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcytyl

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCYT_KERNEL_YDIR_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















    integer :: ispec
    integer :: rangexyz(6)






    DO ispec = 1,nspec
        rangexyz = (/1,nxglbl,1,1,1,nzglbl/)
        call bcyt_kernel_ydir_host("bcyt_kernel_ydir", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_stryyl, 9, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_dydtyl, 9, s3d_000_strid3d_xz, "real(8)", OPS_WRITE), &
                          & ops_arg_gbl(yrin, nspcmx, "real(8)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer", OPS_READ))

    END DO


END SUBROUTINE bcytyl
