!
! auto-generated by ops_fortran.py
!
SUBROUTINE bcytzr

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use BCYT_KERNEL_ZDIR_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















    integer(kind=4) :: ispec
    integer(kind=4) :: rangexyz(6)






    DO ispec = 1,nspec
        rangexyz = [1,nxglbl,1,nyglbl,nzglbl,nzglbl]
        call bcyt_kernel_zdir_host("bcyt_kernel_zdir", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_stryzr(ispec), 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_dydtzr(ispec), 1, s3d_000_strid3d_xy, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_gbl(yrin, nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

    END DO


END SUBROUTINE bcytzr
