!
! auto-generated by ops_fortran.py
!
SUBROUTINE chrate

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use SET_ZERO_KERNEL_MODULE
  use MATHS_KERNEL_EQJ_MODULE
  use MATHS_KERNEL_EQAW_MODULE
  use MATHS_KERNEL_EQAX_MODULE
  use MATHS_KERNEL_EQAY_MODULE
  use MATHS_KERNEL_EQAZ_MODULE
  use MATHS_KERNEL_EQP_MODULE
  use MATHS_KERNEL_EQBM_MODULE
  use MATHS_KERNEL_EQBN_MODULE
  use MATHS_KERNEL_EQB_MODULE
  use MATHS_KERNEL_EQS_MODULE
  use MATHS_KERNEL_EQV_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga

















    real(kind=8), parameter :: ysmall = 0.000000000000000000000000000001_8,ydenom = 0.000000000000001_8


    real(kind=8) :: racnst,rncnst,reovrr
    real(kind=8) :: ovwmas,gibbsp,scoef,preduc
    real(kind=8) :: ovtst1,tstar2,ovtst3,omalph
    real(kind=8) :: fbroad,ftcent,trats1,trats2,trats3,cfactr,enfact
    real(kind=8) :: acfsri,bcfsrm,ovcsrm,dcfsri,ecfsri
    real(kind=8) :: fornow
    real(kind=8) :: talpha,flcnst,cfcst1,cfcst2,encst1,encst2,dtcnst
    integer(kind=4) :: ispec,isspec
    integer(kind=4) :: istep,ibody
    integer(kind=4) :: iindex,ipower,icoef1,icoef2,itint,icp
    LOGICAL :: flthrd
    integer(kind=4) :: rangexyz(6)










































    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    DO ispec = 1,nspec
        call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_rate(ispec), 1, s3d_000, "real(kind=8)", OPS_WRITE))

    END DO



    DO istep = 1, nstep




        flthrd = .true.

        IF(mblist(istep) /= 0) THEN

            ibody = mblist(istep)

            rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
            call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_store3, 1, s3d_000, "real(kind=8)", OPS_WRITE))


            DO ispec = 1,nspec


                ovwmas = ovwmol(ispec)*effy3b(ispec,ibody)


                rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
                call maths_kernel_eqJ_host("EVALUATE THE THIRD BODY CONCENTRATION", senga_grid, 3, rangexyz, &
                                  & ops_arg_dat(d_store3, 1, s3d_000, "real(kind=8)", OPS_INC), &
                                  & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(ovwmas, 1, "real(kind=8)", OPS_READ))

            END DO



        END IF



        racnst = rparam(1,istep)
        rncnst = rparam(2,istep)
        reovrr = rparam(3,istep)

        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call maths_kernel_eqAW_host("EVALUATE THE SPECIFIC REACTION RATE CONSTANT", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_RW), &
                          & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(racnst, 1, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(rncnst, 1, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(reovrr, 1, "real(kind=8)", OPS_READ))







        IF(mllist(istep) /= 0) THEN

            racnst = rclind(1,mllist(istep))
            rncnst = rclind(2,mllist(istep))
            reovrr = rclind(3,mllist(istep))
            flcnst = rclind(4,mllist(istep))

            rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
            call maths_kernel_eqAX_host("REFORMULATE FOR LINDEMANN RATE EXPRESSIONS", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_RW), &
                              & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_dat(d_store4, 1, s3d_000, "real(kind=8)", OPS_RW), &
                              & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(d_store3, 1, s3d_000, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(racnst, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(rncnst, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(reovrr, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(flcnst, 1, "real(kind=8)", OPS_READ))


            flthrd = .false.

        END IF





        IF(mtlist(istep) /= 0) THEN

            racnst = rctroe(1,mtlist(istep))
            rncnst = rctroe(2,mtlist(istep))
            reovrr = rctroe(3,mtlist(istep))
            talpha = rctroe(4,mtlist(istep))
            ovtst1 = rctroe(5,mtlist(istep))
            tstar2 = rctroe(6,mtlist(istep))
            ovtst3 = rctroe(7,mtlist(istep))
            cfcst1 = rctroe(8,mtlist(istep))
            cfcst2 = rctroe(9,mtlist(istep))
            encst1 = rctroe(10,mtlist(istep))
            encst2 = rctroe(11,mtlist(istep))
            dtcnst = rctroe(12,mtlist(istep))

            omalph = one - talpha

            rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
            call maths_kernel_eqAY_host("INCLUDE TROE FORM RATE EVALUATION", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_RW), &
                              & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_dat(d_store4, 1, s3d_000, "real(kind=8)", OPS_RW), &
                              & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(d_store3, 1, s3d_000, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(racnst, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(rncnst, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(reovrr, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(talpha, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(ovtst1, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(tstar2, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(ovtst3, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(cfcst1, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(cfcst2, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(encst1, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(encst2, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(dtcnst, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(omalph, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(clnten, 1, "real(kind=8)", OPS_READ))


            flthrd = .false.

        END IF





        IF(mslist(istep) /= 0)THEN

            racnst = rcsrif(1,mslist(istep))
            rncnst = rcsrif(2,mslist(istep))
            reovrr = rcsrif(3,mslist(istep))
            acfsri = rcsrif(4,mslist(istep))
            bcfsrm = rcsrif(5,mslist(istep))
            ovcsrm = rcsrif(6,mslist(istep))
            dcfsri = rcsrif(7,mslist(istep))
            ecfsri = rcsrif(8,mslist(istep))

            rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
            call maths_kernel_eqAZ_host("INCLUDE SRI FORM RATE EVALUATION", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_RW), &
                              & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_dat(d_store4, 1, s3d_000, "real(kind=8)", OPS_RW), &
                              & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(d_store3, 1, s3d_000, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(racnst, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(rncnst, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(reovrr, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(acfsri, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(bcfsrm, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(ovcsrm, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(dcfsri, 1, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(ecfsri, 1, "real(kind=8)", OPS_READ))


            flthrd = .false.

        END IF







        DO isspec = 1, nrslen(istep)

            ispec = nrspec(isspec,istep)


            rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
            call maths_kernel_eqP_host("A = A*max(B*var    zero)", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_RW), &
                              & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(ovwmol, nspcmx, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

        END DO








        IF(nrclen(istep) > 0) THEN

            DO isspec = 1, nrclen(istep)

                ispec = nrcpec(isspec,istep)

                scoef = crspec(isspec,istep)


                rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
                call maths_kernel_eqBM_host("EVALUATE REACTANT CONCENTRATIONS", senga_grid, 3, rangexyz, &
                                  & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_RW), &
                                  & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(ovwmol, nspcmx, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(scoef, 1, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(ysmall, 1, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(ydenom, 1, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

            END DO

        END IF




        IF(mglist(istep) /= 0) THEN




            DO isspec = 1, nsslen(istep)

                ispec = nsspec(isspec,istep)

                iindex = 1 + (ispec-1)/nspimx
                ipower = ispec - (iindex-1)*nspimx - 1
                icoef2 = ntbase**ipower
                icoef1 = icoef2*ntbase

                rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
                call maths_kernel_eqBN_host("EVALUATE GIBBS FUNCTION FOR EACH SPECIES", senga_grid, 3, rangexyz, &
                                  & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_INC), &
                                  & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                                  & ops_arg_dat(d_itndex(iindex), 1, s3d_000, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(amolgb, ncofmx*ntinmx*nspcmx, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(ncpoly, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(ncpom1, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(ncenth, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(ncenpy, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(diffmu, nssmax*nstpmx, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(isspec, 1, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(istep, 1, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(ipower, 1, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(icoef1, 1, "integer(kind=4)", OPS_READ), &
                                  & ops_arg_gbl(icoef2, 1, "integer(kind=4)", OPS_READ))

            END DO





            rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
            call maths_kernel_eqB_host("A = exp(A)", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_RW))







            DO isspec = 1, npslen(istep)

                ispec = npspec(isspec,istep)


                rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
                call maths_kernel_eqP_host("A = A*max(B*var    zero)", senga_grid, 3, rangexyz, &
                                  & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_RW), &
                                  & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(ovwmol, nspcmx, "real(kind=8)", OPS_READ), &
                                  & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

            END DO








            IF(npclen(istep) > 0) THEN

                DO isspec = 1, npclen(istep)

                    ispec = npcpec(isspec,istep)

                    scoef = cpspec(isspec,istep)


                    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
                    call maths_kernel_eqBM_host("EVALUATE PRODUCT CONCENTRATIONS", senga_grid, 3, rangexyz, &
                                      & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_RW), &
                                      & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                                      & ops_arg_gbl(ovwmol, nspcmx, "real(kind=8)", OPS_READ), &
                                      & ops_arg_gbl(scoef, 1, "real(kind=8)", OPS_READ), &
                                      & ops_arg_gbl(ysmall, 1, "real(kind=8)", OPS_READ), &
                                      & ops_arg_gbl(ydenom, 1, "real(kind=8)", OPS_READ), &
                                      & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

                END DO

            END IF




            rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
            call maths_kernel_eqS_host("A = A-B", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_INC), &
                              & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_READ))


        END IF





        IF(mblist(istep) /= 0) THEN


            IF(flthrd) THEN

                rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
                call maths_kernel_eqV_host("A = A*B", senga_grid, 3, rangexyz, &
                                  & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_RW), &
                                  & ops_arg_dat(d_store3, 1, s3d_000, "real(kind=8)", OPS_READ))

            END IF

        END IF





        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        DO isspec = 1, nsslen(istep)

            ispec = nsspec(isspec,istep)
            fornow = diffmw(isspec,istep)
            call maths_kernel_eqJ_host("A = A + var*B", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(d_rate(ispec), 1, s3d_000, "real(kind=8)", OPS_INC), &
                              & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_READ), &
                              & ops_arg_gbl(fornow, 1, "real(kind=8)", OPS_READ))

        END DO


    END DO



END SUBROUTINE chrate
