!
! auto-generated by ops_fortran.py
!
SUBROUTINE d2fdyz(functn,fderiv)
 use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use D2FDYZ_KERNEL_NULL_MODULE
  use D2FDYZ_KERNEL_INTERIOR_MODULE
  use D2FDYZ_KERNEL_LH_YDIR_4TH_ONESIDED_MODULE
  use D2FDYZ_KERNEL_LH_YDIR_4TH_MIXED_MODULE
  use D2FDYZ_KERNEL_LH_YDIR_4TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_LH_YDIR_6TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_LH_YDIR_8TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_RH_YDIR_8TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_RH_YDIR_6TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_RH_YDIR_4TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_RH_YDIR_4TH_MIXED_MODULE
  use D2FDYZ_KERNEL_RH_YDIR_4TH_ONESIDED_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_4TH_ONESIDED_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_4TH_MIXED_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_4TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_6TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_8TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQA_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQB_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQC_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQD_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQE_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQF_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQG_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQH_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQI_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQL_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQM_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQN_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQO_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQP_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQQ_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQR_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQS_MODULE
  use D2FDYZ_KERNEL_LH_ZDIR_CORNER_EQT_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_8TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_6TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_4TH_CENTRED_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_4TH_MIXED_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_4TH_ONESIDED_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQA_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQB_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQC_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQD_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQE_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQF_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQG_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQH_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQI_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQL_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQM_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQN_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQO_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQP_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQQ_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQR_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQS_MODULE
  use D2FDYZ_KERNEL_RH_ZDIR_CORNER_EQT_MODULE
  use D2FDYZ_KERNEL_SCALING_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga













    TYPE(ops_dat) :: functn, fderiv


    integer(kind=4) :: rangexyz(6)
    integer(kind=4) :: jstart,jfinis,kstart,kfinis



    IF (nyglbl==1 .or. nzglbl==1) THEN
        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call d2fdyz_kernel_null_host("d2fdyz_null", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

    ELSE



        jstart = 1
        jfinis = nyglbl
        kstart = 1
        kfinis = nzglbl
        IF(nendyl == nbound) jstart = 6
        IF(nendyr == nbound) jfinis = nyglbl-5
        IF(nendzl == nbound) kstart = 6
        IF(nendzr == nbound) kfinis = nzglbl-5



        rangexyz = [1,nxglbl,jstart,jfinis,kstart,kfinis]
        call d2fdyz_kernel_interior_host("d2fdyz_interior", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(functn, 1, s3d_p055_m055_mixed_yz, "real(kind=8)", OPS_READ), &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))



        IF(nendyl == nbound) THEN

            rangexyz = [1,nxglbl,1,1,kstart,kfinis]
            call d2fdyz_kernel_lh_ydir_4th_onesided_host("d2fdyz_lh_ydir_4th_onesided", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p042_m002_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,2,2,kstart,kfinis]
            call d2fdyz_kernel_lh_ydir_4th_mixed_host("d2fdyz_lh_ydir_4th_mixed", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p032_m012_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,3,3,kstart,kfinis]
            call d2fdyz_kernel_lh_ydir_4th_centred_host("d2fdyz_lh_ydir_4th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p022_m022_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,4,4,kstart,kfinis]
            call d2fdyz_kernel_lh_ydir_6th_centred_host("d2fdyz_lh_ydir_6th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p033_m033_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,5,5,kstart,kfinis]
            call d2fdyz_kernel_lh_ydir_8th_centred_host("d2fdyz_lh_ydir_8th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p044_m044_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

        END IF



        IF(nendyr == nbound) THEN

            rangexyz = [1,nxglbl,nyglbl-4,nyglbl-4,kstart,kfinis]
            call d2fdyz_kernel_rh_ydir_8th_centred_host("d2fdyz_rh_ydir_8th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p044_m044_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-3,nyglbl-3,kstart,kfinis]
            call d2fdyz_kernel_rh_ydir_6th_centred_host("d2fdyz_rh_ydir_6th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p033_m033_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-2,nyglbl-2,kstart,kfinis]
            call d2fdyz_kernel_rh_ydir_4th_centred_host("d2fdyz_rh_ydir_4th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p022_m022_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-1,nyglbl-1,kstart,kfinis]
            call d2fdyz_kernel_rh_ydir_4th_mixed_host("d2fdyz_rh_ydir_4th_mixed", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p012_m032_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl,nyglbl,kstart,kfinis]
            call d2fdyz_kernel_rh_ydir_4th_onesided_host("d2fdyz_rh_ydir_4th_onesided", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p002_m042_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

        END IF



        IF(nendzl == nbound) THEN

            rangexyz = [1,nxglbl,jstart,jfinis,1,1]
            call d2fdyz_kernel_lh_zdir_4th_onesided_host("d2fdyz_lh_zdir_4th_onesided", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p024_m020_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,jstart,jfinis,2,2]
            call d2fdyz_kernel_lh_zdir_4th_mixed_host("d2fdyz_lh_zdir_4th_mixed", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p023_m021_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,jstart,jfinis,3,3]
            call d2fdyz_kernel_lh_zdir_4th_centred_host("d2fdyz_lh_zdir_4th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p022_m022_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,jstart,jfinis,4,4]
            call d2fdyz_kernel_lh_zdir_6th_centred_host("d2fdyz_lh_zdir_6th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p033_m033_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,jstart,jfinis,5,5]
            call d2fdyz_kernel_lh_zdir_8th_centred_host("d2fdyz_lh_zdir_8th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p044_m044_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))


            IF(nendyl == nbound) THEN
            rangexyz = [1,nxglbl,1,1,1,1]
            call d2fdyz_kernel_lh_zdir_corner_eqA_host("d2fdyz_lh_zdir_corner_eqA", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p044_p000_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,2,2,2,2]
            call d2fdyz_kernel_lh_zdir_corner_eqB_host("d2fdyz_lh_zdir_corner_eqB", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p033_m011_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,1,1,2,2]
            call d2fdyz_kernel_lh_zdir_corner_eqC_host("d2fdyz_lh_zdir_corner_eqC", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p043_m001_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,2,2,1,1]
            call d2fdyz_kernel_lh_zdir_corner_eqD_host("d2fdyz_lh_zdir_corner_eqD", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p034_m010_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,3,5,1,1]
            call d2fdyz_kernel_lh_zdir_corner_eqE_host("d2fdyz_lh_zdir_corner_eqE", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p024_m020_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,3,5,2,2]
            call d2fdyz_kernel_lh_zdir_corner_eqF_host("d2fdyz_lh_zdir_corner_eqF", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p023_m021_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,1,1,3,5]
            call d2fdyz_kernel_lh_zdir_corner_eqG_host("d2fdyz_lh_zdir_corner_eqG", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p042_m002_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,2,2,3,5]
            call d2fdyz_kernel_lh_zdir_corner_eqH_host("d2fdyz_lh_zdir_corner_eqH", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p032_m012_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,3,5,3,5]
            call d2fdyz_kernel_lh_zdir_corner_eqI_host("d2fdyz_lh_zdir_corner_eqI", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p044_m044_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_idx())

            END IF


            IF(nendyr == nbound) THEN
            rangexyz = [1,nxglbl,nyglbl,nyglbl,1,1]
            call d2fdyz_kernel_lh_zdir_corner_eqL_host("d2fdyz_lh_zdir_corner_eqL", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p004_m040_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-1,nyglbl-1,2,2]
            call d2fdyz_kernel_lh_zdir_corner_eqM_host("d2fdyz_lh_zdir_corner_eqM", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p010_m030_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl,nyglbl,2,2]
            call d2fdyz_kernel_lh_zdir_corner_eqN_host("d2fdyz_lh_zdir_corner_eqN", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p003_m041_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-1,nyglbl-1,1,1]
            call d2fdyz_kernel_lh_zdir_corner_eqO_host("d2fdyz_lh_zdir_corner_eqO", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p014_m030_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-4,nyglbl-2,1,1]
            call d2fdyz_kernel_lh_zdir_corner_eqP_host("d2fdyz_lh_zdir_corner_eqP", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p024_m020_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-4,nyglbl-2,2,2]
            call d2fdyz_kernel_lh_zdir_corner_eqQ_host("d2fdyz_lh_zdir_corner_eqQ", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p023_m021_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl,nyglbl,3,5]
            call d2fdyz_kernel_lh_zdir_corner_eqR_host("d2fdyz_lh_zdir_corner_eqR", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p002_m042_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-1,nyglbl-1,3,5]
            call d2fdyz_kernel_lh_zdir_corner_eqS_host("d2fdyz_lh_zdir_corner_eqS", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p012_m032_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-4,nyglbl-2,3,5]
            call d2fdyz_kernel_lh_zdir_corner_eqT_host("d2fdyz_lh_zdir_corner_eqT", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p044_m044_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_gbl(nyglbl, 1, "integer(kind=4)", OPS_READ), &
                              & ops_arg_idx())

            END IF

        END IF



        IF(nendzr == nbound) THEN

            rangexyz = [1,nxglbl,jstart,jfinis,nzglbl-4,nzglbl-4]
            call d2fdyz_kernel_rh_zdir_8th_centred_host("d2fdyz_rh_zdir_8th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p044_m044_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,jstart,jfinis,nzglbl-3,nzglbl-3]
            call d2fdyz_kernel_rh_zdir_6th_centred_host("d2fdyz_rh_zdir_6th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p033_m033_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,jstart,jfinis,nzglbl-2,nzglbl-2]
            call d2fdyz_kernel_rh_zdir_4th_centred_host("d2fdyz_rh_zdir_4th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p022_m022_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,jstart,jfinis,nzglbl-1,nzglbl-1]
            call d2fdyz_kernel_rh_zdir_4th_mixed_host("d2fdyz_rh_zdir_4th_mixed", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p021_m023_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,jstart,jfinis,nzglbl,nzglbl]
            call d2fdyz_kernel_rh_zdir_4th_onesided_host("d2fdyz_rh_zdir_4th_onesided", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p020_m024_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))


            IF(nendyl == nbound)THEN
            rangexyz = [1,nxglbl,1,1,nzglbl,nzglbl]
            call d2fdyz_kernel_rh_zdir_corner_eqA_host("d2fdyz_rh_zdir_corner_eqA", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p040_p004_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,2,2,nzglbl-1,nzglbl-1]
            call d2fdyz_kernel_rh_zdir_corner_eqB_host("d2fdyz_rh_zdir_corner_eqB", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p030_m010_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,1,1,nzglbl-1,nzglbl-1]
            call d2fdyz_kernel_rh_zdir_corner_eqC_host("d2fdyz_rh_zdir_corner_eqC", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p041_p003_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,2,2,nzglbl,nzglbl]
            call d2fdyz_kernel_rh_zdir_corner_eqD_host("d2fdyz_rh_zdir_corner_eqD", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p030_m014_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,3,5,nzglbl-1,nzglbl-1]
            call d2fdyz_kernel_rh_zdir_corner_eqE_host("d2fdyz_rh_zdir_corner_eqE", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p021_m023_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,3,5,nzglbl,nzglbl]
            call d2fdyz_kernel_rh_zdir_corner_eqF_host("d2fdyz_rh_zdir_corner_eqF", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p020_m024_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,1,1,nzglbl-4,nzglbl-2]
            call d2fdyz_kernel_rh_zdir_corner_eqG_host("d2fdyz_rh_zdir_corner_eqG", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p042_m002_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,2,2,nzglbl-4,nzglbl-2]
            call d2fdyz_kernel_rh_zdir_corner_eqH_host("d2fdyz_rh_zdir_corner_eqH", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p032_m012_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,3,5,nzglbl-4,nzglbl-2]
            call d2fdyz_kernel_rh_zdir_corner_eqI_host("d2fdyz_rh_zdir_corner_eqI", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p044_m044_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_gbl(nzglbl, 1, "integer(kind=4)", OPS_READ), &
                              & ops_arg_idx())

            END IF


            IF(nendyr == nbound) THEN
            rangexyz = [1,nxglbl,nyglbl,nyglbl,nzglbl,nzglbl]
            call d2fdyz_kernel_rh_zdir_corner_eqL_host("d2fdyz_rh_zdir_corner_eqL", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p000_m044_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-1,nyglbl-1,nzglbl-1,nzglbl-1]
            call d2fdyz_kernel_rh_zdir_corner_eqM_host("d2fdyz_rh_zdir_corner_eqM", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p011_m033_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl,nyglbl,nzglbl-1,nzglbl-1]
            call d2fdyz_kernel_rh_zdir_corner_eqN_host("d2fdyz_rh_zdir_corner_eqN", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p001_m043_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-1,nyglbl-1,nzglbl,nzglbl]
            call d2fdyz_kernel_rh_zdir_corner_eqO_host("d2fdyz_rh_zdir_corner_eqO", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p010_m034_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-4,nyglbl-2,nzglbl-1,nzglbl-1]
            call d2fdyz_kernel_rh_zdir_corner_eqP_host("d2fdyz_rh_zdir_corner_eqP", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p021_m023_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-4,nyglbl-2,nzglbl,nzglbl]
            call d2fdyz_kernel_rh_zdir_corner_eqQ_host("d2fdyz_rh_zdir_corner_eqQ", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p020_m024_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl,nyglbl,nzglbl-4,nzglbl-2]
            call d2fdyz_kernel_rh_zdir_corner_eqR_host("d2fdyz_rh_zdir_corner_eqR", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p002_m042_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-1,nyglbl-1,nzglbl-4,nzglbl-2]
            call d2fdyz_kernel_rh_zdir_corner_eqS_host("d2fdyz_rh_zdir_corner_eqS", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p012_m032_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,nxglbl,nyglbl-4,nyglbl-2,nzglbl-4,nzglbl-2]
            call d2fdyz_kernel_rh_zdir_corner_eqT_host("d2fdyz_rh_zdir_corner_eqT", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p044_m044_mixed_yz, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_gbl(nyglbl, 1, "integer(kind=4)", OPS_READ), &
                              & ops_arg_gbl(nzglbl, 1, "integer(kind=4)", OPS_READ), &
                              & ops_arg_idx())

            END IF

        END IF



        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call d2fdyz_kernel_scaling_host("d2fdyz_scaling", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_RW))
    END IF


END SUBROUTINE d2fdyz
