!
! auto-generated by ops_fortran.py
!
SUBROUTINE d2fdx2(functn,fderiv)
 use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use D2FDX2_KERNEL_MAIN_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga













    TYPE(ops_dat) :: functn, fderiv


    integer(kind=4) :: rangexyz(6)






    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call d2fdx2_kernel_main_host("d2fdx2_main_scheme", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(functn, 1, s3d_p500_to_m500_x, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(nxglbl, 1, "integer(kind=4)", OPS_READ), &
                      & ops_arg_gbl(nendxl, 1, "integer(kind=4)", OPS_READ), &
                      & ops_arg_gbl(nendxr, 1, "integer(kind=4)", OPS_READ), &
                      & ops_arg_gbl(nbound, 1, "integer(kind=4)", OPS_READ), &
                      & ops_arg_idx())


END SUBROUTINE d2fdx2
