!
! auto-generated by ops_fortran.py
!
SUBROUTINE d2fdz2(functn,fderiv)
 use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use D2FDZ2_KERNEL_NULL_MODULE
  use D2FDZ2_KERNEL_MAIN_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga














    TYPE(ops_dat) :: functn, fderiv


    integer :: rangexyz(6)



    IF (nzglbl == 1) THEN
        rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
        call d2fdz2_kernel_null_host("d2fdz2_null", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(8)", OPS_WRITE))

    ELSE



        rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
        call d2fdz2_kernel_main_host("d2fdz2_main_scheme", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(functn, 1, s3d_p005_to_m005_z, "real(8)", OPS_READ), &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(8)", OPS_WRITE), &
                          & ops_arg_gbl(nzglbl, 1, "integer", OPS_READ), &
                          & ops_arg_gbl(nendzl, 1, "integer", OPS_READ), &
                          & ops_arg_gbl(nendzr, 1, "integer", OPS_READ), &
                          & ops_arg_gbl(nbound, 1, "integer", OPS_READ), &
                          & ops_arg_idx())

    END IF


END SUBROUTINE d2fdz2
