!
! auto-generated by ops_fortran.py
!
SUBROUTINE d2fdy2(functn,fderiv)
 use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use D2FDY2_KERNEL_NULL_MODULE
  use D2FDY2_KERNEL_MAIN_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga













    TYPE(ops_dat) :: functn, fderiv


    integer(kind=4) :: rangexyz(6)



    IF (nyglbl == 1) THEN
        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call d2fdy2_kernel_null_host("d2fdy2_null", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

    ELSE



        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call d2fdy2_kernel_main_host("d2fdy2_main_scheme", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(functn, 1, s3d_p050_to_m050_y, "real(kind=8)", OPS_READ), &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_gbl(nyglbl, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(nendyl, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(nendyr, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(nbound, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_idx())

    END IF


END SUBROUTINE d2fdy2
