!
! auto-generated by ops_fortran.py
!
SUBROUTINE d2fdxy(functn,fderiv)
 use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use D2FDXY_KERNEL_NULL_MODULE
  use D2FDXY_KERNEL_INTERIOR_MODULE
  use D2FDXY_KERNEL_LH_XDIR_4TH_ONESIDED_MODULE
  use D2FDXY_KERNEL_LH_XDIR_4TH_MIXED_MODULE
  use D2FDXY_KERNEL_LH_XDIR_4TH_CENTERED_MODULE
  use D2FDXY_KERNEL_LH_XDIR_6TH_CENTERED_MODULE
  use D2FDXY_KERNEL_LH_XDIR_8TH_CENTERED_MODULE
  use D2FDXY_KERNEL_RH_XDIR_8TH_CENTERED_MODULE
  use D2FDXY_KERNEL_RH_XDIR_6TH_CENTERED_MODULE
  use D2FDXY_KERNEL_RH_XDIR_4TH_CENTERED_MODULE
  use D2FDXY_KERNEL_RH_XDIR_4TH_MIXED_MODULE
  use D2FDXY_KERNEL_RH_XDIR_4TH_ONESIDED_MODULE
  use D2FDXY_KERNEL_LH_YDIR_4TH_ONESIDED_MODULE
  use D2FDXY_KERNEL_LH_YDIR_4TH_MIXED_MODULE
  use D2FDXY_KERNEL_LH_YDIR_4TH_CENTERED_MODULE
  use D2FDXY_KERNEL_LH_YDIR_6TH_CENTERED_MODULE
  use D2FDXY_KERNEL_LH_YDIR_8TH_CENTERED_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQA_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQB_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQC_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQD_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQE_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQF_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQG_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQH_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQI_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQL_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQM_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQN_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQO_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQP_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQQ_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQR_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQS_MODULE
  use D2FDXY_KERNEL_LH_YDIR_CORNER_EQT_MODULE
  use D2FDXY_KERNEL_RH_YDIR_8TH_CENTERED_MODULE
  use D2FDXY_KERNEL_RH_YDIR_6TH_CENTERED_MODULE
  use D2FDXY_KERNEL_RH_YDIR_4TH_CENTERED_MODULE
  use D2FDXY_KERNEL_RH_YDIR_4TH_MIXED_MODULE
  use D2FDXY_KERNEL_RH_YDIR_4TH_ONESIDED_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQA_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQB_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQC_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQD_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQE_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQF_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQG_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQH_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQI_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQL_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQM_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQN_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQO_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQP_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQQ_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQR_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQS_MODULE
  use D2FDXY_KERNEL_RH_YDIR_CORNER_EQT_MODULE
  use D2FDXY_KERNEL_SCALING_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga













    TYPE(ops_dat) :: functn, fderiv


    integer(kind=4) :: rangexyz(6)
    integer(kind=4) :: istart,ifinis,jstart,jfinis



    IF (nxglbl==1 .or. nyglbl==1) THEN
        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call d2fdxy_kernel_null_host("d2fdxy_null", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

    ELSE



        istart = 1
        ifinis = nxglbl
        jstart = 1
        jfinis = nyglbl
        IF(nendxl == nbound) istart = 6
        IF(nendxr == nbound) ifinis = nxglbl-5
        IF(nendyl == nbound) jstart = 6
        IF(nendyr == nbound) jfinis = nyglbl-5



        rangexyz = [istart,ifinis,jstart,jfinis,1,nzglbl]
        call d2fdxy_kernel_interior_host("d2fdxy_interior", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(functn, 1, s3d_p550_m550_mixed_xy, "real(kind=8)", OPS_READ), &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))



        IF(nendxl == nbound) THEN


            rangexyz = [1,1,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_lh_xdir_4th_onesided_host("d2fdxy_lh_xdir_4th_onesided", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p420_m020_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [2,2,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_lh_xdir_4th_mixed_host("d2fdxy_lh_xdir_4th_mixed", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p320_m120_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [3,3,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_lh_xdir_4th_centered_host("d2fdxy_lh_xdir_4th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p220_m220_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [4,4,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_lh_xdir_6th_centered_host("d2fdxy_lh_xdir_6th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p330_m330_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [5,5,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_lh_xdir_8th_centered_host("d2fdxy_lh_xdir_8th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p440_m440_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

        END IF


        IF(nendxr == nbound) THEN


            rangexyz = [nxglbl-4,nxglbl-4,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_rh_xdir_8th_centered_host("d2fdxy_rh_xdir_8th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p440_m440_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-3,nxglbl-3,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_rh_xdir_6th_centered_host("d2fdxy_rh_xdir_6th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p330_m330_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-2,nxglbl-2,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_rh_xdir_4th_centered_host("d2fdxy_rh_xdir_4th_centred", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p220_m220_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-1,nxglbl-1,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_rh_xdir_4th_mixed_host("d2fdxy_rh_xdir_4th_mixed", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p120_m320_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl,nxglbl,jstart,jfinis,1,nzglbl]
            call d2fdxy_kernel_rh_xdir_4th_onesided_host("d2fdxy_rh_xdir_4th_onesided", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p020_m420_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

        END IF



        IF(nendyl == nbound) THEN

            rangexyz = [istart,ifinis,1,1,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_4th_onesided_host("d2fdxy_lh_ydir_4th_onesided", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p240_m200_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [istart,ifinis,2,2,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_4th_mixed_host("d2fdxy_lh_ydir_4th_mixed", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p230_m210_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [istart,ifinis,3,3,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_4th_centered_host("d2fdxy_lh_ydir_4th_centered", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p220_m220_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [istart,ifinis,4,4,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_6th_centered_host("d2fdxy_lh_ydir_6th_centered", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p330_m330_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [istart,ifinis,5,5,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_8th_centered_host("d2fdxy_lh_ydir_8th_centered", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p440_m440_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))


            IF(nendxl == nbound) THEN
            rangexyz = [1,1,1,1,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqA_host("d2fdxy_lh_ydir_corner_eqA", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p440_p000_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [2,2,2,2,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqB_host("d2fdxy_lh_ydir_corner_eqB", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p330_m110_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,1,2,2,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqC_host("d2fdxy_lh_ydir_corner_eqC", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p430_m010_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [2,2,1,1,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqD_host("d2fdxy_lh_ydir_corner_eqD", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p340_m100_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [3,5,1,1,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqE_host("d2fdxy_lh_ydir_corner_eqE", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p240_m200_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [3,5,2,2,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqF_host("d2fdxy_lh_ydir_corner_eqF", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p230_m210_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,1,3,5,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqG_host("d2fdxy_lh_ydir_corner_eqG", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p420_m020_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [2,2,3,5,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqH_host("d2fdxy_lh_ydir_corner_eqH", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p320_m120_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [3,5,3,5,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqI_host("d2fdxy_lh_ydir_corner_eqI", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p440_m440_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_idx())

            END IF


            IF(nendxr == nbound) THEN
            rangexyz = [nxglbl,nxglbl,1,1,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqL_host("d2fdxy_lh_ydir_corner_eqL", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p040_m400_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-1,nxglbl-1,2,2,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqM_host("d2fdxy_lh_ydir_corner_eqM", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p100_m300_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl,nxglbl,2,2,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqN_host("d2fdxy_lh_ydir_corner_eqN", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p030_m410_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-1,nxglbl-1,1,1,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqO_host("d2fdxy_lh_ydir_corner_eqO", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p140_m300_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-4,nxglbl-2,1,1,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqP_host("d2fdxy_lh_ydir_corner_eqP", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p240_m200_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-4,nxglbl-2,2,2,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqQ_host("d2fdxy_lh_ydir_corner_eqQ", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p230_m210_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl,nxglbl,3,5,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqR_host("d2fdxy_lh_ydir_corner_eqR", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p020_m420_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-1,nxglbl-1,3,5,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqS_host("d2fdxy_lh_ydir_corner_eqS", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p120_m320_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-4,nxglbl-2,3,5,1,nzglbl]
            call d2fdxy_kernel_lh_ydir_corner_eqT_host("d2fdxy_lh_ydir_corner_eqT", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p440_m440_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_gbl(nxglbl, 1, "integer(kind=4)", OPS_READ), &
                              & ops_arg_idx())

            END IF

        END IF



        IF(nendyr == nbound) THEN

            rangexyz = [istart,ifinis,nyglbl-4,nyglbl-4,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_8th_centered_host("d2fdxy_rh_ydir_8th_centered", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p440_m440_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [istart,ifinis,nyglbl-3,nyglbl-3,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_6th_centered_host("d2fdxy_rh_ydir_6th_centered", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p330_m330_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [istart,ifinis,nyglbl-2,nyglbl-2,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_4th_centered_host("d2fdxy_rh_ydir_4th_centered", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p220_m220_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [istart,ifinis,nyglbl-1,nyglbl-1,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_4th_mixed_host("d2fdxy_rh_ydir_4th_mixed", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p210_m230_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [istart,ifinis,nyglbl,nyglbl,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_4th_onesided_host("d2fdxy_rh_ydir_4th_onesided", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p200_m240_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))


            IF(nendxl == nbound) THEN
            rangexyz = [1,1,nyglbl,nyglbl,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqA_host("d2fdxy_rh_ydir_corner_eqA", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p400_p040_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [2,2,nyglbl-1,nyglbl-1,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqB_host("d2fdxy_rh_ydir_corner_eqB", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p300_m100_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,1,nyglbl-1,nyglbl-1,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqC_host("d2fdxy_rh_ydir_corner_eqC", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p410_p030_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [2,2,nyglbl,nyglbl,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqD_host("d2fdxy_rh_ydir_corner_eqD", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p300_m140_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [3,5,nyglbl-1,nyglbl-1,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqE_host("d2fdxy_rh_ydir_corner_eqE", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p210_m230_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [3,5,nyglbl,nyglbl,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqF_host("d2fdxy_rh_ydir_corner_eqF", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p200_m240_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [1,1,nyglbl-4,nyglbl-2,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqG_host("d2fdxy_rh_ydir_corner_eqG", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p420_m020_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [2,2,nyglbl-4,nyglbl-2,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqH_host("d2fdxy_rh_ydir_corner_eqH", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p320_m120_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [3,5,nyglbl-4,nyglbl-2,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqI_host("d2fdxy_rh_ydir_corner_eqI", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p440_m440_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_gbl(nyglbl, 1, "integer(kind=4)", OPS_READ), &
                              & ops_arg_idx())

            END IF


            IF(nendxr == nbound) THEN
            rangexyz = [nxglbl,nxglbl,nyglbl,nyglbl,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqL_host("d2fdxy_rh_ydir_corner_eqL", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p000_m440_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-1,nxglbl-1,nyglbl-1,nyglbl-1,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqM_host("d2fdxy_rh_ydir_corner_eqM", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p110_m330_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl,nxglbl,nyglbl-1,nyglbl-1,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqN_host("d2fdxy_rh_ydir_corner_eqN", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p010_m430_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-1,nxglbl-1,nyglbl,nyglbl,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqO_host("d2fdxy_rh_ydir_corner_eqO", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p100_m340_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-4,nxglbl-2,nyglbl-1,nyglbl-1,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqP_host("d2fdxy_rh_ydir_corner_eqP", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p210_m230_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-4,nxglbl-2,nyglbl,nyglbl,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqQ_host("d2fdxy_rh_ydir_corner_eqQ", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p200_m240_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl,nxglbl,nyglbl-4,nyglbl-2,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqR_host("d2fdxy_rh_ydir_corner_eqR", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p020_m420_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-1,nxglbl-1,nyglbl-4,nyglbl-2,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqS_host("d2fdxy_rh_ydir_corner_eqS", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p120_m320_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE))

            rangexyz = [nxglbl-4,nxglbl-2,nyglbl-4,nyglbl-2,1,nzglbl]
            call d2fdxy_kernel_rh_ydir_corner_eqT_host("d2fdxy_rh_ydir_corner_eqT", senga_grid, 3, rangexyz, &
                              & ops_arg_dat(functn, 1, s3d_p440_m440_mixed_xy, "real(kind=8)", OPS_READ), &
                              & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                              & ops_arg_gbl(nxglbl, 1, "integer(kind=4)", OPS_READ), &
                              & ops_arg_gbl(nyglbl, 1, "integer(kind=4)", OPS_READ), &
                              & ops_arg_idx())

            END IF

        END IF



        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call d2fdxy_kernel_scaling_host("d2fdxy_scaling", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(fderiv, 1, s3d_000, "real(kind=8)", OPS_RW))

    END IF


END SUBROUTINE d2fdxy






