!
! auto-generated by ops_fortran.py
!
SUBROUTINE espini

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_espect
    use com_senga
    use com_ops_senga

















    real(kind=8) :: ten
    PARAMETER(ten = 10.0_8)


    EXTERNAL espect,espovk,espksq


    real(kind=8) :: tenrgy,tinscl,tdisip
    real(kind=8) :: speclo,spechi
    real(kind=8) :: argmnt

    real(kind=8) :: viscos,viskin,tkolmo,taylor,rtin,dvrin
    integer :: imodes,nmodes

    integer :: ispec




    const0 = sparam(1)
    ck0 = sparam(2)
    ovk0 = one/ck0
    covk0 = const0/ck0



    IF(iproc == 0)THEN

        WRITE(ncrept,*)
        WRITE(ncrept,*)'Energy spectrum function data'
        WRITE(ncrept,*)'-----------------------------'
        WRITE(ncrept,*)


        nmodes = ngzmax/2


        WRITE(ncrept,*)'spectrum function:'
        WRITE(ncrept,*)'mode       k          E(k)'
        DO imodes = 0, nmodes

            argmnt = REAL(imodes,kind=8)
            WRITE(ncrept,'(I5,2(1PE12.4))')imodes,argmnt,espect(argmnt)
        END DO
        WRITE(ncrept,*)


        speclo = zero

        spechi = REAL(nmodes,kind=8)


        call integf(espect,speclo,spechi,tenrgy)

        call integf(espovk,speclo,spechi,tinscl)

        call integf(espksq,speclo,spechi,tdisip)



        WRITE(ncrept,*)'raw integrals:'
        WRITE(ncrept,*)'energy, length scale, dissipation'
        WRITE(ncrept,'(3(1PE12.4))')tenrgy,tinscl,tdisip
        WRITE(ncrept,*)



        tinscl = tinscl*three/tenrgy/two/two/two
        tdisip = two*two*two*pi*pi*tdisip
        WRITE(ncrept,*)'scaled values:'
        WRITE(ncrept,*)'energy, length scale, dissipation/viscosity:'
        WRITE(ncrept,'(3(1PE12.4))')tenrgy,tinscl,tdisip
        WRITE(ncrept,*)


        tinscl = tinscl*xgdlen
        tdisip = tdisip/(xgdlen*xgdlen)
        WRITE(ncrept,*)'dimensional values:'
        WRITE(ncrept,*)'energy, length scale, dissipation/viscosity:'
        WRITE(ncrept,'(3(1PE12.4))')tenrgy,tinscl,tdisip
        WRITE(ncrept,*)


        viscos = alamda*EXP(rlamda*LOG(trin))
        viscos = viscos*prantl

        rtin = zero
        DO ispec = 1,nspec
            rtin = rtin + rgspec(ispec)*yrin(ispec)
        END DO
        rtin = rtin*trin
        dvrin = prin/rtin
        viskin = viscos/dvrin

        WRITE(ncrept,*)'viscosities: dynamic, kinematic:'
        WRITE(ncrept,'(2(1PE12.4))')viscos,viskin
        WRITE(ncrept,*)

        tdisip = tdisip*viskin
        WRITE(ncrept,*)'energy, length scale, dissipation:'
        WRITE(ncrept,'(3(1PE12.4))')tenrgy,tinscl,tdisip
        WRITE(ncrept,*)


        taylor = ten*viskin*tenrgy/tdisip
        taylor = SQRT(taylor)

        tkolmo = viskin*viskin*viskin/tdisip
        tkolmo = SQRT(SQRT(tkolmo))
        WRITE(ncrept,*)'length scales: int, Taylor, Kolmo:'
        WRITE(ncrept,'(3(1PE12.4))')tinscl,taylor,tkolmo
        WRITE(ncrept,*)

        WRITE(ncrept,*)'domain/length scale ratios: int, Taylor, Kolmo:'
        WRITE(ncrept,'(3(1PE12.4))')xgdlen/tinscl,xgdlen/taylor, xgdlen/tkolmo
        WRITE(ncrept,*)


        WRITE(ncrept,*)'------------------------------------'
        WRITE(ncrept,*)

    END IF


END SUBROUTINE espini
