!
! auto-generated by ops_fortran.py
!
SUBROUTINE flamin

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use FLAMIN_KERNEL_SET_REACTION_VAR_MODULE
  use FLAMIN_KERNEL_EQA_MODULE
  use SET_ZERO_KERNEL_MD_MODULE
  use FLAMIN_KERNEL_EQB_MODULE
  use FLAMIN_KERNEL_EQC_MODULE
  use FLAMIN_KERNEL_EQD_MODULE
  use SET_ZERO_KERNEL_MODULE
  use FLAMIN_KERNEL_EQE_MODULE
  use FLAMIN_KERNEL_EQF_MODULE
  use FLAMIN_KERNEL_EQG_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















    real(kind=8) :: clocat,cthick
    PARAMETER(clocat = 0.0025_8, cthick = 0.0005_8)





    real(kind=8) :: erfunc
    EXTERNAL erfunc


    real(kind=8) :: yrinr(nspcmx),yrinp(nspcmx)
    real(kind=8) :: trinr,trinp
    real(kind=8) :: deltag,xcoord,argmnt
    real(kind=8) :: flxmas
    integer :: icproc
    integer :: ix
    integer :: ic,jc,kc
    integer :: ispec
    integer :: rangexyz(6)






    trinr = trin

    trinp = 2200.0_8



    yrinr(1) = 0.0199886_8
    yrinr(2) = 0.2286239_8
    DO ispec = 3,nspm1
        yrinr(ispec) = zero
    END DO

    yrinr(nspec) = zero
    DO ispec = 1,nspm1
        yrinr(nspec) = yrinr(nspec) + yrinr(ispec)
    END DO
    yrinr(nspec) = one - yrinr(nspec)

    yrinp(1) = zero
    yrinp(2) = 0.0685323_8
    yrinp(3) = 0.1798974_8
    DO ispec = 4,nspm1
        yrinp(ispec) = zero
    END DO
    yrinp(nspec) = zero
    DO ispec = 1,nspm1
        yrinp(nspec) = yrinp(nspec) + yrinp(ispec)
    END DO
    yrinp(nspec) = one - yrinp(nspec)

    IF(iproc == 0) THEN

        WRITE(ncrept,*)
        WRITE(ncrept,*)'FLAMIN: reactant mass fractions:'
        DO ispec = 1,nspec
            WRITE(ncrept,'(I5,1PE15.7)')ispec,yrinr(ispec)
        END DO
        WRITE(ncrept,*)

        WRITE(ncrept,*)'FLAMIN: product mass fractions:'
        DO ispec = 1,nspec
            WRITE(ncrept,'(I5,1PE15.7)')ispec,yrinp(ispec)
        END DO
        WRITE(ncrept,*)

        WRITE(ncrept,*)'FLAMIN: reactant and product temperatures:'
        WRITE(ncrept,'(2(1PE15.7))')trinr,trinp
        WRITE(ncrept,*)

    END IF


    deltag = xgdlen/(REAL(nxglbl-1,kind=8))


    rangexyz = (/1,nxglbl,1,1,1,1/)
    call flamin_kernel_set_reaction_var_host("SIMPLE 1D LEFT-FACING ERROR FUNCTION PROFILE", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_crin, 1, s3d_000_strid3d_x, "real(8)", OPS_WRITE), &
                      & ops_arg_gbl(deltag, 1, "real(8)", OPS_READ), &
                      & ops_arg_gbl(clocat, 1, "real(8)", OPS_READ), &
                      & ops_arg_gbl(cthick, 1, "real(8)", OPS_READ), &
                      & ops_arg_idx())


    DO ispec = 1, nspm1
        rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
        call flamin_kernel_eqA_host("SET SPECIES MASS FRACTION PROFILES", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_yrun, 9, s3d_000, "real(8)", OPS_WRITE), &
                          & ops_arg_dat(d_crin, 1, s3d_000_strid3d_x, "real(8)", OPS_READ), &
                          & ops_arg_gbl(yrinr(ispec), 1, "real(8)", OPS_READ), &
                          & ops_arg_gbl(yrinp(ispec), 1, "real(8)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer", OPS_READ))

    END DO

    rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
    call set_zero_kernel_MD_host("set zero multi-dim", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_yrun, 9, s3d_000, "real(8)", OPS_WRITE), &
                      & ops_arg_gbl(nspec, 1, "integer", OPS_READ))

    DO ispec = 1, nspm1
        rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
        call flamin_kernel_eqB_host("A_multidim = A_multidim + A_multidim", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_yrun, 9, s3d_000, "real(8)", OPS_RW), &
                          & ops_arg_gbl(ispec, 1, "integer", OPS_READ), &
                          & ops_arg_gbl(nspec, 1, "integer", OPS_READ))

    END DO

    rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
    call flamin_kernel_eqC_host("A_multidim = 1.0 - A_multidim", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_yrun, 9, s3d_000, "real(8)", OPS_RW), &
                      & ops_arg_gbl(nspec, 1, "integer", OPS_READ))


    rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
    call flamin_kernel_eqD_host("A = var1 + B_xdimonly*(var2-var1)", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_trun, 1, s3d_000, "real(8)", OPS_WRITE), &
                      & ops_arg_dat(d_crin, 1, s3d_000_strid3d_x, "real(8)", OPS_READ), &
                      & ops_arg_gbl(trinr, 1, "real(8)", OPS_READ), &
                      & ops_arg_gbl(trinp, 1, "real(8)", OPS_READ))



    rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
    call set_zero_kernel_host("set zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_store1, 1, s3d_000, "real(8)", OPS_WRITE))

    DO ispec = 1,nspec
        rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
        call flamin_kernel_eqE_host("A = A + var*B_multidim", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_store1, 1, s3d_000, "real(8)", OPS_INC), &
                          & ops_arg_dat(d_yrun, 9, s3d_000, "real(8)", OPS_READ), &
                          & ops_arg_gbl(rgspec(ispec), 1, "real(8)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer", OPS_READ))

    END DO

    rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
    call flamin_kernel_eqF_host("A = var/(B*C)", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(8)", OPS_WRITE), &
                      & ops_arg_dat(d_store1, 1, s3d_000, "real(8)", OPS_READ), &
                      & ops_arg_dat(d_trun, 1, s3d_000, "real(8)", OPS_READ), &
                      & ops_arg_gbl(prin, 1, "real(8)", OPS_READ))


    flxmas = drin*urin
    rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)
    call flamin_kernel_eqG_host("A = var/B", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(8)", OPS_WRITE), &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(8)", OPS_READ), &
                      & ops_arg_gbl(flxmas, 1, "real(8)", OPS_READ))


9000  FORMAT(a)

END SUBROUTINE flamin
