!
! auto-generated by ops_fortran.py
!
SUBROUTINE indata

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use SET_ZERO_KERNEL_MODULE
  use COPY_KERNEL_MODULE
  use MATHS_KERNEL_EQF_MODULE
  use MATHS_KERNEL_EQE_MODULE
  use MATHS_KERNEL_EQD_MODULE
  use MATHS_KERNEL_EQK_MODULE
  use MATHS_KERNEL_EQV_MODULE
  use MATHS_KERNEL_EQU_MODULE
  use SET_ZERO_KERNEL_INT_MODULE
  use MATHS_KERNEL_EQBO_MODULE
  use MATHS_KERNEL_EQBP_MODULE
  use MATHS_KERNEL_EQAU_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga



















#ifdef HDF5
    use hdf5io
#endif
    use com_espect



    CHARACTER (LEN=10) :: pncont,pnchem,pndiff,pnradn
    CHARACTER (LEN=11) :: pnrept,pnstat,pndmpi,pndmpo
    CHARACTER (LEN=4) :: pnxdat,pnxres
    PARAMETER(pncont = 'input/cont', pnchem = 'input/chem',  &
              pndiff = 'input/diff', pnradn = 'input/radn',  &
              pnrept = 'output/rept', pnstat = 'output/stat',  &
              pndmpi = 'output/dmpi', pndmpo = 'output/dmpo',  &
              pnxdat = '.dat', pnxres = '.res')

    integer(kind=4), parameter :: lenlin = 79

    real(kind=8), parameter :: tttol = 0.0010_8


    real(kind=8) :: dyrin(nspcmx)
    real(kind=8) :: ctrans(nspcmx,4)
    real(kind=8) :: dtrans(nspcmx)
    real(kind=8) :: rtin,durin,dvrin,dwrin,derin
    real(kind=8) :: ttemp(5),ttold(5)
    real(kind=8) :: fornow,tmplog
    real(kind=8) :: combo1,combo2,combo3
    integer(kind=4) :: iindex,ipower,icoef1,icoef2
    integer(kind=4) :: ic,jc,kc,ispec,istep,itint,icp
    integer(kind=4) :: jspec,ncount
    integer(kind=4) :: nxdmax,nydmax,nzdmax,ndspec
    integer(kind=4) :: rangexyz(6)
    CHARACTER (LEN=132) :: strout
    CHARACTER (LEN=79) :: clstar,cldash
    CHARACTER (LEN=10) :: streac
    CHARACTER (LEN=5) :: strstp
    CHARACTER (LEN=4) :: straro
    CHARACTER (LEN=1) :: strcof

    CHARACTER (LEN=6) :: pnproc
    CHARACTER (LEN=1) :: pnflag
    LOGICAL :: fxdump
    LOGICAL :: flgreq




#ifdef HDF5
    call hdf5_init
#endif


    nccont = 1
    ncchem = 2
    ncdiff = 3
    ncradn = 4
    ncdmpo = 7
    ncrept = 8
    ncstat = 9

    WRITE(pnproc,'(I6.6)')iproc
    fncont = pncont//pnxdat
    fnchem = pnchem//pnxdat
    fndiff = pndiff//pnxdat
    fnradn = pnradn//pnxdat
    fnrept = pnrept//pnxres
    fnstat = pnstat//pnxres
    idflag = 0
    WRITE(pnflag,'(I1)')idflag
    fndmpo(1) = pndmpi//pnproc//pnflag//pnxdat
#ifdef HDF5
    h5_filename(1) = pndmpi//pnflag//".h5"
#endif
    idflag = 1
    WRITE(pnflag,'(I1)')idflag
    fndmpo(2) = pndmpi//pnproc//pnflag//pnxdat
#ifdef HDF5
    h5_filename(2) = pndmpi//pnflag//".h5"
#endif


    call contin



    IF(iproc == 0)THEN

        DO ic = 1,lenlin
            clstar(ic:ic) = '*'
            cldash(ic:ic) = '-'
        END DO

        OPEN(UNIT=ncrept,FILE=fnrept,STATUS='REPLACE',FORM='FORMATTED')

        WRITE(ncrept,9000)clstar
        WRITE(ncrept,9010)
        WRITE(ncrept,9020)
        WRITE(ncrept,9010)
        WRITE(ncrept,9030)
        WRITE(ncrept,9010)
        WRITE(ncrept,9040)
        WRITE(ncrept,9010)
        WRITE(ncrept,9000)clstar
        WRITE(ncrept,*)

        WRITE(ncrept,*)'==========='
        WRITE(ncrept,*)'REPORT FILE'
        WRITE(ncrept,*)'==========='
        WRITE(ncrept,*)

        WRITE(ncrept,9000)cldash

        WRITE(ncrept,*)
        WRITE(ncrept,*)'Domain decomposition data:'
        WRITE(ncrept,*)'-------------------------'
        WRITE(ncrept,*)

        WRITE(ncrept,*)'NXGLBL,NYGLBL,NZGLBL'
        WRITE(ncrept,9200)nxglbl,nyglbl,nzglbl
        WRITE(ncrept,*)

        flgreq = (nxgreq == nxglbl) .AND.(nygreq == nyglbl) .AND.(nzgreq == nzglbl)
        IF(.NOT.flgreq) THEN
            WRITE(ncrept,*)'Warning: INDATA: global domain size mismatch'
            WRITE(ncrept,*)'Required values in control file:'
            WRITE(ncrept,9200)nxgreq,nygreq,nzgreq
            WRITE(ncrept,*)'Global values take precedence'
            WRITE(ncrept,*)
        END IF

        WRITE(ncrept,*)'NXPROC,NYPROC,NZPROC,NPROC'
        WRITE(ncrept,9200)nxproc,nyproc,nzproc,nproc
        WRITE(ncrept,*)
        IF(nproc /= nxproc*nyproc*nzproc) THEN
            WRITE(ncrept,*) 'Warning: INDATA: mismatched total no. of processors'
            WRITE(ncrept,*)
        END IF

        flgreq = (nxpreq == nxproc) .AND.(nypreq == nyproc) .AND.(nzpreq == nzproc)
        IF(.NOT.flgreq) THEN
            WRITE(ncrept,*)'Warning: INDATA: no. of processors mismatch'
            WRITE(ncrept,*)'Required values in control file:'
            WRITE(ncrept,9200)nxpreq,nypreq,nzpreq
            WRITE(ncrept,*)'Global values take precedence'
            WRITE(ncrept,*)
        END IF

        WRITE(ncrept,*)'NXSIZE,NYSIZE,NZSIZE'
        WRITE(ncrept,9200)nxsize,nysize,nzsize
        WRITE(ncrept,*)

        WRITE(ncrept,*)'NPMAPX'
        WRITE(ncrept,9200)(npmapx(ic),ic=0,nxprm1)
        WRITE(ncrept,*)'NPMAPY'
        WRITE(ncrept,9200)(npmapy(ic),ic=0,nyprm1)
        WRITE(ncrept,*)'NPMAPZ'
        WRITE(ncrept,9200)(npmapz(ic),ic=0,nzprm1)

        WRITE(ncrept,*)'--------------------------------'
        WRITE(ncrept,*)
        WRITE(ncrept,9000)cldash


        WRITE(ncrept,*)
        WRITE(ncrept,*)'Initial data:'
        WRITE(ncrept,*)'------------'
        WRITE(ncrept,*)

        WRITE(ncrept,*)'XGDLEN,YGDLEN,ZGDLEN'
        WRITE(ncrept,9400)xgdlen,ygdlen,zgdlen
        WRITE(ncrept,*)

        WRITE(ncrept,*)'TSTEP,NTIME1,NTIME,NSTPSW,NTDUMP,NTREPT,NTSTAT'
        WRITE(ncrept,9300)tstep,ntime1,ntime,nstpsw,ntdump,ntrept,ntstat
        WRITE(ncrept,*)

        WRITE(ncrept,*)'NCDMPI'
        WRITE(ncrept,9200)ncdmpi

        WRITE(ncrept,*)'INTURB, INSEED, SPARAM'
        WRITE(ncrept,9270)inturb,inseed,(sparam(ic),ic=1,nsparm)

        WRITE(ncrept,*)'INFLAM'
        WRITE(ncrept,9200)inflam

        WRITE(ncrept,*)
        WRITE(ncrept,*)'PRIN,TRIN,URIN,VRIN,WRIN'
        WRITE(ncrept,9400)prin,trin,urin,vrin,wrin

        IF(nspreq /= nspcmx) THEN
            WRITE(ncrept,*)'Warning: INDATA: no. of species mismatch'
            WRITE(ncrept,*)'Global value:'
            WRITE(ncrept,9200)nspcmx
            WRITE(ncrept,*)'Required value in control file:'
            WRITE(ncrept,9200)nspreq
            WRITE(ncrept,*)'Global value takes precedence'
            WRITE(ncrept,*)
        END IF

        WRITE(ncrept,*)'ISPEC,YRIN'
        DO ispec = 1,nspec
            WRITE(ncrept,9450)ispec,yrin(ispec)
        END DO

        fornow = zero
        DO ispec = 1,nspec
            fornow = fornow + yrin(ispec)
        END DO
        IF(ABS(fornow-one) > ytoler) THEN
            WRITE(ncrept,*)  &
                        'Warning: INDATA: initial mass fractions do not sum to unity'
            WRITE(ncrept,*)
        END IF

        WRITE(ncrept,*)
        WRITE(ncrept,*)'NGBCXL,NGBCXR,NGBCYL,NGBCYR,NGBCZL,NGBCZR'
        WRITE(ncrept,9250)ngbcxl,ngbcxr,ngbcyl,ngbcyr,ngbczl,ngbczr

        WRITE(ncrept,*)
        WRITE(ncrept,*)'End of initial data'
        WRITE(ncrept,*)'-------------------'
        WRITE(ncrept,*)
        WRITE(ncrept,9000)cldash

    END IF



    call chemin


    IF(iproc == 0) THEN


        WRITE(ncrept,*)
        WRITE(ncrept,*)'Chemical data:'
        WRITE(ncrept,*)'-------------'
        WRITE(ncrept,*)

        WRITE(ncrept,*)'Number of species:'
        WRITE(ncrept,'(I5)')nspec

        IF(nspec /= nspcmx) THEN
            WRITE(ncrept,*)'Warning: INDATA: no. of species mismatch'
            WRITE(ncrept,*)'Global value:'
            WRITE(ncrept,9200)nspcmx
            WRITE(ncrept,*)'Required value in chemical data file:'
            WRITE(ncrept,9200)nspec
            WRITE(ncrept,*)'Chemical data file value takes precedence'
            WRITE(ncrept,*)
        END IF
        WRITE(ncrept,*)'List of species:'
        WRITE(ncrept,*)'  No.  Symbol         Mol. Mass'
        DO ispec = 1,nspec
            WRITE(ncrept,'(I5,3X,A10,3X,1PE12.4)') ispec,spcsym(ispec),wmolar(ispec)
        END DO
        WRITE(ncrept,*)

        WRITE(ncrept,*)'Species thermodynamic data:'
        WRITE(ncrept,'("  Reference pressure: ",1PE12.4)')prefgb
        WRITE(ncrept,*)' Spec.  No of T intervals   ',  &
                    'Interval   T low       T high       No of coeffs'
        DO ispec = 1,nspec
            ic = 1
            WRITE(ncrept,'(I5,6X,I5,9X,I5,8X,2(1PE12.4),I8)') ispec,ntint(ispec),  &
                                 ic,tintlo(ic,ispec),tinthi(ic,ispec),ncofcp(ic,ispec)
            DO ic = 2,ntint(ispec)
                WRITE(ncrept,'(25X,I5,8X,2(1PE12.4),I8)')  &
                                ic,tintlo(ic,ispec),tinthi(ic,ispec),ncofcp(ic,ispec)

            END DO
        END DO
        WRITE(ncrept,*)'Cp coeffs by mass'
        WRITE(ncrept,*)' Spec.  T int.  Coeff no.  Coeff.'
        DO ispec = 1,nspec
            DO ic = 1,ntint(ispec)
                jc = 1
                WRITE(ncrept,'(I5,2X,I5,5X,I5,4X,1PE15.7)')  &
                                ispec,ic,jc,amascp(jc,ic,ispec)
                DO jc = 2,ncofcp(ic,ispec)
                    WRITE(ncrept,'(17X,I5,4X,1PE15.7)')jc,amascp(jc,ic,ispec)
                END DO
            END DO
        END DO

        WRITE(ncrept,*)
        WRITE(ncrept,*)'Mass-specific Cp, Enthalpy, Entropy;', '  Molar Gibbs fn.:'
        WRITE(ncrept,*)' Spec.  T int.  Temp.       Cp',  &
                    '          Enthalpy    Entropy     Molar Gibbs'
        DO ispec = 1,nspec
            DO ic = 1,ntint(ispec)
                DO icp = 1,2

                    IF(icp == 1) ttemp(1) = tintlo(ic,ispec)
                    IF(icp == 2) ttemp(1) = tinthi(ic,ispec)

                    fornow = amascp(ncpoly(ic,ispec),ic,ispec)
                    DO jc = ncpom1(ic,ispec),1,-1
                        fornow = fornow*ttemp(1) + amascp(jc,ic,ispec)
                    END DO
                    ttemp(2) = fornow

                    fornow = amasch(ncpoly(ic,ispec),ic,ispec)
                    DO jc = ncpom1(ic,ispec),1,-1
                        fornow = fornow*ttemp(1) + amasch(jc,ic,ispec)
                    END DO
                    fornow = amasch(ncenth(ic,ispec),ic,ispec) + fornow*ttemp(1)
                    ttemp(3) = fornow

                    fornow = amascs(ncpoly(ic,ispec),ic,ispec)
                    DO jc = ncpom1(ic,ispec),2,-1
                        fornow = fornow*ttemp(1) + amascs(jc,ic,ispec)
                    END DO
                    fornow = amascs(ncenpy(ic,ispec),ic,ispec) + fornow*ttemp(1)  &
                           + amascs(1,ic,ispec)*LOG(ttemp(1))
                    ttemp(4) = fornow


                    fornow = amolgb(ncpoly(ic,ispec),ic,ispec)
                    DO jc = ncpom1(ic,ispec),1,-1
                        fornow = amolgb(jc,ic,ispec) + fornow*ttemp(1)
                    END DO
                    fornow = amolgb(ncenth(ic,ispec),ic,ispec) /ttemp(1)  &
                           - amolgb(ncenpy(ic,ispec),ic,ispec) *LOG(ttemp(1))  &
                           - fornow
                    ttemp(5) = fornow

                    IF(icp == 1) THEN
                        IF(ic == 1) THEN
                            WRITE(ncrept,'(I5,2X,I5,X,"l",X,5(1PE12.4))')  &
                                            ispec,ic,(ttemp(jc),jc=1,5)
                        ELSE
                            WRITE(ncrept,'(7X,I5,X,"l",X,5(1PE12.4))') ic,(ttemp(jc),jc=1,5)
                            DO jc = 1,5
                                IF(ABS(ttold(jc)-ttemp(jc)) > ABS(tttol*ttemp(jc))) THEN
                                    WRITE(ncrept,*)'Warning: INDATA: Mismatched thermo data'
                                    WRITE(ncrept,'(I7,1PE12.4)')jc,ttemp(jc)
                                END IF
                            END DO
                        END IF
                    ELSE
                        WRITE(ncrept,'(7X,I5,X,"h",X,5(1PE12.4))') ic,(ttemp(jc),jc=1,5)
                    END IF

                    IF(icp == 2) THEN
                        DO jc = 1,5
                            ttold(jc) = ttemp(jc)
                        END DO
                    END IF

                END DO
            END DO
        END DO
        WRITE(ncrept,*)


        WRITE(ncrept,*)'Reaction mechanism:'
        WRITE(ncrept,*)'  Number of steps:'
        WRITE(ncrept,'(I5)')nstep
        IF(nstep /= nstpmx) THEN
            WRITE(ncrept,*)'Warning: mismatch in number of steps:'
            WRITE(ncrept,9600)nstep,nstpmx
        END IF
        DO istep = 1,nstep

            WRITE(strstp,'(I5)')istep
            icoef1 = 1
            icoef2 = LEN(strstp) + 3
            strout(icoef1:icoef2) = strstp//'   '
            DO ispec = 1,nrslen(istep)
                streac = spcsym(nrspec(ispec,istep))
                icoef1 = icoef2 + 1
                icoef2 = icoef1 + LEN(streac)
                strout(icoef1:icoef2) = streac
                icoef1 = icoef2 + 1
                icoef2 = icoef1
                strout(icoef1:icoef2) = '+'
            END DO
            IF(mblist(istep) > 0) THEN
                streac = bdysym(mblist(istep))
                icoef1 = icoef2 + 1
                icoef2 = icoef1 + LEN(streac)
                strout(icoef1:icoef2) = streac
            ELSE
                icoef2 = icoef2 - 1
            END IF

            straro = ' => '
            IF(mglist(istep) > 0) straro = ' == '
            icoef1 = icoef2 + 1
            icoef2 = icoef1 + LEN(straro)
            strout(icoef1:icoef2) = straro
            DO ispec = 1,nsslen(istep)
                icp = 0
                DO jspec = 1,nrslen(istep)
                    IF(nrspec(jspec,istep) == nsspec(ispec,istep)) THEN
                        icp = icp + 1
                    END IF
                END DO
                icp = nint(diffmu(ispec,istep)) + icp
                IF(icp > 0) THEN
                    IF(icp > 1) THEN
                        WRITE(strcof,'(I1)')icp
                        icoef1 = icoef2 + 1
                        icoef2 = icoef1 + LEN(strcof)
                        strout(icoef1:icoef2) = strcof
                    END IF
                    streac = spcsym(nsspec(ispec,istep))
                    icoef1 = icoef2 + 1
                    icoef2 = icoef1 + LEN(streac)
                    strout(icoef1:icoef2) = streac
                    icoef1 = icoef2 + 1
                    icoef2 = icoef1
                    strout(icoef1:icoef2) = '+'
                END IF
            END DO

            IF(mblist(istep) > 0) THEN
                streac = bdysym(mblist(istep))
                icoef1 = icoef2 + 1
                icoef2 = icoef1 + LEN(streac)
                strout(icoef1:icoef2) = streac
            ELSE
                icoef2 = icoef2 - 1
            END IF

            WRITE(ncrept,'(A)')strout(1:icoef2)

        END DO

        WRITE(ncrept,*)
        WRITE(ncrept,*)'Reaction parameters A,n,E:'
        DO istep = 1,nstep
            WRITE(ncrept,'(I5,3(2X,1PE12.4))') istep,(rparam(icp,istep),icp=1,3)
        END DO

        IF(nlind > 0) THEN
            WRITE(ncrept,*)
            WRITE(ncrept,*)'Lindemann parameters:'
            DO istep = 1,nstep
                IF(mllist(istep) /= 0) THEN
                    WRITE(ncrept,'(I5,3(2X,1PE12.4))')  &
                                    istep,(rclind(icp,mllist(istep)),icp=1,3)
                END IF
            END DO
        END IF

        WRITE(ncrept,*)
        WRITE(ncrept,*)'Third body efficiencies:'
        DO jspec = 1,nbody
            WRITE(ncrept,'(I5,3X,A10)')jspec,bdysym(jspec)
            DO ispec = 1,nspec
                WRITE(ncrept,'(I5,3X,A10,1PE12.4)')  &
                                ispec,spcsym(ispec),effy3b(ispec,jspec)
            END DO
        END DO

        WRITE(ncrept,*)
        WRITE(ncrept,*)'End of chemical data'
        WRITE(ncrept,*)'--------------------'
        WRITE(ncrept,*)
        WRITE(ncrept,9000)cldash


    END IF



    call diffin

    IF(flmavt) THEN


        IF(iproc == 0) THEN


            WRITE(ncrept,*)
            WRITE(ncrept,*)'Transport data: mixture averaged transport'
            WRITE(ncrept,*)'--------------'
            WRITE(ncrept,*)

            WRITE(ncrept,'(2(1PE12.4))')pdifgb,tdifgb
            WRITE(ncrept,*)
            WRITE(ncrept,*)'Viscosity'
            DO ispec = 1,nspec
                WRITE(ncrept,'(2I5)')ispec,ncovis
                WRITE(ncrept,'(5(1PE15.7))') (viscco(icoeff,ispec),icoeff=1,ncovis)
            END DO
            WRITE(ncrept,*)
            WRITE(ncrept,*)'Thermal conductivity'
            DO ispec = 1,nspec
                WRITE(ncrept,'(2I5)')ispec,ncocon
                WRITE(ncrept,'(5(1PE15.7))') (condco(icoeff,ispec),icoeff=1,ncocon)
            END DO
            WRITE(ncrept,*)
            WRITE(ncrept,*)'Binary diffusion coefficient'
            DO ispec = 1,nspec
                WRITE(ncrept,'(2I5)')ispec,ncodif
                DO jspec = 1,ispec
                    WRITE(ncrept,'(I5,5(1PE15.7))')jspec,  &
                                (diffco(icoeff,jspec,ispec),icoeff=1,ncodif)
                END DO
            END DO
            WRITE(ncrept,*)
            WRITE(ncrept,*)'Thermal diffusion ratio'
            DO ispec = 1,nspec
                WRITE(ncrept,'(2I5)')ispec,ncotdr
                DO jspec = 1,ispec-1
                    WRITE(ncrept,'(I5,5(1PE15.7))')jspec,  &
                                (tdrcco(icoeff,jspec,ispec),icoeff=1,ncotdr)
                END DO
            END DO

            tmplog = LOG(trin/tdifgb)

            rtin = zero
            DO ispec = 1,nspec
                rtin = rtin + rgspec(ispec)*yrin(ispec)
            END DO
            rtin = rtin*trin
            drin = prin/rtin

            DO ispec = 1, nspec
                fornow = viscco(ncovis,ispec)
                DO icp = ncovm1,1,-1
                    fornow = fornow*tmplog + viscco(icp,ispec)
                END DO
                ctrans(ispec,1) = EXP(fornow)
            END DO

            combo1 = zero
            DO ispec = 1, nspec
                combo2 = zero
                DO jspec = 1, nspec
                    fornow = SQRT(ctrans(ispec,1)/ctrans(jspec,1))
                    fornow = one + fornow*wilko2(jspec,ispec)
                    fornow = wilko1(jspec,ispec)*fornow*fornow
                    combo2 = combo2 + yrin(jspec)*ovwmol(jspec)*fornow
                END DO
                fornow = ctrans(ispec,1)/combo2
                combo1 = combo1 + yrin(ispec)*ovwmol(ispec)*fornow

            END DO
            ttemp(1) = combo1

            DO ispec = 1, nspec
                fornow = condco(ncocon,ispec)
                DO icp = ncocm1,1,-1
                    fornow = fornow*tmplog + condco(icp,ispec)
                END DO
                ctrans(ispec,2) = EXP(fornow)
            END DO

            combo1 = zero
            combo2 = zero
            combo3 = zero
            DO ispec = 1, nspec
                fornow = yrin(ispec)*ovwmol(ispec)
                combo1 = combo1 + fornow*ctrans(ispec,2)
                combo2 = combo2 + fornow/ctrans(ispec,2)
                combo3 = combo3 + fornow
            END DO
            combo3 = one/combo3
            combo1 = combo1*combo3
            combo2 = combo2*combo3
            ttemp(2) = half*(combo1 + one/combo2)

            combo2 = zero
            ic = 1
            DO ispec = 1, nspec
                fornow = amascp(ncpoly(ic,ispec),ic,ispec)
                DO jc = ncpom1(ic,ispec),1,-1
                    fornow = fornow*trin + amascp(jc,ic,ispec)
                END DO
                combo1 = fornow
                combo2 = combo2 + yrin(ispec)*combo1
            END DO
            ttemp(3) = combo2

            WRITE(ncrept,*)
            WRITE(ncrept,*)'         Viscosity         Conductivity'
            DO ispec = 1, nspec
                WRITE(ncrept,'(I5,2(1PE18.7))')ispec,ctrans(ispec,1), ctrans(ispec,2)
            END DO
            WRITE(ncrept,*)
            WRITE(ncrept,*) '         Mix viscosity     Conductivity      Prandtl no'
            WRITE(ncrept,'(5X,3(1PE18.7))')ttemp(1),ttemp(2), ttemp(1)*combo2/ttemp(2)

            DO ispec = 1, nspec

                DO jspec = 1, nspec
                    fornow = diffco(ncocon,jspec,ispec)
                    DO icp = ncodm1,1,-1
                        fornow = fornow*tmplog + diffco(icp,jspec,ispec)
                    END DO
                    dtrans(jspec) = EXP(fornow)*pdifgb/prin
                END DO

                combo1 = zero
                combo2 = zero
                combo3 = zero
                DO jspec = 1, nspec
                    fornow = yrin(jspec) + dfctol
                    combo1 = combo1 + fornow
                    combo2 = combo2 + fornow*ovwmol(jspec)/dtrans(jspec)
                    combo3 = combo3 + yrin(jspec)*ovwmol(jspec)
                END DO
                fornow = yrin(ispec) + dfctol
                combo1 = combo1 - fornow
                combo2 = combo2 - fornow*ovwmol(ispec)/dtrans(ispec)
                combo2 = combo2/combo3
                ctrans(ispec,3) = drin*combo1/combo2

            END DO

            tmplog = trin/tdifgb
            DO ispec = 1, nspec

                DO jspec = 1, nspec
                    fornow = tdrcco(ncocon,jspec,ispec)
                    DO icp = ncotm1,1,-1
                        fornow = fornow*tmplog + tdrcco(icp,jspec,ispec)
                    END DO
                    dtrans(jspec) = fornow
                END DO

                combo1 = zero
                combo2 = zero
                DO jspec = 1, nspec
                    fornow = yrin(jspec)*ovwmol(jspec)
                    combo1 = combo1 + fornow*dtrans(jspec)
                    combo2 = combo2 + fornow
                END DO
                ctrans(ispec,4) = combo1/combo2

            END DO

            WRITE(ncrept,*)
            WRITE(ncrept,*)'         Diffusivity       Schmidt No',  &
                           '        Lewis No          Thermal diff'
            DO ispec = 1, nspec
                WRITE(ncrept,'(I5,4(1PE18.7))')ispec,ctrans(ispec,3),  &
                                ttemp(1)/ctrans(ispec,3), ttemp(2)/(ctrans(ispec,3)*ttemp(3)),  &
                                ctrans(ispec,4)
            END DO

            WRITE(ncrept,*)
            WRITE(ncrept,*)'End of transport data'
            WRITE(ncrept,*)'---------------------'
            WRITE(ncrept,*)
            WRITE(ncrept,9000)cldash

        END IF


    ELSE


        IF(iproc == 0) THEN

            WRITE(ncrept,*)
            WRITE(ncrept,*)'Transport data: constant Lewis numbers'
            WRITE(ncrept,*)'--------------'
            WRITE(ncrept,*)

            WRITE(ncrept,*)' constants A,r; ref T; Prandtl no.:'
            WRITE(ncrept,'(4(1PE12.4))')alamdc,rlamda,tlamda,prantl
            WRITE(ncrept,*)

            WRITE(ncrept,*)'Spec.No.  Symbol         Lewis no.'
            DO ispec = 1,nspec
                WRITE(ncrept,'(I8,3X,A10,3X,1PE12.4)') ispec,spcsym(ispec),clewis(ispec)
            END DO

            WRITE(ncrept,*)
            WRITE(ncrept,*)'End of transport data'
            WRITE(ncrept,*)'---------------------'
            WRITE(ncrept,*)
            WRITE(ncrept,9000)cldash

        END IF


    END IF



    call radcin

    IF(flradn) THEN


        IF(iproc == 0) THEN


            WRITE(ncrept,*)
            WRITE(ncrept,*)'Radiation data'
            WRITE(ncrept,*)'--------------'
            WRITE(ncrept,*)
            WRITE(ncrept,*)'Planck mean absorption coefficient data'
            DO ispec = 1, nsprad
                WRITE(ncrept,'(2I6)')nsprid(ispec),nkprad(ispec)
                WRITE(ncrept,'(5(1PE15.7))')(akprad(icp,ispec),icp=1,5)
                WRITE(ncrept,'(5(1PE15.7))')(akprad(icp,ispec), icp=6,nkprad(ispec))
            END DO

            WRITE(ncrept,*)
            WRITE(ncrept,*)'Reference ambient temperature:'
            WRITE(ncrept,'(1PE15.7)')trefrn

            WRITE(ncrept,*)
            WRITE(ncrept,*)'Planck mean absorption coefficients:'
            DO ispec = 1, nsprad
                fornow = akprad(nkprad(ispec),jspec)
                DO icp = nkprm1(ispec),1,-1
                    fornow = fornow*trefrn + akprad(icp,ispec)
                END DO
                jspec = nsprid(ispec)
                WRITE(ncrept,'(I6,5X,A10,1PE15.7)')jspec,spcsym(jspec),fornow
            END DO

            WRITE(ncrept,*)
            WRITE(ncrept,*)'End of radiation data'
            WRITE(ncrept,*)'---------------------'
            WRITE(ncrept,*)
            WRITE(ncrept,9000)cldash

        END IF


    END IF







    IF(iproc == 0) THEN

        OPEN(UNIT=ncstat,FILE=fnstat,STATUS='REPLACE',FORM='FORMATTED')
        ENDFILE(ncstat)
        CLOSE(ncstat)

    END IF

    itstat = 0



#ifndef HDF5
    INQUIRE(FILE=fndmpo(1),EXIST=fxdump)
    IF(.NOT.fxdump) THEN
        IF(ndofmt == 0) THEN
            OPEN(UNIT=ncdmpo,FILE=fndmpo(1),STATUS='REPLACE',FORM='UNFORMATTED')
        ELSE
            OPEN(UNIT=ncdmpo,FILE=fndmpo(1),STATUS='REPLACE',FORM='FORMATTED')
        END IF
        CLOSE(ncdmpo)
    END IF

    INQUIRE(FILE=fndmpo(2),EXIST=fxdump)

    IF(.NOT.fxdump) THEN
        IF(ndofmt == 0) THEN
            OPEN(UNIT=ncdmpo,FILE=fndmpo(2),STATUS='REPLACE',FORM='UNFORMATTED')
        ELSE
            OPEN(UNIT=ncdmpo,FILE=fndmpo(2),STATUS='REPLACE',FORM='FORMATTED')
        END IF
        CLOSE(ncdmpo)
    END IF
#else
    call create_h5dump_files
#endif





    pi = FOUR*ATAN(ONE)


    clnten = LOG(10.0_8)


    etime = zero
    ntime2 = ntime1+ntime-1
    itime = 0



    call bcinit





    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_WRITE))

    call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_WRITE))

    call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_WRITE))




    IF(inturb == 1) call turbin

    IF(inturb == 2) THEN
        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_store4, 1, s3d_000, "real(kind=8)", OPS_READ))

        call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_store5, 1, s3d_000, "real(kind=8)", OPS_READ))

        call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_store6, 1, s3d_000, "real(kind=8)", OPS_READ))

    END IF



    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call maths_kernel_eqF_host("A = A + var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_INC), &
                      & ops_arg_gbl(urin, 1, "real(kind=8)", OPS_READ))

    call maths_kernel_eqF_host("A = A + var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_INC), &
                      & ops_arg_gbl(vrin, 1, "real(kind=8)", OPS_READ))

    call maths_kernel_eqF_host("A = A + var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_INC), &
                      & ops_arg_gbl(wrin, 1, "real(kind=8)", OPS_READ))





    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    DO ispec = 1,nspec
        call maths_kernel_eqE_host("A = var(indx)", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_yrun(ispec), 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_gbl(yrin, nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

    END DO


    rangexyz = [1-nhalox,nxglbl+nhalox,1-nhaloy,nyglbl+nhaloy,1-nhaloz,nzglbl+nhaloz]
    call maths_kernel_eqD_host("A = var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_prun, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(prin, 1, "real(kind=8)", OPS_READ))

    call maths_kernel_eqD_host("A = var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(trin, 1, "real(kind=8)", OPS_READ))


    rtin = zero
    DO ispec = 1,nspec
        rtin = rtin + rgspec(ispec)*yrin(ispec)
    END DO
    rtin = rtin*trin
    drin = prin/rtin


    erin = zero
    DO ispec = 1,nspec

        itint = 1
        DO WHILE (trin > tinthi(itint,ispec) .and. itint < ntint(ispec))
            itint = itint + 1
        END DO

        fornow = amasch(ncpoly(itint,ispec),itint,ispec)
        DO icp = ncpom1(itint,ispec),1,-1
            fornow = fornow*trin + amasch(icp,itint,ispec)
        END DO
        fornow = amasch(ncenth(itint,ispec),itint,ispec) + fornow*trin
        erin = erin + fornow*yrin(ispec)

    END DO
    fornow = urin*urin + vrin*vrin + wrin*wrin
    erin = erin - rtin + half*fornow



    IF(inflam == 1) THEN


        call flamin

    END IF




    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_WRITE))


    DO ispec = 1,nspec
        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call maths_kernel_eqK_host("A = A + var(indx)*B", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_INC), &
                          & ops_arg_dat(d_yrun(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(rgspec, nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

    END DO

    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call maths_kernel_eqV_host("A = A*B", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call maths_kernel_eqU_host("A = B/C", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_prun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_READ))





    rangexyz = [1-nhalox,nxglbl+nhalox,1-nhaloy,nyglbl+nhaloy,1-nhaloz,nzglbl+nhaloz]
    DO iindex = 1,nintmx
        call set_zero_kernel_int_host("set_zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_itndex(iindex), 1, s3d_000, "integer(kind=4)", OPS_WRITE))
    END DO

    DO ispec = 1, nspec

        iindex = 1 + (ispec-1)/nspimx
        ipower = ispec - (iindex-1)*nspimx - 1

        call maths_kernel_eqBO_host("INTERNAL ENERGY FIELD", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_itndex(iindex), 1, s3d_000, "integer(kind=4)", OPS_RW), &
                          & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(tinthi, ntinmx*nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ntint, nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ipower, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))
    END DO

    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_erun, 1, s3d_000, "real(kind=8)", OPS_WRITE))

    DO ispec = 1,nspec

        iindex = 1 + (ispec-1)/nspimx
        ipower = ispec - (iindex-1)*nspimx - 1
        icoef2 = ntbase**ipower
        icoef1 = icoef2*ntbase

        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call maths_kernel_eqBP_host("INITIALISE INTERNAL ENERGY", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_erun, 1, s3d_000, "real(kind=8)", OPS_INC), &
                          & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_dat(d_itndex(iindex), 1, s3d_000, "integer(kind=4)", OPS_READ), &
                          & ops_arg_dat(d_yrun(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(amasch, ncofmx*ntinmx*nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ncpoly, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ncpom1, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ncenth, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ipower, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(icoef1, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(icoef2, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

    END DO

    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call maths_kernel_eqAU_host("A = A - B + half*(C*C+D*D+E*E)", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_erun, 1, s3d_000, "real(kind=8)", OPS_INC), &
                      & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_READ))



    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call maths_kernel_eqV_host("A = A*B", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call maths_kernel_eqV_host("A = A*B", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call maths_kernel_eqV_host("A = A*B", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call maths_kernel_eqV_host("A = A*B", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_erun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(kind=8)", OPS_READ))

    DO ispec = 1,nspec
        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call maths_kernel_eqV_host("A = B*A", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_yrun(ispec), 1, s3d_000, "real(kind=8)", OPS_RW), &
                          & ops_arg_dat(d_drun, 1, s3d_000, "real(kind=8)", OPS_READ))

    END DO




    IF(ncdmpi == 1) THEN








#ifndef HDF5
        IF(ndifmt == 0) THEN

            write(*, '(a)') "Using the arrays not allocated by OPS, &
                        Please implement the function in OPS first, indata.F90: ID=1307"
            STOP

            OPEN(UNIT=ncdmpi,FILE=fndmpo(2),STATUS='OLD', FORM='UNFORMATTED')
            READ(ncdmpi)nxdmax,nydmax,nzdmax,ndspec, drun,urun,vrun,wrun,erun,yrun,  &
                etime,tstep,errold,errldr

            IF(nxdmax /= nxsize)WRITE(6,*)'Dump input size error: x'
            IF(nydmax /= nysize)WRITE(6,*)'Dump input size error: y'
            IF(nzdmax /= nzsize)WRITE(6,*)'Dump input size error: z'
            IF(ndspec /= nspec)WRITE(6,*)'Dump input size error: species'

            CLOSE(ncdmpi)
        ELSE

            OPEN(UNIT=ncdmpi,FILE=fndmpo(1),STATUS='OLD',FORM='FORMATTED')
            READ(ncdmpi,*)nxdmax,nydmax,nzdmax,ndspec

            IF(nxdmax /= nxsize)WRITE(6,*)'Dump input size error: x'
            IF(nydmax /= nysize)WRITE(6,*)'Dump input size error: y'
            IF(nzdmax /= nzsize)WRITE(6,*)'Dump input size error: z'
            IF(ndspec /= nspec)WRITE(6,*)'Dump input size error: species'

            write(*, '(a)') "Using the arrays not allocated by OPS, &
                        Please implement the function in OPS first, indata.F90: ID=1335"
            STOP

            DO kc = 1, nzsize
                DO jc = 1, nysize
                    DO ic = 1, nxsize
                        READ(ncdmpi,*)drun(ic,jc,kc),  &
                            urun(ic,jc,kc),vrun(ic,jc,kc),wrun(ic,jc,kc), erun(ic,jc,kc),  &
                            (yrun(ispec,ic,jc,kc),ispec=1,nspec)
                    END DO
                END DO
            END DO

            READ(ncdmpi,*)etime,tstep,errold,errldr

            CLOSE(ncdmpi)
        END IF
#else
        call read_h5dump_files
#endif



    END IF




    durin = drin*urin
    dvrin = drin*vrin
    dwrin = drin*wrin
    derin = drin*erin

    DO ispec = 1,nspec
        dyrin(ispec) = drin*yrin(ispec)
    END DO

    rangexyz = [1-nhalox,nxglbl+nhalox,1-nhaloy,nyglbl+nhaloy,1-nhaloz,nzglbl+nhaloz]
    call maths_kernel_eqD_host("A = var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_drhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(drin, 1, "real(kind=8)", OPS_READ))

    call maths_kernel_eqD_host("A = var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_urhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(durin, 1, "real(kind=8)", OPS_READ))

    call maths_kernel_eqD_host("A = var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_vrhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(dvrin, 1, "real(kind=8)", OPS_READ))

    call maths_kernel_eqD_host("A = var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_wrhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(dwrin, 1, "real(kind=8)", OPS_READ))

    call maths_kernel_eqD_host("A = var", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_erhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_gbl(derin, 1, "real(kind=8)", OPS_READ))

    rangexyz = [1-nhalox,nxglbl+nhalox,1-nhaloy,nyglbl+nhaloy,1-nhaloz,nzglbl+nhaloz]
    DO ispec = 1,nspec
        call maths_kernel_eqE_host("A = var(indx)", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_gbl(dyrin, nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

    END DO


    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_drhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_urhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_vrhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_wrhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_erhs, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_erun, 1, s3d_000, "real(kind=8)", OPS_READ))

    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    DO ispec = 1,nspec
        call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_yrun(ispec), 1, s3d_000, "real(kind=8)", OPS_READ))

    END DO



    call parfer



    call tempin





    call dtinit



    call dfinit






    IF(iproc == 0) THEN

        WRITE(ncrept,9000)cldash
        WRITE(ncrept,*)

        CLOSE(ncrept)

    END IF


9000  FORMAT(a79)
9010  FORMAT('**',75X,'**')
9020  FORMAT('**',18X,'DIRECT NUMERICAL SIMULATION CODE SENGA2', 18X,'**')
9030  FORMAT('**',31X,'Stewart Cant',32X,'**')
9040  FORMAT('**',16X,'Cambridge University Engineering Department', 16X,'**')
9200  FORMAT(12I6)
9250  FORMAT(6I7)
9270  FORMAT(2I5,5(1PE12.4))
9300  FORMAT(1PE12.4,6I8)
9400  FORMAT(6(1PE12.4))
9450  FORMAT(i7,1PE15.7)
9600  FORMAT(' Actual (NSPEC) = ',i5,2X,'Max (NSPCMX) = ',i5)

END SUBROUTINE indata
