!
! auto-generated by ops_fortran.py
!
SUBROUTINE lincom

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use LINCOM_KERNEL_MAIN_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga















    integer(kind=4) :: ispec
    integer(kind=4) :: rangexyz(6)








    rangexyz(1) = 1
    IF (nsbcxl == nsbci3) rangexyz(1) = 2
    rangexyz(2) = nxglbl
    IF (nsbcxr == nsbci3) rangexyz(2) = nxglbl-1
    rangexyz(3) = 1
    IF (nsbcyl == nsbci3) rangexyz(3) = 2
    rangexyz(4) = nyglbl
    IF (nsbcyr == nsbci3) rangexyz(4) = nyglbl-1
    rangexyz(5) = 1
    IF (nsbczl == nsbci3) rangexyz(5) = 2
    rangexyz(6) = nzglbl
    IF (nsbczr == nsbci3) rangexyz(6) = nzglbl-1

    call lincom_kernel_main_host("lincom_main", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_derr, 1, s3d_000, "real(kind=8)", OPS_INC), &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_drhs, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_gbl(rkerr, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rklhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rkrhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(irkstp, 1, "integer(kind=4)", OPS_READ))


    rangexyz(1) = 1
    IF (nsbcxl == nsbci2 .or. nsbcxl == nsbci3 .or. nsbcxl == nsbcw1 .or. nsbcxl == nsbcw2) rangexyz(1) = 2
    rangexyz(2) = nxglbl
    IF (nsbcxr == nsbci2 .or. nsbcxr == nsbci3 .or. nsbcxr == nsbcw1 .or. nsbcxr == nsbcw2) rangexyz(2) = nxglbl-1
    rangexyz(3) = 1
    IF (nsbcyl == nsbci2 .or. nsbcyl == nsbci3 .or. nsbcyl == nsbcw1 .or. nsbcyl == nsbcw2) rangexyz(3) = 2
    rangexyz(4) = nyglbl
    IF (nsbcyr == nsbci2 .or. nsbcyr == nsbci3 .or. nsbcyr == nsbcw1 .or. nsbcyr == nsbcw2) rangexyz(4) = nyglbl-1
    rangexyz(5) = 1
    IF (nsbczl == nsbci2 .or. nsbczl == nsbci3 .or. nsbczl == nsbcw1 .or. nsbczl == nsbcw2) rangexyz(5) = 2
    rangexyz(6) = nzglbl
    IF (nsbczr == nsbci2 .or. nsbczr == nsbci3 .or. nsbczr == nsbcw1 .or. nsbczr == nsbcw2) rangexyz(6) = nzglbl-1

    call lincom_kernel_main_host("lincom_main", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_uerr, 1, s3d_000, "real(kind=8)", OPS_INC), &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_urhs, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_gbl(rkerr, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rklhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rkrhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(irkstp, 1, "integer(kind=4)", OPS_READ))


    call lincom_kernel_main_host("lincom_main", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_verr, 1, s3d_000, "real(kind=8)", OPS_INC), &
                      & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_vrhs, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_gbl(rkerr, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rklhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rkrhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(irkstp, 1, "integer(kind=4)", OPS_READ))


    call lincom_kernel_main_host("lincom_main", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_werr, 1, s3d_000, "real(kind=8)", OPS_INC), &
                      & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_wrhs, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_gbl(rkerr, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rklhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rkrhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(irkstp, 1, "integer(kind=4)", OPS_READ))


    rangexyz(1) = 1
    IF (nsbcxl == nsbci2 .or. nsbcxl == nsbcw2) rangexyz(1) = 2
    rangexyz(2) = nxglbl
    IF (nsbcxr == nsbci2 .or. nsbcxr == nsbcw2) rangexyz(2) = nxglbl-1
    rangexyz(3) = 1
    IF (nsbcyl == nsbci2 .or. nsbcyl == nsbcw2) rangexyz(3) = 2
    rangexyz(4) = nyglbl
    IF (nsbcyr == nsbci2 .or. nsbcyr == nsbcw2) rangexyz(4) = nyglbl-1
    rangexyz(5) = 1
    IF (nsbczl == nsbci2 .or. nsbczl == nsbcw2) rangexyz(5) = 2
    rangexyz(6) = nzglbl
    IF (nsbczr == nsbci2 .or. nsbczr == nsbcw2) rangexyz(6) = nzglbl-1

    call lincom_kernel_main_host("lincom_main", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_eerr, 1, s3d_000, "real(kind=8)", OPS_INC), &
                      & ops_arg_dat(d_erun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_erhs, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_gbl(rkerr, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rklhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(rkrhs, nrkmax, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(irkstp, 1, "integer(kind=4)", OPS_READ))



    rangexyz(1) = 1
    IF (nsbcxl == nsbci2 .or. nsbcxl == nsbci3) rangexyz(1) = 2
    rangexyz(2) = nxglbl
    IF (nsbcxr == nsbci2 .or. nsbcxr == nsbci3) rangexyz(2) = nxglbl-1
    rangexyz(3) = 1
    IF (nsbcyl == nsbci2 .or. nsbcyl == nsbci3) rangexyz(3) = 2
    rangexyz(4) = nyglbl
    IF (nsbcyr == nsbci2 .or. nsbcyr == nsbci3) rangexyz(4) = nyglbl-1
    rangexyz(5) = 1
    IF (nsbczl == nsbci2 .or. nsbczl == nsbci3) rangexyz(5) = 2
    rangexyz(6) = nzglbl
    IF (nsbczr == nsbci2 .or. nsbczr == nsbci3) rangexyz(6) = nzglbl-1

    DO ispec = 1,nspec

        call lincom_kernel_main_host("lincom_main", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_yerr(ispec), 1, s3d_000, "real(kind=8)", OPS_INC), &
                          & ops_arg_dat(d_yrun(ispec), 1, s3d_000, "real(kind=8)", OPS_RW), &
                          & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_RW), &
                          & ops_arg_gbl(rkerr, nrkmax, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(rklhs, nrkmax, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(rkrhs, nrkmax, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(irkstp, 1, "integer(kind=4)", OPS_READ))

    END DO


END SUBROUTINE lincom
