
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.cuda
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.hip
USE_HDF5=1
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.hdf5

OTHER_FILES = constants.F90 cuda_constant.F90 com_espect.F90 com_senga2.F90 \
    dfmstr.F90 ardums.F90 ardump.F90 buftxl.F90 \
    chkarr.F90 chkary.F90 erfunc.F90 espect.F90 espksq.F90 espovk.F90 \
    finish.F90 diffin.F90 hdf5io.F90 contin.F90 bcinit.F90 turbft.F90 \
    fftsym.F90 fftf3d.F90 integf.F90 fftixl.F90

OPS_FILES = senga2.F90 com_ops_senga2.F90 ops_data_init.F90 dfinit.F90 dfbydx.F90 d2fdx2.F90 \
    dfbydy.F90 dfbydz.F90 d2fdy2.F90 d2fdz2.F90 zeroxl.F90 zeroxr.F90 zeroyl.F90 zeroyr.F90 \
    zerozl.F90 zerozr.F90 d2fdxy.F90 d2fdxz.F90 d2fdyz.F90 rhscal.F90 rhsvel.F90 \
    lincom.F90 fincom.F90 adaptt.F90 bcdtxl.F90 bcdtxr.F90 bcdtyl.F90 bcdtyr.F90 \
    bcdtzl.F90 bcdtzr.F90 bcttxl.F90 bcttxr.F90 bcttyl.F90 bcttyr.F90 bcttzl.F90 \
    bcttzr.F90 bcutxl.F90 bcutxr.F90 bcutyl.F90 bcutyr.F90 bcutzl.F90 bcutzr.F90 \
    bcytxl.F90 bcytxr.F90 bcytyl.F90 bcytyr.F90 bcytzl.F90 bcytzr.F90 bounds.F90 \
    bountt.F90 boundt.F90 radcal.F90 radcin.F90 bctixl.F90 flamin.F90 chrate.F90 \
    indata.F90 dtinit.F90 chemin.F90 espini.F90 turbin.F90 temper.F90 temper_fused.F90 pardom.F90 \
    tempin.F90 parfer.F90 output.F90 print_dats.F90 print_alldats.F90 print_output.F90

ifeq ($(OPS_COMPILER),gnu)
#APP_FLAGS = -mcmodel=medium -fopt-info-vec -fopt-info-vec-optimized -fopt-info-vec-missed -funroll-loops -funroll-all-loops -finline-functions -ftree-vectorize -fstrict-aliasing
APP_FLAGS = -mcmodel=medium -fallow-argument-mismatch
APP_CXX_FLAGS = -mcmodel=medium #-fsanitize=undefined
endif

ifeq ($(OPS_COMPILER),intel)
APP_FLAGS = -mcmodel=large -fp-model precise -fp-model source -no-fma -fimf-arch-consistency=true -fimf-precision=high
#APP_FLAGS = -mcmodel=large -fp-model precise -fp-model source -no-fma -nolib-inline
APP_CXX_FLAGS = -mcmodel=medium -fp-model precise -fp-model source -prec-div -prec-sqrt
endif

ifeq ($(OPS_COMPILER),pgi)
APP_FLAGS = -Kieee -Mnofpapprox -mcmodel=medium -Ktrap=unf -Mnofprelaxed -m64 -pc 64
APP_CXX_FLAGS = -mcmodel=medium -Kieee -nofma
#-nofma
endif

ifeq ($(OPS_COMPILER),cray)
APP_FLAGS = -N 1023
#-hlist=m -h vector3 -h flex_mp=strict
#APP_FLAGS = -h noacc,fp1,contiguous_assumed_shape,nofma,zero -h flex_mp=strict  -h nofma -hfp1=noapprox -K trap=divz,fp,inv,unf
endif

APP_LIBS = fftlib/fftlib.a rndlib/rndlib.a parlib/parlib.a -lm

TARGETS = seq tiled openmp mpi mpi_openmp mpi_tiled ompoffload mpi_ompoffload mpi_ompoffload_tiled

ifeq ($(OPS_COMPILER),pgi)
	TARGETS += cuda mpi_cuda mpi_cuda_tiled
endif

APP = senga2
MAIN_SRC = senga2

##############################################################################
ifndef OPS_GENERATED_SUFFIX
OPS_GENERATED_SUFFIX=_ops
endif

ifeq ($(strip $(OPS_GENERATED)),)
OPS_GENERATED=$(join $(addsuffix $(OPS_GENERATED_SUFFIX), $(basename $(OPS_FILES))), $(suffix $(OPS_FILES)))
endif

OPS_FILES_GEN=$(OTHER_FILES) $(OPS_GENERATED)

# New clang/fparser based code-gen
.generated: $(OPS_FILES) $(OPS_INSTALL_PATH)/../ops_translator/ops-translator/*.py
	@echo "generating translations for ${OPS_FILES}"
	@echo "OPS_EXTENTIONS: ${OPS_GENERATED_SUFFIX}"
	@echo "OPS_GENERATED: ${OPS_GENERATED}"
	which python3
	python3 $(OPS_INSTALL_PATH)/../ops_translator/ops-translator $(VERBOSE) $(DEFINES) -I $(OPS_INSTALL_PATH)/c/include/ --file_paths $(OPS_FILES)
	rm -f .generated
	touch .generated

# Legacy code-gen
#.generated: $(OPS_FILES) $(OPS_INSTALL_PATH)/../ops_translator_legacy/fortran/*.py
#	$(OPS_INSTALL_PATH)/../ops_translator_legacy/fortran/ops_fortran.py $(OPS_FILES)
#	rm -f .generated
#	touch .generated

# check what targets can not be built with current environment setting and give warnings
ifneq ($(strip $(TARGETS)),)

ifneq (,$(filter cuda mpi_cuda mpi_cuda_tiled,$(TARGETS)))
ifneq ($(OPS_COMPILER),pgi)
TARGETS:=$(filter-out cuda mpi_cuda mpi_cuda_tiled,$(TARGETS))
endif
endif

ifneq (,$(filter f2c_cuda f2c_mpi_cuda f2c_mpi_cuda_tiled,$(TARGETS)))
ifndef CUDA_INSTALL_PATH
TARGETS:=$(filter-out f2c_cuda f2c_mpi_cuda f2c_mpi_cuda_tiled,$(TARGETS))
endif   #ifndef CUDA_INSTALL_PATH
endif

endif

ifndef TARGETS
TARGETS = seq openmp tiled mpi mpi_openmp mpi_tiled ompoffload mpi_ompoffload mpi_ompoffload_tiled

ifeq ($(OPS_COMPILER),pgi)
TARGETS += cuda mpi_cuda mpi_cuda_tiled
endif

ifdef CUDA_INSTALL_PATH
TARGETS += f2c_mpi_cuda
endif

ifdef HIP_INSTALL_PATH
TARGETS += f2c_mpi_hip
endif

endif

ifneq (,$(filter ompoffload mpi_ompoffload mpi_ompoffload_tiled,$(TARGETS)))
ifeq ($(OPS_COMPILER),gnu)
TARGETS:=$(filter-out ompoffload mpi_ompoffload mpi_ompoffload_tiled,$(TARGETS))
endif
ifeq ($(OPS_COMPILER),intel)
TARGETS:=$(filter-out ompoffload mpi_ompoffload mpi_ompoffload_tiled,$(TARGETS))
endif
ifeq ($(OPS_COMPILER),intel-sycl)
TARGETS:=$(filter-out ompoffload mpi_ompoffload mpi_ompoffload_tiled,$(TARGETS))
endif
endif

ifneq (,$(filter ompoffload mpi_ompoffload mpi_ompoffload_tiled,$(TARGETS)))
OTHER_FILES_OFFLOAD := $(patsubst %, %_offload, $(filter-out constants.F90, $(OTHER_FILES))) constants_offload.F90
endif

ifneq ($(strip $(MPI_INSTALL_PATH)),)
ifneq (,$(wildcard $(MPI_INC)))
I_MPI_INC = -I$(MPI_INC)
endif
ifneq (,$(wildcard $(MPI_LIB)))
L_MPI_LIB = -L$(MPI_LIB)
endif
else
I_MPI_INC = $(foreach dir,$(shell $(MPICC) --showme:incdirs),-I$(dir))
endif

F2C_CXXFLAGS = $(CXXFLAGS)
ifeq ($(filter $(OPS_COMPILER),intel pgi),$(OPS_COMPILER))
F2C_CXXFLAGS := $(subst -std=c++11,-std=c++14,$(F2C_CXXFLAGS))
endif

F2C_NVCCFLAGS = $(NVCCFLAGS)
ifneq ($(strip $(F2C_NVCCFLAGS)),)
F2C_NVCCFLAGS := $(subst -std=c++11,-std=c++14,$(F2C_NVCCFLAGS))
F2C_NVCCFLAGS += --expt-relaxed-constexpr
F2C_NVCCFLAGS += -Xcompiler="-mcmodel=medium"
endif

F2C_HIPFLAGS = $(HIPFLAGS)
ifneq ($(strip $(F2C_HIPFLAGS)),)
F2C_HIPFLAGS := $(subst -std=c++11,-std=c++14,$(F2C_HIPFLAGS))
#F2C_HIPFLAGS += --expt-relaxed-constexpr
#F2C_HIPFLAGS += -Xcompiler="-mcmodel=medium"
endif

CXXFLAGS_NOOMP = $(CXXFLAGS)
CXXFLAGS_NOOMP := $(filter-out -fopenmp, $(CXXFLAGS_NOOMP))
CXXFLAGS_NOOMP := $(filter-out -qopenmp, $(CXXFLAGS_NOOMP))

F2C_CUDAFOR = $(CUDAFOR)
ifeq ($(OPS_COMPILER),pgi)
F2C_CUDAFOR := $(filter-out -DOPS_WITH_CUDAFOR, $(F2C_CUDAFOR))
endif

APP_TARGETS = $(addprefix $(APP)_, $(TARGETS))

all: $(APP_TARGETS)

SEQ_KERNELS = $(wildcard mpi_openmp/*.F90)
CUDA_KERNELS = $(wildcard cuda/*.CUF)
OFFLOAD_KERNELS = $(wildcard openmp_offload/*.F90)

MODULE_FILES = constants.F90 com_espect.F90 com_senga2.F90
OPS_MODULE_FILES = com_ops_senga2_ops.F90
OTHER_FILES := $(filter-out $(MODULE_FILES), $(OTHER_FILES))
OTHER_FILES := $(filter-out $(OPS_MODULE_FILES), $(OTHER_FILES))
OPS_GENERATED := $(filter-out $(MODULE_FILES), $(OPS_GENERATED))
OPS_GENERATED := $(filter-out $(OPS_MODULE_FILES), $(OPS_GENERATED))

MODULE_FILES_OMPOFFLOAD = constants_offload.F90 com_espect.F90 com_senga2.F90

#=========================================================================================================================

SEQ_OBJ = $(MODULE_FILES:.F90=_seq.o) $(OPS_MODULE_FILES:.F90=_seq.o) $(OTHER_FILES:.F90=_seq.o) $(SEQ_KERNELS:.F90=_seq.o) $(OPS_GENERATED:.F90=_seq.o)

OMP_OBJ = $(MODULE_FILES:.F90=_omp.o) $(OPS_MODULE_FILES:.F90=_omp.o) $(OTHER_FILES:.F90=_omp.o) $(SEQ_KERNELS:.F90=_omp.o) $(OPS_GENERATED:.F90=_omp.o)

TILED_OBJ = $(MODULE_FILES:.F90=_tiled.o) $(OPS_MODULE_FILES:.F90=_tiled.o) $(OTHER_FILES:.F90=_tiled.o) $(SEQ_KERNELS:.F90=_tiled.o) $(OPS_GENERATED:.F90=_tiled.o)

MPI_OBJ = $(MODULE_FILES:.F90=_mpi.o) $(OPS_MODULE_FILES:.F90=_mpi.o) $(OTHER_FILES:.F90=_mpi.o) $(SEQ_KERNELS:.F90=_mpi.o) $(OPS_GENERATED:.F90=_mpi.o)

MPI_TILED_OBJ = $(MODULE_FILES:.F90=_mpi_tiled.o) $(OPS_MODULE_FILES:.F90=_mpi_tiled.o) $(OTHER_FILES:.F90=_mpi_tiled.o) $(SEQ_KERNELS:.F90=_mpi_tiled.o) $(OPS_GENERATED:.F90=_mpi_tiled.o)

MPI_OMP_OBJ = $(MODULE_FILES:.F90=_mpi_omp.o) $(OPS_MODULE_FILES:.F90=_mpi_omp.o) $(OTHER_FILES:.F90=_mpi_omp.o) $(SEQ_KERNELS:.F90=_mpi_omp.o) $(OPS_GENERATED:.F90=_mpi_omp.o)

CUDA_OBJ = $(MODULE_FILES:.F90=_cuda.o) $(OPS_MODULE_FILES:.F90=_cuda.o) $(OTHER_FILES:.F90=_cuda.o) $(CUDA_KERNELS:.CUF=_cuda.o) $(OPS_GENERATED:.F90=_cuda.o)

MPI_CUDA_OBJ = $(MODULE_FILES:.F90=_mpi_cuda.o) $(OPS_MODULE_FILES:.F90=_mpi_cuda.o) $(OTHER_FILES:.F90=_mpi_cuda.o) $(CUDA_KERNELS:.CUF=_mpi_cuda.o) $(OPS_GENERATED:.F90=_mpi_cuda.o)

MPI_CUDA_TILED_OBJ = $(MODULE_FILES:.F90=_mpi_cuda_tiled.o) $(OPS_MODULE_FILES:.F90=_mpi_cuda_tiled.o) $(OTHER_FILES:.F90=_mpi_cuda_tiled.o) $(CUDA_KERNELS:.CUF=_mpi_cuda_tiled.o) $(OPS_GENERATED:.F90=_mpi_cuda_tiled.o)

OMPOFFLOAD_OBJ = $(MODULE_FILES_OMPOFFLOAD:.F90=_offload.o) $(OPS_MODULE_FILES:.F90=_offload.o) $(OTHER_FILES:.F90=_offload.o) $(OFFLOAD_KERNELS:.F90=_offload.o) $(OPS_GENERATED:.F90=_offload.o)

MPI_OMPOFFLOAD_OBJ = $(MODULE_FILES_OMPOFFLOAD:.F90=_mpi_offload.o) $(OPS_MODULE_FILES:.F90=_mpi_offload.o) $(OTHER_FILES:.F90=_mpi_offload.o) $(OFFLOAD_KERNELS:.F90=_mpi_offload.o) $(OPS_GENERATED:.F90=_mpi_offload.o)

MPI_OMPOFFLOAD_TILED_OBJ = $(MODULE_FILES_OMPOFFLOAD:.F90=_mpi_offload_tiled.o) $(OPS_MODULE_FILES:.F90=_mpi_offload_tiled.o) $(OTHER_FILES:.F90=_mpi_offload_tiled.o) $(OFFLOAD_KERNELS:.F90=_mpi_offload_tiled.o) $(OPS_GENERATED:.F90=_mpi_offload_tiled.o)

#=========================================================================================================================

CXX_MASTER_KERNELS = f2c_mpi_openmp/f2c_mpi_openmp_kernels.cpp
F2C_SEQ_KERNELS = $(wildcard f2c_mpi_openmp/*.F90)

F2C_MPI_OBJ = $(MODULE_FILES:.F90=_f2c_mpi.o) $(OPS_MODULE_FILES:.F90=_f2c_mpi.o) $(OTHER_FILES:.F90=_f2c_mpi.o) $(CXX_MASTER_KERNELS:.cpp=_f2c_mpi.o) $(F2C_SEQ_KERNELS:.F90=_f2c_mpi.o) $(OPS_GENERATED:.F90=_f2c_mpi.o)

f2c_mpi_openmp/f2c_mpi_openmp_kernels_f2c_mpi.o: f2c_mpi_openmp/f2c_mpi_openmp_kernels.cpp
	$(MPICPP) $(F2C_CXXFLAGS) $(APP_CXX_FLAGS) -DOPS_FTN -DOPS_MPI $(I_MPI_INC) -I$(C_OPS_INC) -I. -c $< -o $@

%_f2c_mpi.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS) -DOPS_MPI -DOPS_F2C_INTEROP -c $< -o $@


CXX_CUDA_MASTER_KERNELS = f2c_cuda/f2c_cuda_kernels.cu
F2C_CUDA_KERNELS = $(wildcard f2c_cuda/*.F90)

F2C_MPI_CUDA_OBJ = $(MODULE_FILES:.F90=_f2c_mpi_cuda.o) $(OPS_MODULE_FILES:.F90=_f2c_mpi_cuda.o) $(OTHER_FILES:.F90=_f2c_mpi_cuda.o) $(CXX_CUDA_MASTER_KERNELS:.cu=_f2c_mpi_cuda.o) $(F2C_CUDA_KERNELS:.F90=_f2c_mpi_cuda.o) $(OPS_GENERATED:.F90=_f2c_mpi_cuda.o)

f2c_cuda/f2c_cuda_kernels_f2c_mpi_cuda.o: f2c_cuda/f2c_cuda_kernels.cu
	$(NVCC) $(CXXFLAGS_NOOMP) $(F2C_NVCCFLAGS) -DOPS_FTN -DOPS_MPI -I$(C_OPS_INC) -I. -DMPICH_IGNORE_CXX_SEEK $(I_MPI_INC) -c $< -o $@

%_f2c_mpi_cuda.o: %.F90
	 $(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS_F2C_CUDA) -DOPS_MPI -DOPS_F2C_INTEROP -c $< -o $@


CXX_HIP_MASTER_KERNELS = f2c_hip/f2c_hip_kernels.cpp
F2C_HIP_KERNELS = $(wildcard f2c_hip/*.F90)

F2C_MPI_HIP_OBJ = $(MODULE_FILES:.F90=_f2c_mpi_hip.o) $(OPS_MODULE_FILES:.F90=_f2c_mpi_hip.o) $(OTHER_FILES:.F90=_f2c_mpi_hip.o) $(CXX_HIP_MASTER_KERNELS:.cpp=_f2c_mpi_hip.o) $(F2C_HIP_KERNELS:.F90=_f2c_mpi_hip.o) $(OPS_GENERATED:.F90=_f2c_mpi_hip.o)

f2c_hip/f2c_hip_kernels_f2c_mpi_hip.o: f2c_hip/f2c_hip_kernels.cpp
	$(HIPMPICPP) $(CXXFLAGS_NOOMP) $(F2C_HIPFLAGS) -DOPS_FTN -DOPS_MPI -I$(C_OPS_INC) -I. -DMPICH_IGNORE_CXX_SEEK $(I_MPI_INC) -c $< -o $@

%_f2c_mpi_hip.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS_F2C_HIP) -DOPS_MPI -DOPS_F2C_INTEROP -c $< -o $@

#=========================================================================================================================

%_seq.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS) -c $< -o $@

%_omp.o: %.F90
	$(MPIF90) $(FFLAGS) $(OMPFLAGS) $(APP_FLAGS) $(FMODS) -c $< -o $@

%_tiled.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) -DOPS_LAZY $(FMODS) -c $< -o $@

%_mpi.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) -DOPS_MPI $(FMODS) -c $< -o $@

%_mpi_tiled.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) -DOPS_MPI -DOPS_LAZY $(FMODS) -c $< -o $@

%_mpi_omp.o: %.F90
	$(MPIF90) $(FFLAGS) $(OMPFLAGS) $(APP_FLAGS) -DOPS_MPI $(FMODS) -c $< -o $@

%_cuda.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(CUDAFOR) $(FMODS_CUDA) -c $< -o $@

%_cuda.o: %.CUF
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(CUDAFOR) $(FMODS_CUDA) -c $< -o $@

%_mpi_cuda.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(CUDAFOR) -DOPS_MPI $(FMODS_CUDA) -c $< -o $@

%_mpi_cuda.o: %.CUF
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(CUDAFOR) -DOPS_MPI $(FMODS_CUDA) -c $< -o $@

%_mpi_cuda_tiled.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(CUDAFOR) -DOPS_MPI -DOPS_LAZY $(FMODS_CUDA) -c $< -o $@

%_mpi_cuda_tiled.o: %.CUF
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(CUDAFOR) -DOPS_MPI -DOPS_LAZY $(FMODS_CUDA) -c $< -o $@

%_offload.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(OMPOFFLOADFLAGS) $(OMPOFFLOADFOR) $(FMODS_OMPOFFLOAD) -c $< -o $@

%_mpi_offload.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(OMPOFFLOADFLAGS) $(OMPOFFLOADFOR) -DOPS_MPI $(FMODS_OMPOFFLOAD) -c $< -o $@

%_mpi_offload_tiled.o: %.F90
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(OMPOFFLOADFLAGS) $(OMPOFFLOADFOR) -DOPS_MPI -DOPS_LAZY $(FMODS_OMPOFFLOAD) -c $< -o $@


#=========================================================================================================================

$(APP)_seq: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_seq.a $(SEQ_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_seq"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS) $(SEQ_OBJ) $(APP_LIBS) $(FLINK) -lops_for_seq $(F_HDF5_LIB_SEQ) -o $(APP)_seq

#=========================================================================================================================

$(APP)_openmp: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_seq.a $(OMP_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_openmp"
	@echo ""
	$(MPIF90) $(FFLAGS) $(OMPFLAGS) $(APP_FLAGS) $(FMODS) $(OMP_OBJ) $(APP_LIBS) $(FLINK) -lops_for_seq $(F_HDF5_LIB_SEQ) -o $(APP)_openmp

#=========================================================================================================================

$(APP)_tiled: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_seq.a $(TILED_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_tiled"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS) -DOPS_LAZY $(TILED_OBJ) $(APP_LIBS) $(FLINK) -lops_for_seq $(F_HDF5_LIB_SEQ) -o $(APP)_tiled

#=========================================================================================================================

$(APP)_mpi: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_mpi.a $(MPI_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_mpi"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS) -DOPS_MPI $(MPI_OBJ) $(APP_LIBS) $(FLINK) -lops_for_mpi $(F_HDF5_LIB_MPI) $(L_MPI_LIB) $(MPI_LINK) -o $(APP)_mpi

#=========================================================================================================================

$(APP)_f2c_mpi: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_f2c_mpi.a $(F2C_MPI_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_f2c_mpi"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS) -I$(C_OPS_INC) -DOPS_MPI $(I_MPI_INC) -DOPS_F2C_INTEROP $(F2C_MPI_OBJ) $(APP_LIBS) $(FLINK) -lops_f2c_mpi $(F_HDF5_LIB_MPI) $(L_MPI_LIB) $(MPI_LINK) -o $(APP)_f2c_mpi

#=========================================================================================================================

$(APP)_mpi_tiled: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_mpi.a $(MPI_TILED_OBJ)
	@echo ""
	@echo ""
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS) -DOPS_MPI -DOPS_LAZY $(MPI_TILED_OBJ) $(APP_LIBS) $(FLINK) -lops_for_mpi $(F_HDF5_LIB_MPI) $(L_MPI_LIB) $(MPI_LINK) -o $(APP)_mpi_tiled

#=========================================================================================================================

$(APP)_mpi_openmp: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_mpi.a $(MPI_OMP_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_mpi_openmp"
	@echo ""
	$(MPIF90) $(FFLAGS) $(OMPFLAGS) $(APP_FLAGS) $(FMODS) -DOPS_MPI $(MPI_OMP_OBJ) $(APP_LIBS) $(FLINK) -lops_for_mpi $(F_HDF5_LIB_MPI) $(L_MPI_LIB) $(MPI_LINK) -o $(APP)_mpi_openmp

#=========================================================================================================================

$(APP)_cuda: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_cuda.a $(CUDA_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_cuda"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS_CUDA) $(CUDAFOR) $(CUDA_OBJ) $(APP_LIBS) $(FLINK) -lops_for_cuda $(F_HDF5_LIB_SEQ) $(FCURAND) -o $(APP)_cuda

#=========================================================================================================================

$(APP)_mpi_cuda: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_mpi_cuda.a $(MPI_CUDA_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_mpi_cuda"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS_CUDA) $(CUDAFOR) -DOPS_MPI $(MPI_CUDA_OBJ) $(APP_LIBS) $(FLINK) -lops_for_mpi_cuda $(F_HDF5_LIB_MPI) $(FCURAND) $(L_MPI_LIB) $(MPI_LINK) -o $(APP)_mpi_cuda

#=========================================================================================================================

$(APP)_f2c_mpi_cuda: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_f2c_mpi_cuda.a $(F2C_MPI_CUDA_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_mpi_cuda"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) -I$(CUDA_INC) -I$(C_OPS_INC) $(FMODS_F2C_CUDA) $(I_MPI_INC) -DOPS_MPI $(F2C_MPI_CUDA_OBJ) $(APP_LIBS) $(FLINK) -lops_f2c_mpi_cuda $(F_HDF5_LIB_MPI) -L$(CUDA_LIB) $(CUDART) $(CURAND) $(L_MPI_LIB) $(MPI_LINK) -o $(APP)_f2c_mpi_cuda

#=========================================================================================================================

$(APP)_mpi_cuda_tiled: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_mpi_cuda.a $(MPI_CUDA_TILED_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_mpi_cuda_tiled"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(FMODS_CUDA) $(CUDAFOR) -DOPS_MPI -DOPS_LAZY $(MPI_CUDA_TILED_OBJ) $(APP_LIBS) $(FLINK) -lops_for_mpi_cuda $(F_HDF5_LIB_MPI) $(FCURAND) $(L_MPI_LIB) $(MPI_LINK) -o $(APP)_mpi_cuda_tiled

#=========================================================================================================================

$(APP)_ompoffload: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_ompoffload.a $(OMPOFFLOAD_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_ompoffload"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(OMPOFFLOADFLAGS) $(FMODS_OMPOFFLOAD) $(OMPOFFLOADFOR) $(OMPOFFLOAD_OBJ) $(APP_LIBS) $(FLINK) -lops_for_ompoffload $(F_HDF5_LIB_SEQ) -o $(APP)_ompoffload

#=========================================================================================================================

$(APP)_mpi_ompoffload: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_mpi_ompoffload.a $(MPI_OMPOFFLOAD_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_mpi_ompoffload"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(OMPOFFLOADFLAGS) $(FMODS_OMPOFFLOAD) $(OMPOFFLOADFOR) -DOPS_MPI $(MPI_OMPOFFLOAD_OBJ) $(APP_LIBS) $(FLINK) -lops_for_mpi_ompoffload $(F_HDF5_LIB_MPI) $(L_MPI_LIB) $(MPI_LINK) $(MPI_OMPOFFLOAD_LINK) -o $(APP)_mpi_ompoffload

#=========================================================================================================================

$(APP)_mpi_ompoffload_tiled: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_for_mpi_ompoffload.a $(MPI_OMPOFFLOAD_TILED_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_mpi_ompoffload_tiled"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) $(OMPOFFLOADFLAGS) $(FMODS_OMPOFFLOAD) $(OMPOFFLOADFOR) -DOPS_LAZY -DOPS_MPI $(MPI_OMPOFFLOAD_TILED_OBJ) $(APP_LIBS) $(FLINK) -lops_for_mpi_ompoffload $(F_HDF5_LIB_MPI) $(L_MPI_LIB) $(MPI_LINK) $(MPI_OMPOFFLOAD_LINK) -o $(APP)_mpi_ompoffload_tiled

#=========================================================================================================================

$(APP)_f2c_mpi_hip: Makefile .generated $(OPS_INSTALL_PATH)/fortran/lib/$(OPS_COMPILER)/libops_f2c_mpi_hip.a $(F2C_MPI_HIP_OBJ)
	@echo ""
	@echo ""
	@echo "Building ${APP}_mpi_hip"
	@echo ""
	$(MPIF90) $(FFLAGS) $(APP_FLAGS) -I$(C_OPS_INC) $(FMODS_F2C_HIP) $(I_MPI_INC) -DOPS_MPI $(F2C_MPI_HIP_OBJ) $(APP_LIBS) $(FLINK) -lops_f2c_mpi_hip $(F_HDF5_LIB_MPI) $(MPI_HIP_LINK) $(HIP_LINK) $(HIPRAND) $(L_MPI_LIB) $(MPI_LINK) -o $(APP)_f2c_mpi_hip

#=========================================================================================================================

cleanall: clean
	rm -rf ./mpi_openmp ./cuda ./openmp_offload ./f2c_mpi_openmp ./f2c_cuda ./f2c_hip

clean:
	rm -f .generated
	rm -f *.o mpi_openmp/*.o cuda/*.o openmp_offload/*.o
	rm -f *.oo mpi_openmp/*.oo cuda/*.oo openmp_offload/*.oo
	rm -f *.optrpt mpi_openmp/*.optrpt cuda/*.optrpt openmp_offload/*.optrpt
	rm -f *.lst mpi_openmp/*.lst cuda/*.lst openmp_offload/*.lst
	rm -f *.mod mpi_openmp/*.mod cuda/*.mod openmp_offload/*.mod
	rm -f *~ mpi_openmp/*~ cuda/*~ openmp_offload/*~
	rm -f constants_list.txt constants_offload.F90
	rm -f $(APP)_seq $(APP)_openmp $(APP)_tiled
	rm -f $(APP)_mpi $(APP)_mpi_openmp $(APP)_mpi_tiled 
	rm -f $(APP)_cuda $(APP)_mpi_cuda $(APP)_mpi_cuda_tiled 
	rm -f $(APP)_ompoffload $(APP)_mpi_ompoffload $(APP)_mpi_ompoffload_tiled
	rm -f $(APP)_f2c_mpi
	rm -f $(APP)_f2c_mpi_cuda
	rm -f $(APP)_f2c_mpi_hip

