!
! auto-generated by ops_fortran.py
!
SUBROUTINE output

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use MATHS_KERNEL_EQU_MODULE
  use OUTPUT_KERNEL_EQA_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga
















#ifdef HDF5
    use hdf5io
#endif



    CHARACTER (LEN=4) :: pnxres
    PARAMETER(pnxres = '.res')
    CHARACTER (LEN=2) :: pnxryf
    PARAMETER(pnxryf = 'yf')
    integer(kind=4) :: ncdiag
    PARAMETER(ncdiag = 11)
    integer(kind=4) :: iddump


    real(kind=8) :: deltag,fornow
    real(kind=8) :: ttemp(nxsize,nysize,nzsize)
    real(kind=8) :: ptemp(nxsize,nysize,nzsize)
    real(kind=8) :: ytemp(nspec,nxsize,nysize,nzsize)
    real(kind=8) :: tkeg

    integer(kind=4) :: ispec
    integer(kind=4) :: ic,jc,kc
    integer(kind=4) :: ix
    integer(kind=4) :: rangexyz(6)
    CHARACTER (LEN=21) :: fndiag

    CHARACTER (LEN=6) :: pnproc
    CHARACTER (LEN=11) :: strqty
    CHARACTER (LEN=2) :: strspc
    LOGICAL :: bcflag
    logical :: file_exist

    CHARACTER (LEN=60) :: fname
    CHARACTER (LEN=4) :: proc
    CHARACTER (LEN=5) :: ipdump










































































































































    IF(iproc == 0) THEN
        WRITE(*,'(I7,1PE12.4,I5)')itime,tstep,inderr
    END IF








    IF(MOD(itime,ntdump) == 0) THEN
      call print_dats()
      if (iproc==0) then
        inquire(file="test_dir/filed_time.dat",exist=file_exist)
        if (file_exist) then
          open(unit=1011,file="test_dir/filed_time.dat",STATUS='OLD',POSITION='APPEND',FORM='FORMATTED')
        else
          open(unit=1011,file="test_dir/filed_time.dat",STATUS='NEW',FORM='FORMATTED')
        end if
        write(1011,*)int(itime/ntdump),etime
        close(1011)
      end if
    END IF

    tkeg = zero
    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]


    call maths_kernel_eqU_host("A = B/C", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_utgv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_urhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_drhs, 1, s3d_000, "real(kind=8)", OPS_READ))

    call maths_kernel_eqU_host("A = B/C", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_vtgv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_vrhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_drhs, 1, s3d_000, "real(kind=8)", OPS_READ))

    call maths_kernel_eqU_host("A = B/C", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_wtgv, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_wrhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_drhs, 1, s3d_000, "real(kind=8)", OPS_READ))

    call output_kernel_eqA_host("Summing up energy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_drun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_utgv, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_vtgv, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_wtgv, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_reduce(h_tkes, 1, "real(kind=8)", OPS_INC))

    call ops_reduction_result(h_tkes,tkeg)
    if (iproc==0) then
      inquire(file="test_dir/tgv_stat.dat",exist=file_exist)
      if (file_exist) then
        open(unit=1011,file="test_dir/tgv_stat.dat",STATUS='OLD',POSITION='APPEND',FORM='FORMATTED')
      else
        open(unit=1011,file="test_dir/tgv_stat.dat",STATUS='NEW',FORM='FORMATTED')
      end if
      write(1011,*)etime,tkeg
      close(1011)
    end if






























END SUBROUTINE output
