!
! auto-generated by ops_fortran.py
!
SUBROUTINE pardom

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga















    INTEGER :: nextra
    INTEGER :: icproc





#ifndef OPS_MPI
   CALL p_init
#endif


#ifdef OPS_MPI
    call p_size(nproc,iproc)
#else
    nproc = 1
    iproc = 0
#endif



    ixproc = MOD(iproc,nxproc)
    iyproc = iproc/nxproc
    izproc = iyproc/nyproc
    iyproc = MOD(iyproc,nyproc)





    nxnode = nxglbl/nxproc
    nextra = MOD(nxglbl,nxproc)
    nextra = nxproc-nextra
    nxprm1 = nxproc-1
    DO icproc = 0,nxprm1
        npmapx(icproc) = nxnode
        IF(icproc >= nextra) npmapx(icproc) = nxnode+1
    END DO
   nxnode = npmapx(ixproc)

    nynode = nyglbl/nyproc
    nextra = MOD(nyglbl,nyproc)
    nextra = nyproc-nextra
    nyprm1 = nyproc-1
    DO icproc = 0,nyprm1
        npmapy(icproc) = nynode
        IF(icproc >= nextra) npmapy(icproc) = nynode+1
   END DO
   nynode = npmapy(iyproc)

    nznode = nzglbl/nzproc
    nextra = MOD(nzglbl,nzproc)
    nextra = nzproc-nextra
    nzprm1 = nzproc-1
    DO icproc = 0,nzprm1
        npmapz(icproc) = nznode
        IF(icproc >= nextra) npmapz(icproc) = nznode+1
    END DO
   nznode = npmapz(izproc)



    DO icproc = 0,nxprm1
        nprocx(icproc) = icproc+nxproc*(iyproc+nyproc*izproc)
    END DO
    DO icproc = 0,nyprm1
        nprocy(icproc) = ixproc+nxproc*(icproc+nyproc*izproc)
    END DO
    DO icproc = 0,nzprm1
        nprocz(icproc) = ixproc+nxproc*(iyproc+nyproc*icproc)
    END DO


END SUBROUTINE pardom
