!
! auto-generated by ops_fortran.py
!
SUBROUTINE parfer

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga



















    call ops_halo_transfer(halos_grp_x)


    IF(nhaloy /= 0) call ops_halo_transfer(halos_grp_y)


    IF(nhaloz /= 0) call ops_halo_transfer(halos_grp_z)


END SUBROUTINE parfer
