!
! auto-generated by ops_fortran.py
!
SUBROUTINE print_dats()
    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use COPY_KERNEL_MODULE
    use OPS_Fortran_hdf5_Declarations
    use OPS_CONSTANTS

    use, intrinsic :: ISO_C_BINDING

    use com_senga
    use com_ops_senga

    CHARACTER (LEN=60) :: fname
    CHARACTER (LEN=3) :: pnxres
    PARAMETER(pnxres = '.h5')
    CHARACTER(len=4) :: citime
    INTEGER :: num
    INTEGER :: rangexyz(6)
    rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)

    num = INT(itime/ntdump)

    WRITE(citime,'(I4.4)') num













    fname = 'test_dir/drun_timestep'//citime//pnxres
    call ops_fetch_block_hdf5_file(senga_grid, trim(fname))
    call ops_fetch_dat_hdf5_file(d_drun, trim(fname))

    fname = 'test_dir/urun_timestep'//citime//pnxres
    call ops_fetch_block_hdf5_file(senga_grid, trim(fname))
    call ops_fetch_dat_hdf5_file(d_urun, trim(fname))

    fname = 'test_dir/vrun_timestep'//citime//pnxres
    call ops_fetch_block_hdf5_file(senga_grid, trim(fname))
    call ops_fetch_dat_hdf5_file(d_vrun, trim(fname))

    fname = 'test_dir/wrun_timestep'//citime//pnxres
    call ops_fetch_block_hdf5_file(senga_grid, trim(fname))
    call ops_fetch_dat_hdf5_file(d_wrun, trim(fname))

    fname = 'test_dir/yrun_timestep'//citime//pnxres
    call ops_fetch_block_hdf5_file(senga_grid, trim(fname))
    call ops_fetch_dat_hdf5_file(d_yrun, trim(fname))

    call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d2prun, 1, s3d_000, "real(8)", OPS_WRITE), &
                      & ops_arg_dat(d_prun, 1, s3d_000, "real(8)", OPS_READ))

    call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d2trun, 1, s3d_000, "real(8)", OPS_WRITE), &
                      & ops_arg_dat(d_trun, 1, s3d_000, "real(8)", OPS_READ))

    fname = 'test_dir/trun_timestep'//citime//pnxres
    call ops_fetch_block_hdf5_file(senga_grid, trim(fname))
    call ops_fetch_dat_hdf5_file(d2trun, trim(fname))

    fname = 'test_dir/prun_timestep'//citime//pnxres
    call ops_fetch_block_hdf5_file(senga_grid, trim(fname))
    call ops_fetch_dat_hdf5_file(d2prun, trim(fname))























END SUBROUTINE print_dats
