!
! auto-generated by ops_fortran.py
!
SUBROUTINE print_dats()
    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use COPY_KERNEL_MODULE
    use OPS_Fortran_hdf5_Declarations
    use OPS_CONSTANTS

    use, intrinsic :: ISO_C_BINDING

    use com_senga
    use com_ops_senga

    integer(kind=4) :: ispec,dtime
    CHARACTER (LEN=60) :: fname
    CHARACTER (LEN=3) :: pnxres
    PARAMETER(pnxres = '.h5')
    CHARACTER(len=4) :: citime
    INTEGER :: rangexyz(6)
    rangexyz = (/1,nxglbl,1,nyglbl,1,nzglbl/)

    dtime=int(itime/ntdump)

    WRITE(citime,'(I4.4)') dtime














    fname = 'test_dir/timestep'//citime//pnxres
    call ops_fetch_block_hdf5_file(senga_grid, trim(fname))
    call ops_fetch_dat_hdf5_file(d_drun, trim(fname))

    call ops_fetch_dat_hdf5_file(d_urun, trim(fname))

    call ops_fetch_dat_hdf5_file(d_vrun, trim(fname))

    call ops_fetch_dat_hdf5_file(d_wrun, trim(fname))



    DO ispec = 1,nspcmx
        call ops_fetch_dat_hdf5_file(d_yrun(ispec), trim(fname))
    END DO

    call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d2prun, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_prun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call copy_kernel_host("copy", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d2trun, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ))

    call ops_fetch_dat_hdf5_file(d2trun, trim(fname))

    call ops_fetch_dat_hdf5_file(d2prun, trim(fname))














































END SUBROUTINE print_dats
