!
! auto-generated by ops_fortran.py
!
SUBROUTINE radcin

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga















    real(kind=8) :: pcount
    integer :: ispec,jspec,icoeff
    integer :: nrdspc,ncount
    integer :: iroot
    CHARACTER (LEN=10) :: spcrad(nspcmx)





    flradn = .false.


    IF(nfradn == 1) THEN





        iroot = 0


        pcount = zero


        DO ncount = 1, nparay
            parray(ncount) = zero
        END DO



        IF(iproc == 0) THEN




            OPEN(UNIT=ncradn,FILE=fnradn,STATUS='OLD',FORM='FORMATTED')



            READ(ncradn,*)
            READ(ncradn,*)
            READ(ncradn,*)
            READ(ncradn,*)
            READ(ncradn,*)



            READ(ncradn,*)
            READ(ncradn,'(I5)')nrdspc
            IF(nrdspc /= nspec) THEN
                WRITE(ncradn,*)
                WRITE(ncradn,*)'Warning: RADCIN: mismatch in no. of species'
                WRITE(ncradn,*)'CHEMIN: ',nspec,'; RADCIN: ',nrdspc
                WRITE(ncradn,*)
            END IF

            DO jspec = 1, nspec
                READ(ncradn,'(I5,3X,A)')ispec,spcrad(ispec)
                IF(spcsym(ispec) /= spcrad(ispec)) THEN
                    WRITE(ncrept,*)
                    WRITE(ncrept,*)'Warning: RADCIN: mismatch in species symbol'
                    WRITE(ncrept,*)'CHEMIN: ',spcsym(ispec), '; RADCIN: ',spcrad(ispec)
                    WRITE(ncrept,*)
                END IF
            END DO


            READ(ncradn,*)
            READ(ncradn,*)nsprad
            DO ispec = 1,nsprad
                READ(ncradn,*)jspec,nkprad(ispec)
                READ(ncradn,*) (akprad(icoeff,ispec),icoeff=1,nkprad(ispec))
                nsprid(ispec) = jspec
            END DO



            READ(ncradn,*)
            CLOSE(ncradn)





            ncount = 1
            DO ispec = 1,nspec
                ncount = ncount + 1
                parray(ncount) = REAL(nsprad,kind=8)
                DO icoeff = 1, nsprad
                    ncount = ncount + 1
                    parray(ncount) = akprad(icoeff,ispec)
                END DO
                ncount = ncount + 1
                parray(ncount) = REAL(nsprid(ispec),kind=8)
            END DO



            pcount = REAL(ncount,kind=8)


            IF(ncount > nparay) THEN
                WRITE(ncrept,*)
                WRITE(ncrept,*)'Warning: RADCIN: broadcast array size too small'
                WRITE(ncrept,*)'Actual: ',ncount,'; Available: ',nparay
                WRITE(ncrept,*)
            END IF


        END IF



        CALL p_bcst(pcount,1,1,iroot)
        ncount = nint(pcount)


        CALL p_bcst(parray,nparay,ncount,iroot)



        IF(iproc /= 0)THEN





            ncount = 1
            DO ispec = 1,nspec
                ncount = ncount + 1
                nsprad = nint(parray(ncount))
                DO icoeff = 1, nsprad
                    ncount = ncount + 1
                    akprad(icoeff,ispec) = parray(ncount)
                END DO
                ncount = ncount + 1
                nsprid(ispec) = nint(parray(ncount))
            END DO


        END IF





        DO ispec = 1,nspec
            nkprm1(ispec) = nkprad(ispec) - 1
        END DO



        foursb = four*stefbo
        trfrth = trefrn*trefrn*trefrn*trefrn

#ifdef OPS_WITH_CUDAFOR
        foursb_opsconstant = foursb
        trfrth_opsconstant = trfrth
#endif



        flradn = .true.


    END IF


END SUBROUTINE radcin
