!
! auto-generated by ops_fortran.py
!
SUBROUTINE radcal

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use SET_ZERO_KERNEL_MODULE
  use RADCAL_KERNEL_MEANCOEF_MODULE
  use RADCAL_KERNEL_ADDSPECIES_MODULE
  use RADCAL_KERNEL_ADDRADIATION_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga















    real(kind=8) :: plspec,fornow
    integer(kind=4) :: ispec,jspec,icp
    integer(kind=4) :: rangexyz(6)





    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_WRITE))


    DO jspec = 1, nsprad

        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call radcal_kernel_meancoef_host("PLANCK MEAN ABSORPTION COEF", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(akprad, ncfrmx*nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(nkprad, nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(nkprm1, nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(jspec, 1, "integer(kind=4)", OPS_READ))

        ispec = nsprid(jspec)

        rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
        call radcal_kernel_addspecies_host("ADD THE SPECIES CONTRIBUTION", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_RW), &
                          & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_dat(d_store2, 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(rgspec, nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))

    END DO


    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call radcal_kernel_addradiation_host("INCLUDE THE RADIATION TERM IN THE ENERGY EQUATION", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_erhs, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_store1, 1, s3d_000, "real(kind=8)", OPS_READ))


END SUBROUTINE radcal
