!
! auto-generated by ops_fortran.py
!
PROGRAM senga2

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
    use OPS_Fortran_hdf5_Declarations
    use OPS_CONSTANTS

    use, intrinsic :: ISO_C_BINDING

    use com_senga
    use com_ops_senga

































    integer(kind=4) :: jtime,jrkstp

    real(kind=c_double) :: startTime = 0
    real(kind=c_double) :: endTime = 0





    call ops_init(6)
    call ops_set_soa(0)

    call ops_timers ( startTime )

    call ops_data_init

    call pardom

    call indata

    call output

    call cuda_const_init




    DO jtime = ntime1,ntime2

        itime = jtime





        DO jrkstp = 1,nrksm1

            irkstp = jrkstp

            call boundt

            call parfer

            call rhscal
#ifdef OPS_LAZY
    call ops_execute()
#endif

            call rhsvel

            call bounds

            call lincom

        END DO



        irkstp = nrkstp

        call boundt

        call parfer

        call rhscal
#ifdef OPS_LAZY
    call ops_execute()
#endif

        call rhsvel

        call bounds

        call fincom



        etime = etime + tstep



        call bountt



        call adaptt



        call output
        print *, iproc, "is here"



    END DO



    call ops_timers ( endTime )
    call ops_timing_output( )
    IF (ops_is_root() .eq. 1) THEN
        write (*,'(a,f16.7,a)') 'Max total runtime =', endTime - startTime,' seconds'
    END IF

    call finish


    call ops_exit( )

END PROGRAM senga2
