!
! auto-generated by ops_fortran.py
!
SUBROUTINE temper

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use TEMPER_KERNEL_EQA_MODULE
  use SET_ZERO_KERNEL_MD6_MODULE
  use SET_ZERO_KERNEL_MD5_MODULE
  use SET_ZERO_KERNEL_MODULE
  use TEMPER_KERNEL_EQB_MODULE
  use TEMPER_KERNEL_EQC_MODULE
  use TEMPER_KERNEL_EQD_MODULE
  use SET_ZERO_KERNEL_INT_MODULE
  use TEMPER_KERNEL_EQE_MODULE
  use TEMPER_KERNEL_EQF_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga













    integer(kind=4) :: icp, ispec, rangexyz(6)
    integer(kind=4) :: iindex,ipower,icoef1,icoef2






    rangexyz(1) = 1-nhalox
    IF (nsbcxl == nsbco1 .or. nsbcxl == nsbci1 .or. nsbcxl == nsbci2 .or. &
        nsbcxl == nsbci3 .or. nsbcxl == nsbcw1 .or. nsbcxl == nsbcw2) rangexyz(1) = 1

    rangexyz(2) = nxglbl+nhalox
    IF (nsbcxr == nsbco1 .or. nsbcxr == nsbci1 .or. nsbcxr == nsbci2 .or. &
        nsbcxr == nsbci3 .or. nsbcxr == nsbcw1 .or. nsbcxr == nsbcw2) rangexyz(2) = nxglbl

    rangexyz(3) = 1-nhaloy
    IF (nsbcyl == nsbco1 .or. nsbcyl == nsbci1 .or. nsbcyl == nsbci2 .or. &
        nsbcyl == nsbci3 .or. nsbcyl == nsbcw1 .or. nsbcyl == nsbcw2) rangexyz(3) = 1

    rangexyz(4) = nyglbl+nhaloy
    IF (nsbcyr == nsbco1 .or. nsbcyr == nsbci1 .or. nsbcyr == nsbci2 .or. &
        nsbcyr == nsbci3 .or. nsbcyr == nsbcw1 .or. nsbcyr == nsbcw2) rangexyz(4) = nyglbl

    rangexyz(5) = 1-nhaloz
    IF (nsbczl == nsbco1 .or. nsbczl == nsbci1 .or. nsbczl == nsbci2 .or. &
        nsbczl == nsbci3 .or. nsbczl == nsbcw1 .or. nsbczl == nsbcw2) rangexyz(5) = 1

    rangexyz(6) = nzglbl+nhaloz
    IF (nsbczr == nsbco1 .or. nsbczr == nsbci1 .or. nsbczr == nsbci2 .or. &
        nsbczr == nsbci3 .or. nsbczr == nsbcw1 .or. nsbczr == nsbcw2) rangexyz(6) = nzglbl


    call temper_kernel_eqA_host("temper eq A", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_tcoeff, 6, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_drhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_urhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_vrhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_wrhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_erhs, 1, s3d_000, "real(kind=8)", OPS_READ))

    DO icp = 1, nctmax
        call set_zero_kernel_MD6_host("set_zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_tcoeff, 6, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_gbl(icp+1, 1, "integer(kind=4)", OPS_READ))

        call set_zero_kernel_MD5_host("set_zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_tderiv, 5, s3d_000, "real(kind=8)", OPS_WRITE), &
                          & ops_arg_gbl(icp, 1, "integer(kind=4)", OPS_READ))
    END DO


    call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_store7, 1, s3d_000, "real(kind=8)", OPS_WRITE))


    DO ispec = 1, nspec

        iindex = 1 + (ispec-1)/nspimx
        ipower = ispec - (iindex-1)*nspimx - 1
        icoef2 = ntbase**ipower
        icoef1 = icoef2*ntbase


        call temper_kernel_eqB_host("temper eq B", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_tcoeff, 6, s3d_000, "real(kind=8)", OPS_RW), &
                          & ops_arg_dat(d_tderiv, 5, s3d_000, "real(kind=8)", OPS_RW), &
                          & ops_arg_dat(d_itndex(iindex), 1, s3d_000, "integer(kind=4)", OPS_WRITE), &
                          & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(amascp, ncofmx*ntinmx*nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(amasct, ncofmx*ntinmx*nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ncpoly, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ncenth, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ipower, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(icoef1, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(icoef2, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))



        call temper_kernel_eqC_host("temper eq C", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_store7, 1, s3d_000, "real(kind=8)", OPS_RW), &
                          & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(rgspec, nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ))


    END DO



    call temper_kernel_eqD_host("temper eq D", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_tcoeff, 6, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_tderiv, 5, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_drhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_urhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_vrhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_wrhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_erhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_idx())


    DO iindex = 1,nintmx
        call set_zero_kernel_int_host("set_zero", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_itndex(iindex), 1, s3d_000, "integer(kind=4)", OPS_WRITE))
    END DO

    call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_transp, 1, s3d_000, "real(kind=8)", OPS_WRITE))

    DO ispec = 1, nspec

        iindex = 1 + (ispec-1)/nspimx
        ipower = ispec - (iindex-1)*nspimx - 1

        call temper_kernel_eqE_host("temper eq E", senga_grid, 3, rangexyz, &
                          & ops_arg_dat(d_transp, 1, s3d_000, "real(kind=8)", OPS_RW), &
                          & ops_arg_dat(d_itndex(iindex), 1, s3d_000, "integer(kind=4)", OPS_RW), &
                          & ops_arg_dat(d_yrhs(ispec), 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(amascp, ncofmx*ntinmx*nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ncpoly, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ncpom1, ntinmx*nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(tinthi, ntinmx*nspcmx, "real(kind=8)", OPS_READ), &
                          & ops_arg_gbl(ntint, nspcmx, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ispec, 1, "integer(kind=4)", OPS_READ), &
                          & ops_arg_gbl(ipower, 1, "integer(kind=4)", OPS_READ))

    END DO


    call temper_kernel_eqF_host("temper eq F", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_transp, 1, s3d_000, "real(kind=8)", OPS_RW), &
                      & ops_arg_dat(d_prun, 1, s3d_000, "real(kind=8)", OPS_WRITE), &
                      & ops_arg_dat(d_drhs, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_trun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_store7, 1, s3d_000, "real(kind=8)", OPS_READ))


END SUBROUTINE temper
