!
! auto-generated by ops_fortran.py
!
SUBROUTINE turbin

    use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use TURBIN_KERNEL_EQA_MODULE
  use TURBIN_KERNEL_EQB_MODULE
  use TURBIN_KERNEL_EQC_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga


















    real(kind=8) :: espect,ranuni
    EXTERNAL espect,ranuni


    real(kind=8), parameter :: vectol=0.00001_8, tolimg=1.0E-6


    real(kind=8) :: vectk1,vectk2,vectk3,vksize,ovksiz
    real(kind=8) :: velmag,vfactr,plnmag
    real(kind=8) :: ovplmg,aziang,cosazi,sinazi
    real(kind=8) :: phang1,phang2,cosph1,sinph1,cosph2,sinph2
    real(kind=8) :: vaterm,vbterm
    real(kind=8) :: tklodd
    real(kind=8) :: twopi,ovtopi
    real(kind=8) :: ubart,vbart,wbart,uvart,vvart,wvart,tket
    real(kind=8) :: ubartt,vbartt,wbartt,uvartt,vvartt,wvartt,tketot
    real(kind=8) :: ubartl,vbartl,wbartl,uvartl,vvartl,wvartl,tketl
    real(kind=8) :: ubartg,vbartg,wbartg,uvartg,vvartg,wvartg,tketg
    real(kind=8) :: udev,vdev,wdev,faclav,facgav
    integer(kind=4) :: ic,jc,kc,ix,jx,kx,icproc
    integer(kind=4) :: igofst,jgofst,kgofst,igofm1,jgofm1,kgofm1
    integer(kind=4) :: igstal,jgstal,kgstal,igstol,jgstol,kgstol
    integer(kind=4) :: nodblx,nodbly,nodblz
    integer(kind=4) :: ngoddx,ngoddy,ngoddz
    integer(kind=4) :: iseed
    LOGICAL :: flagim
    LOGICAL :: flrani,flranj,flrank

    integer(kind=4) :: rangexyz(6)



    write(*, '(a)') "Using the arrays not allocated by OPS, &
                        Please implement the function in OPS first, turbin.F90: ID=84"
            STOP



    ngoddx = MOD(nxglbl,2)
    ngoddy = MOD(nyglbl,2)
    ngoddz = MOD(nzglbl,2)

    nodblx = nxglbl/2 - 1 + ngoddx
    nodbly = nyglbl/2 - 1 + ngoddy
    nodblz = nzglbl/2 - 1 + ngoddz

    igofst = 0
    DO icproc = 0, ixproc-1
        igofst = igofst + npmapx(icproc)
    END DO
    igstal = igofst+1
    igstol = igofst + npmapx(ixproc)
    igofm1 = igofst-1

    jgofst = 0
    DO icproc = 0, iyproc-1
        jgofst = jgofst + npmapy(icproc)
    END DO
    jgstal = jgofst+1
    jgstol = jgofst + npmapy(iyproc)
    jgofm1 = jgofst-1

    kgofst = 0
    DO icproc = 0, izproc-1
        kgofst = kgofst + npmapz(icproc)
    END DO
    kgstal = kgofst+1
    kgstol = kgofst + npmapz(izproc)
    kgofm1 = kgofst-1


    twopi = two*pi
    ovtopi = one/twopi
    tklodd = zero



    IF(inseed >= 0)THEN


        iseed = inseed + iproc
        call ranini(iseed)


        DO kc = 1,nzsize
            DO jc = 1,nysize
                DO ic = 1,nxsize

                    utmp(ic,jc,kc) = ranuni(iseed)
                    vtmp(ic,jc,kc) = ranuni(iseed)
                    wtmp(ic,jc,kc) = ranuni(iseed)

                END DO
            END DO
        END DO

    ELSE


        iseed = inseed
        call ranini(iseed)

        DO kc = 1,nzglbl
        DO jc = 1,nyglbl
        DO ic = 1,nxglbl

        aziang = ranuni(iseed)
        phang1 = ranuni(iseed)
        phang2 = ranuni(iseed)

        flrani = (ic >= igstal).AND.(ic <= igstol)
        flranj = (jc >= jgstal).AND.(jc <= jgstol)
        flrank = (kc >= kgstal).AND.(kc <= kgstol)

        IF(flrani.AND.flranj.AND.flrank)THEN

          ix = ic - igofst
          jx = jc - jgofst
          kx = kc - kgofst

          write(*, '(a)') "Using the arrays not allocated by OPS, &
                        Please implement the function in OPS first, turbin.F90: line number 190"
          STOP

          utmp(ix,jx,kx) = aziang
          vtmp(ix,jx,kx) = phang1
          wtmp(ix,jx,kx) = phang2

        END IF

        END DO
        END DO
        END DO

    END IF



    call espini




    DO kc = 1,nzsize

    kx = kgofm1 + kc
    IF(kx > nodblz)kx = kx-nzglbl

    DO jc = 1,nysize

    jx = jgofm1 + jc
    IF(jx > nodbly)jx = jx-nyglbl

    DO ic = 1,nxsize

      ix = igofm1 + ic
      IF(ix > nodblx)ix = ix-nxglbl

      flrank = (kx > 0)
      flranj = (kx == 0).AND.(jx > 0)
      flrani = (kx == 0).AND.(jx == 0).AND.(ix >= 0)

      IF(flrani.OR.flranj.OR.flrank)THEN


        vectk1 = REAL(ix,kind=8)
        vectk2 = REAL(jx,kind=8)
        vectk3 = REAL(kx,kind=8)
        vksize = SQRT(vectk1*vectk1+vectk2*vectk2+vectk3*vectk3)

        ovksiz = one
        IF(vksize > vectol)ovksiz = one/vksize

        plnmag = SQRT(vectk1*vectk1 + vectk2*vectk2)


        IF(plnmag < vectol)THEN

          ovplmg = one
          vectk1 = zero
          vectk2 = one
        ELSE
          ovplmg = one/plnmag
        END IF


        velmag = espect(vksize)

        velmag = SQRT(velmag*ovtopi)*ovksiz


        aziang = utmp(ic,jc,kc)
        aziang = twopi*aziang
        cosazi = COS(aziang)
        sinazi = SIN(aziang)


        phang1 = vtmp(ic,jc,kc)
        phang1 = pi*(two*phang1-one)
        cosph1 = COS(phang1)
        sinph1 = SIN(phang1)
        phang2 = wtmp(ic,jc,kc)
        phang2 = pi*(two*phang2-one)
        cosph2 = COS(phang2)
        sinph2 = SIN(phang2)

        vfactr = velmag*ovksiz*ovplmg

        vaterm = vfactr*vksize*vectk2*cosazi
        vbterm = vfactr*vectk1*vectk3*sinazi

        urun(ic,jc,kc) = vaterm*cosph1 + vbterm*cosph2

        utmp(ic,jc,kc) = vaterm*sinph1 + vbterm*sinph2

        vaterm = vfactr*vksize*vectk1*cosazi
        vbterm = vfactr*vectk2*vectk3*sinazi

        vrun(ic,jc,kc) = vbterm*cosph2 - vaterm*cosph1

        vtmp(ic,jc,kc) = vbterm*sinph2 - vaterm*sinph1


        vbterm = -vfactr*plnmag*plnmag*sinazi

        wrun(ic,jc,kc) = vbterm*cosph2

        wtmp(ic,jc,kc) = vbterm*sinph2

      ELSE


        urun(ic,jc,kc) = zero
        utmp(ic,jc,kc) = zero
        vrun(ic,jc,kc) = zero
        vtmp(ic,jc,kc) = zero
        wrun(ic,jc,kc) = zero
        wtmp(ic,jc,kc) = zero

      END IF

    END DO
    END DO
    END DO



    tket = zero
    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call turbin_kernel_eqA_host("CHECK ENERGY CONTENT", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_utmp, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_vtmp, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_dat(d_wtmp, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_reduce(h_tket, 1, "real(kind=8)", OPS_INC))

    call ops_reduction_result(h_tket, tket)


    tketot = tket

    IF(iproc == 0)THEN
        WRITE(ncrept,*)'Fourier-space turbulence kinetic energy'
        WRITE(ncrept,'(1PE12.4)')tketot
    END IF



    call turbft



    DO kc = 1,nzsize
    DO jc = 1,nysize
    DO ic = 1,nxsize

      flagim = .false.
      IF(utmp(ic,jc,kc) > tolimg)flagim = .true.
      IF(vtmp(ic,jc,kc) > tolimg)flagim = .true.
      IF(wtmp(ic,jc,kc) > tolimg)flagim = .true.
      IF(flagim)THEN
        WRITE(6,*)'Warning: Imaginary part too large',iproc
        WRITE(6,'(3I5,3(1PE12.4))')ic,jc,kc,  &
            utmp(ic,jc,kc),vtmp(ic,jc,kc),wtmp(ic,jc,kc)
      END IF

    END DO
    END DO
    END DO




    faclav = one/REAL(nxsize,kind=8)/REAL(nysize,kind=8)/REAL(nzsize,kind=8)
    facgav = one/REAL(nxglbl,kind=8)/REAL(nyglbl,kind=8)/REAL(nzglbl,kind=8)


    ubart = zero
    vbart = zero
    wbart = zero

    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call turbin_kernel_eqB_host("VELOCITY MEANS", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_reduce(h_ubart, 1, "real(kind=8)", OPS_INC))
    call ops_reduction_result(h_ubart, ubart)

    call turbin_kernel_eqB_host("VELOCITY MEANS", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_reduce(h_vbart, 1, "real(kind=8)", OPS_INC))
    call ops_reduction_result(h_vbart, vbart)

    call turbin_kernel_eqB_host("VELOCITY MEANS", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_reduce(h_wbart, 1, "real(kind=8)", OPS_INC))
    call ops_reduction_result(h_wbart, wbart)

    ubartl = ubart*faclav
    vbartl = vbart*faclav
    wbartl = wbart*faclav


    ubartt = ubart

    vbartt = vbart

    wbartt = wbart

    ubartg = ubartt*facgav
    vbartg = vbartt*facgav
    wbartg = wbartt*facgav



    uvart = zero
    vvart = zero
    wvart = zero

    rangexyz = [1,nxglbl,1,nyglbl,1,nzglbl]
    call turbin_kernel_eqC_host("VELOCITY VARIANCES", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_urun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(ubartg, 1, "real(kind=8)", OPS_READ), &
                      & ops_arg_reduce(h_uvart, 1, "real(kind=8)", OPS_INC))
    call ops_reduction_result(h_uvart, uvart)

    call turbin_kernel_eqC_host("VELOCITY VARIANCES", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_vrun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(vbartg, 1, "real(kind=8)", OPS_READ), &
                      & ops_arg_reduce(h_vvart, 1, "real(kind=8)", OPS_INC))
    call ops_reduction_result(h_vvart, vvart)

    call turbin_kernel_eqC_host("VELOCITY VARIANCES", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(d_wrun, 1, s3d_000, "real(kind=8)", OPS_READ), &
                      & ops_arg_gbl(wbartg, 1, "real(kind=8)", OPS_READ), &
                      & ops_arg_reduce(h_wvart, 1, "real(kind=8)", OPS_INC))
    call ops_reduction_result(h_wvart, wvart)

    tket   = half*(uvart+vvart+wvart)

    uvartl = uvart*faclav
    vvartl = vvart*faclav
    wvartl = wvart*faclav
    tketl  = half*(uvartl+vvartl+wvartl)


    uvartt = uvart

    vvartt = vvart

    wvartt = wvart

    tketot = tket

    uvartg = uvartt*facgav
    vvartg = vvartt*facgav
    wvartg = wvartt*facgav
    tketg  = tketot*facgav

    IF(iproc == 0) THEN
        WRITE(ncrept,*)'Physical-space turbulence kinetic energy'
        WRITE(ncrept,'(1PE12.4)')tketg
        WRITE(ncrept,*)
        WRITE(ncrept,*)'Velocity means:'
        WRITE(ncrept,'(3(1PE12.4))')ubartg,vbartg,wbartg
        WRITE(ncrept,*)'Velocity variances:'
        WRITE(ncrept,'(3(1PE12.4))')uvartg,vvartg,wvartg
        WRITE(ncrept,*)
    END IF


END SUBROUTINE turbin
