!
! auto-generated by ops_fortran.py
!
SUBROUTINE zerozr(farray)
 use OPS_Fortran_Declarations
  use OPS_Fortran_RT_Support
  use SET_ZERO_KERNEL_MODULE

    use OPS_CONSTANTS
    use, intrinsic :: ISO_C_BINDING

    use data_types
    use com_senga
    use com_ops_senga


    TYPE(ops_dat) :: farray


    integer(kind=4) :: rangexyz(6)



    rangexyz = [1,nxglbl,1,nyglbl,nzglbl,nzglbl]
    call set_zero_kernel_host("set_zero", senga_grid, 3, rangexyz, &
                      & ops_arg_dat(farray, 1, s3d_000, "real(kind=8)", OPS_WRITE))


END SUBROUTINE zerozr
