#!/bin/sh
#
# Make stub library for MPI calls
#
#
mpif90 -O3 -Wall -c p_init.f
mpif90 -O3 -Wall -c p_stop.f
#
mpif90 -O3 -Wall -c p_gmax.f
mpif90 -O3 -Wall -c p_gmin.f
mpif90 -O3 -Wall -c p_summ.f
#
mpif90 -O3 -Wall -c p_bcst.f
#
mpif90 -O3 -Wall -c p_send.f
mpif90 -O3 -Wall -c p_recv.f
#
mpif90 -O3 -Wall -c p_size.f
mpif90 -O3 -Wall -c p_sync.f
#
ar rcsv mpi_stub.a \
        p_init.o p_stop.o \
        p_gmax.o p_gmin.o p_summ.o \
        p_bcst.o \
        p_send.o p_recv.o \
        p_size.o p_sync.o
#
rm *.o
#
exit
